CODEOWNERS, OWNERS_ALIASES, components/kyma-metrics-collector/OWNERS, resources/kcp/charts/kyma-metrics-collector/OWNERS
- modify CODEOWNERS for KMC
- introduce ONWERS_ALIASES and OWNERS for KMC
=> modify codeowners for KMC

tools/cli/pkg/ers/command/instances.go
- allows to have json output in ers tool
=> Json output in ers tool

resources/kcp/values.yaml
The `sc-migration` reconciler will deprecate https://github.com/SAP/sap-btp-service-operator-migration and https://github.com/kyma-incubator/sc-removal currently being executed as `Jobs`.
Depends on:
=> Register sc-migration reconciler

CODEOWNERS, OWNERS, OWNERS_ALIASES, resources/kcp/OWNERS
Since Kamil left the company last month and Chris is on paternity leave, we need to update the CODEOWNERS and OWNERS  files.
- Remove ksputo from CODEOWNERS
- Remove voigt from CODEOWNERS
- Update OWNERS and OWNER_ALIASES
=> Update OWNERS and CODEOWNERS files

resources/kcp/charts/component-reconcilers/templates/deployment.yaml
- Add an optional GIT CLONE TOKEN environment variable to the Component Reconciler
See the related issue - https://github.com/kyma-incubator/reconciler/issues/418
=> Add GIT CLONE TOKEN environment variable to the Component Reconciler

resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
Reduce the retention time of reconciliation entries to 4 days.
=> Reduce retention of reconciliations to 4days

components/provisioner/Dockerfile, resources/kcp/values.yaml
- Bump Provisioners base images
=> Bump Provisioners base images

tools/reconciler/e2e-test/template-kyma-main.json
- `istio-configuration` was renamed to `istio`
- ...
- ...
=> Remane istio component

resources/kcp/values.yaml
- Bumping KEB image tag to deploy issuerUrl normalisation 
https://github.com/kyma-project/control-plane/pull/1473
=> Normalize user input for isserURL - image bump

components/kyma-environment-broker/go.mod, components/kyma-environment-broker/go.sum, resources/kcp/values.yaml
- Updated the KEB to use the latest provisioner version from the merged PR https://github.com/kyma-project/control-plane/pull/1462
=> Point to the new provisioner version in KEB

resources/kcp/charts/component-reconcilers/charts/rma/templates/policy.yaml, resources/kcp/charts/component-reconcilers/charts/rma/templates/service-monitor.yaml, resources/kcp/charts/component-reconcilers/charts/rma/values.yaml
fix for https://github.tools.sap/kyma/backlog/issues/2456
=> add PeerAuthentication ServiceMonitor for rma

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/internal/process/input/input.go, components/kyma-environment-broker/internal/provider/aws_provider.go, components/kyma-environment-broker/internal/provider/azure_provider.go, components/kyma-environment-broker/internal/provider/azure_provider_test.go, components/kyma-environment-broker/internal/provider/gcp_provider.go, components/kyma-environment-broker/internal/provider/openstack_provider.go, resources/kcp/values.yaml
- if user provides an empty region in provisioning parameters, KEB should do the same as the region is nil
=> Do not use empty region

tools/reconciler/e2e-test/template-kyma-2-1-x.json
I have created a template for a reconciler request which is sufficient to work with Kyma 2.1.x. (Same as current main-template). We need this differentiation, to be able to continue to work on Kyma main and adapt its template without interfering with Kyma2.0.x or Kyma2.1.x.
- Introduction of Kyma2.1.x template which will be used by pipelines
- ...
- ...
=> Template for reconciler when reconciling Kyma2.1.x

.github/dependabot-config.yaml, .github/dependabot.yml
Enable dependabot for kyma environment broker and run rendertemplates.
closes: https://github.com/kyma-project/control-plane/issues/1472
=> Enable dependabot for KEB

tools/cli/pkg/ers/client/fake.go, tools/cli/pkg/ers/command/migrate_all.go, tools/cli/pkg/ers/command/migration.go
=> Fake ers client in ers tool

tools/cli/pkg/ers/client/http.go, tools/cli/pkg/ers/command/instances.go
- do not use fmt.Println in a ers client (ERS tool)
=> Remove unnecessary messages in ers tool

tools/cli/pkg/ers/command/migrate_all.go, tools/cli/pkg/ers/command/stats.go
- Simple stats for displaying `err`, `done` and `all` counters.
=> Simple Stats

resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- scrape Timeout added in service-monitor
=> scrapeTimeout added

resources/kcp/charts/component-reconcilers/templates/deployment.yaml, resources/kcp/charts/mothership-reconciler/templates/deployment.yaml, resources/kcp/values.yaml
Add option configure features in component reconciler deployment
- allow configuration of env vars in deployment template of component reconciler
https://github.com/kyma-incubator/reconciler/issues/868
=> Add option to configure features in component reconciler deployment

tools/cli/pkg/command/send_slack_notification.go
appending the cluster (e.g. `kcp-stage/prod`) when sending slack notification
=> append cluster env when sending slack msg

tools/cli/pkg/ers/command/migrate_all.go
=> ERS CLI - Increased Timeout

tools/cli/pkg/ers/command/status.go
=> Regex Logs Correction

tools/cli/pkg/ers/command/migrate_all.go
- Duplicate call for decreasing WaitGroup value.
=> Corrected Unnecessary WaitGroup Calls

components/kyma-metrics-collector/go.mod, components/kyma-metrics-collector/go.sum, resources/kcp/values.yaml
this pr upgrades the used gardener package to fix security issues.
=> bump gardener deps

components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go, resources/kcp/values.yaml
- add additional condition to check whether service instance is present in the cluster
See also #1521
=> Fix remove service instance step

components/kyma-environment-broker/Dockerfile.cleanup, components/kyma-environment-broker/Dockerfile.sac, components/schema-migrator/Dockerfile
- Version bumps in KEB Dockerfiles.
=> Version Bumps

resources/kcp/charts/mothership-reconciler/templates/deployment.yaml, resources/kcp/values.yaml
Downgrade mothership reconciler to be3fe478
=> Downgrade mothership reconciler to be3fe478

resources/kcp/values.yaml, tools/cli/go.mod, tools/cli/go.sum
- updating go mod file,
- tools/cli tidy.
=> Values Update & Cli Tidy

components/provisioner/go.mod, components/provisioner/go.sum, components/provisioner/internal/api/resolver_integration_test.go, components/provisioner/internal/api/validator_test.go, components/provisioner/internal/provisioning/input_converter_test.go, components/provisioner/internal/provisioning/service.go, resources/kcp/values.yaml
- Compare the k8s versions correctly in Provisioner
=> Compare the k8s versions correctly in Provisioner

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go, resources/kcp/values.yaml
=> Do not call Provisioner in case of svcat migration

tools/cli/go.mod, tools/cli/go.sum, tools/cli/pkg/command/taskrun.go
- fix cli compilation errors caused by removing gardener dependencies
=> Use dynamic interface for gardener api

tools/cli/pkg/ers/client/client.go, tools/cli/pkg/ers/client/http.go, tools/cli/pkg/ers/command/broker.go
=> Fix ERS switch command

components/kyma-environment-broker/cmd/broker/main.go, resources/kcp/values.yaml
- fix condition for upgrade shoot step
=> Fix condition for upgrade shoot step in the update queue

components/kubeconfig-service/Dockerfile
to fix the security-scans  https://github.tools.sap/kyma/security-scans/issues/15386
=> fix protecode on kubeconfig-service

components/provisioner/internal/apperrors/apperrors.go, components/provisioner/internal/director/directorclient.go, components/provisioner/internal/installation/installation.go, components/provisioner/internal/installation/resource_cleanup.go, components/provisioner/internal/operations/executor.go, components/provisioner/internal/operations/executor_test.go, components/provisioner/internal/operations/stages/deprovisioning/cleanup_cluster.go, components/provisioner/internal/operations/stages/deprovisioning/cleanup_cluster_test.go, components/provisioner/internal/operations/stages/deprovisioning/delete_cluster.go, components/provisioner/internal/operations/stages/deprovisioning/delete_cluster_test.go, components/provisioner/internal/operations/stages/deprovisioning/trigger_kyma_uninstall.go, components/provisioner/internal/operations/stages/deprovisioning/trigger_kyma_uninstall_test.go, components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion.go, components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion_test.go, components/provisioner/internal/operations/stages/provisioning/install_kyma.go, components/provisioner/internal/provisioning/service.go, components/provisioner/internal/provisioning/service_test.go, resources/kcp/values.yaml
- This PR is to separate the code changes of provisioner from the PR-1579 https://github.com/kyma-project/control-plane/pull/1579
- Make the errors categorized as error component(category), error reason and error message.
- Add provisioner timeout error reason
[backlog #1933](https://github.tools.sap/kyma/backlog/issues/1933)
=> Errors categorization for deprovisioning - changes for provisioner

components/kyma-environment-broker/internal/metrics/operations_collector.go, resources/kcp/charts/kyma-environment-broker/files/dashboard.json, resources/kcp/values.yaml
- Added the plans `aws_ha`, `azure_ha`, `openstack` and `preview` to the compass_keb_operations_provisioning_<state>_total metrics to support all plans so far.
=> Add plans to compass_keb_operations_provisioning_<state>_total metrics to support all plans

components/kyma-environment-broker/internal/process/provisioning/external_eval_step.go
- Update external evaluation target URL to [istio-healthz  virtualservice ](https://github.com/kyma-project/kyma/blob/main/resources/istio-resources/templates/virtualservice.yaml)
=> Update externalEvalCreator target URL

resources/kcp/values.yaml
- bumps reconciler images with log level decrease
- https://github.com/kyma-incubator/reconciler/pull/1040
=> bumps reconciler images with log level decrease

components/kyma-environment-broker/internal/process/provisioning/external_eval_step.go, resources/kcp/values.yaml
- Fix issue in https://github.com/kyma-project/control-plane/pull/1605/files
=> bugfix: remove extra shootName from external evaluation  targetURL

resources/kcp/charts/mothership-reconciler/templates/deployment.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Introduce helm values to toggle between old and new mothership cleaner scripts
- By default the old cleaner script is enabled
- To enable new cleaner script, changes in the management plane config need to be performed
https://github.com/kyma-incubator/reconciler/pull/1057
=> feat: cleaner config helm values

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/broker/instance_create_test.go, components/kyma-environment-broker/internal/broker/instance_get_test.go, components/kyma-environment-broker/internal/broker/instance_update.go, components/kyma-environment-broker/internal/broker/instance_update_test.go, components/kyma-environment-broker/internal/dashboard/config.go, resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/values.yaml
- Replace legacy console URL with Kyma Dashboard for newly provisioned instances.
- Replace legacy console URL with Kyma Dashboard for existing instances on update.
- Add feature flag for Kyma Dashboard
- Add feature flag to KEB chart
=> Replace legacy console URL with Kyma Dashboard

resources/kcp/values.yaml
Change the version of the connectivity-proxy component reconciler.
[Issue](https://github.com/kyma-incubator/reconciler/issues/676)
=> Change the version of the connectivity-proxy reconciler

components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go, components/kyma-environment-broker/internal/process/deprovisioning/utils.go, resources/kcp/values.yaml
- skip GetKubeconfig step in deprovisioning when kubeconfig is not provided
=> Skip GetKubeconfig step in deprovisioning when kubeconfig is not provided

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/internal/component_input_helpers.go, resources/kcp/values.yaml
BTP-Operator introduced breaking change in helm arguments, this PR adds support for both v0.2.2 and below as well as v0.2.3.
https://github.com/kyma-incubator/sap-btp-service-operator/pull/16#discussion_r860841940
=> Overrides for btp-operator v0.2.3

resources/kcp/values.yaml
https://github.com/kyma-incubator/reconciler/compare/4ce04418...f342be0b
=> Bump reconciler to f342be0b

components/kyma-metrics-collector/go.mod, components/kyma-metrics-collector/go.sum, resources/kcp/values.yaml
This bumps the dependencies for `gardener` in KMV to avoid potential security issues.
=> KMC bump gardener

CODEOWNERS
- remove user alexandra-simeonova from codeowners
=> fix error in codeowners

tools/cli/pkg/ers/command/migrate_all.go, tools/cli/pkg/ers/model.go
=> ERS cli changes, block already migrated

tools/cli/pkg/ers/command/migrate_all.go
=> Do not spam ers

components/kubeconfig-service/pkg/endpoints/endpoint.go
try to fix the checkmarx issue [Permissive_Content_Security_Policy/components/kubeconfig-service/pkg/endpoints/endpoint.go:42-42 [control-plane/kubeconfig-service]](https://cx.wdf.sap.corp/CxWebClient/ViewerMain.aspx?scanid=10347240&projectid=87240&pathid=251)
=> fix kubeconfig-service checkmarx issue

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/process/update/manager.go, resources/kcp/values.yaml
- the update process must be able to process more updates at the same time
=> Increase concurrency for KEB processing update operations

components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/internal/broker/instance_update.go, components/kyma-environment-broker/internal/suspension/handler.go, resources/kcp/values.yaml, tools/cli/pkg/ers/command/migrate_all.go
- When the migration update is done for suspended SKR, the unsuspension process must create a Kyma with btp operator
=> Handle migration for suspended SKRs

resources/kcp/values.yaml
- bump cloudsql-proxy image to the newest version
=> Bump cloudsql-proxy image to v1.30.1

components/kyma-environment-broker/go.mod, components/kyma-environment-broker/go.sum
- update indirect docker dependency to v20.10.16
=> Update docker dependency to v20.10.16

components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go, components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step_test.go, components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go, components/kyma-environment-broker/internal/process/deprovisioning/utils.go, resources/kcp/values.yaml
- add not found error check,
- add tests for step.
=> Fix GetKubeconfig step in deprovisioning queue

components/kubeconfig-service/cmd/generator/main.go, components/kubeconfig-service/pkg/endpoints/endpoint.go, components/kubeconfig-service/pkg/runtime/runtime.go, components/kubeconfig-service/pkg/runtime/runtime_kcp.go, components/kubeconfig-service/pkg/runtime/runtime_test.go
=> [testing]feature: kcp runtime functions for kubeconfig-serivce

components/kyma-environment-broker/internal/dto.go, components/kyma-environment-broker/internal/process/update/initialisation_step.go, components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go, resources/kcp/values.yaml
In upgrade kyma queues the `ERSContext` values updated after provisioning were being overwritten back to provisioning values. This is a followup to https://github.com/kyma-project/control-plane/pull/1735.
=> Store ERS context on kyma upgrade

tools/cli/go.mod, tools/cli/go.sum
Fixing KCP CLI deps
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-kcp-cli
=> Fix KCP CLI prow jobs

components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
I introduced a flaky unit test in https://github.com/kyma-project/control-plane/pull/1735, disabling it temporarily until I manage to address the flakiness.
=> Disable flaky TestKymaUpgrade_UpgradeAfterMigrationWithNetworkPolicy

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/cmd/broker/upgrade_cluster_test.go, components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go, components/kyma-environment-broker/internal/broker/instance_update.go, components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go, components/kyma-environment-broker/internal/storage/driver/memory/operation.go, resources/kcp/values.yaml
Fixing flaky test, followup to https://github.com/kyma-project/control-plane/pull/1748
=> Reduce flakiness on ERS context unit test

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go, components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go, components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go, resources/kcp/values.yaml
- Remove test which checks upgrade kyma 1 to kyma 2 (not needed, everything is upgraded)
- SC components must not be installed (always disabled in the initialisation step: HB, SC, SC-addons, SM-proxy)
=> SC components must be always disabled

components/kyma-environment-broker/internal/environmentscleanup/service.go, components/kyma-environment-broker/internal/provisioner/client.go, resources/kcp/values.yaml
- environments cleanup job must skip runtimes if not exists in the provisioner
=> Handle not existing runtimes in provisioner by environments cleaner

components/kyma-metrics-collector/pkg/cache/record.go, components/kyma-metrics-collector/pkg/logger/logger.go, components/kyma-metrics-collector/pkg/process/process.go, resources/kcp/values.yaml
Add runtimeID in log to enable better correlation of KMC and KEB logs
https://github.com/kyma-project/control-plane/issues/1640
=> Add runtimeID to log message

components/kyma-metrics-collector/Dockerfile, resources/kcp/values.yaml
=> bump the golang image to golang1.18.3:alpine3.16 in KMC

components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go, components/kyma-environment-broker/internal/process/update/conditions.go, resources/kcp/values.yaml
- remove conditions for running steps which determine Kyma version
=> Remove unnecessary Kyma versions conditions

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/common/orchestration/ext.go, components/kyma-environment-broker/common/orchestration/strategies/parallel.go, components/kyma-environment-broker/internal/orchestration/manager/manager.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
- add speed factor to affect orchestration processing queues for tests
=> Speed up orchestration for tests

docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
=> Btp operator creds in docs

components/kyma-environment-broker/internal/runtime/converter.go, components/kyma-environment-broker/internal/runtime/converter_test.go, components/kyma-environment-broker/internal/runtime/handler.go, resources/kcp/values.yaml
- computing runtimes endpoint Satus.State value
=> Return state suspended for all suspended runtimes

components/kyma-metrics-collector/go.mod, components/kyma-metrics-collector/go.sum, resources/kcp/values.yaml
=> Bump dependencies in kmc

tools/reconciler/e2e-test/template-kyma-main.json
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/5616
=> Remove deprecated components from reconciler e2e test for kyma main

resources/kcp/values.yaml
- enable feature flag for reconciler debug logging
=> enable feature flag for reconciler debug logging

resources/kcp/values-reconciler-image.yaml, resources/kcp/values.yaml, tools/reconciler/Makefile
Resolve the problem keb version bump triggers renconciler e2e prow job
=> extract reconciler image values to different value file

resources/kcp/values-reconciler-image.yaml, resources/kcp/values.yaml, tools/reconciler/Makefile
=> bring back mothership reconciler image in default value file

resources/kcp/values.yaml
- Updated Cloudsql Image Version.
=> Updated Cloudsql Version

components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/provider/azure_provider.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Enable logging region which comes to KEB as param

resources/kcp/values.yaml
- Revert to old image version.
=> Old Image Revert

resources/kcp/charts/kyma-environment-broker/values.yaml
=> Update value of kyma_environments_subaccount_cleanup_job

components/schema-migrator/Dockerfile, resources/kcp/values.yaml
=> Change golang version

components/kyma-environment-broker/internal/metrics/instances_collector.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/storage/dbmodel/operation.go, components/kyma-environment-broker/internal/storage/driver/memory/instance.go, components/kyma-environment-broker/internal/storage/driver/postsql/instance.go, components/kyma-environment-broker/internal/storage/ext.go, components/kyma-environment-broker/internal/storage/postsql/factory.go, components/kyma-environment-broker/internal/storage/postsql/read.go, resources/kcp/charts/kyma-environment-broker/values.yaml
`compass_keb_ers_context_license_type_total` will offer aggregated metric counting all instances grouped by license_type from ERSContext last operation
=> Introduce license_type aggregated metric

resources/kcp/charts/kyma-environment-broker/values.yaml
=> Update value of kyma_environments_cleanup_job

components/kyma-environment-broker/internal/provisioner/graphqlizer.go, components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
EnableNatGateway -> enableNatGateway
=> keb: adjust name in graphQL payload

components/kyma-environment-broker/internal/storage/tests_utils.go
- Corrected swallowed error.
- Fixed invalid container removal
=> Corrected Hidden Error & Invalid Rm Command

components/kyma-environment-broker/internal/appinfo/runtime_info_test.go, components/kyma-environment-broker/internal/fixture/fixture.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go, components/kyma-environment-broker/internal/process/provisioning/internal_eval_updater_test.go, components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go, components/kyma-environment-broker/internal/process/update/check_step_test.go, components/kyma-environment-broker/internal/process/upgrade_cluster/manager_test.go, components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides_test.go, components/kyma-environment-broker/internal/runtime/converter_test.go, components/kyma-environment-broker/internal/runtime/handler_test.go, components/kyma-environment-broker/internal/storage/driver/postsql/operation.go, components/kyma-environment-broker/internal/suspension/handler_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- all type of operation specific data bounded together in the Operation. This is one of a step, which allows a refactoring and get rid of specific types of operations.
- methods like toProvisioningOperation in the storage was modified to unmarshall data after calling toOperation.
=> All necessary fields moved from XXXOperation to Operation type

components/kyma-environment-broker/Dockerfile.cleanup, resources/kcp/charts/kyma-environment-broker/values.yaml
- Change from alpine to scratch in image `environments-cleanup-job`
- Update values
=> Change environments-cleanup-job from alpine to scratch

components/kyma-environment-broker/internal/metrics/metrics.go, components/kyma-environment-broker/internal/metrics/operation_duration.go, components/kyma-environment-broker/internal/metrics/operation_result.go, components/kyma-environment-broker/internal/metrics/step_result.go, components/kyma-environment-broker/internal/process/events.go, components/kyma-environment-broker/internal/process/staged_manager.go, components/kyma-environment-broker/internal/process/staged_manager_test.go
- added package with staged manager operating just on Operations - not on ProvisioningOperations
- necessary events added 
- tests adjusted
=> Staged manager uses plain Operations instead of ProvisioningOperations

resources/kcp/charts/mothership-reconciler/values.yaml, resources/kcp/values.yaml
- Remove support for Kyma <2.1 with old istio-configuration component
https://github.com/kyma-incubator/reconciler/issues/1115
=> Remove support for Kyma < 2.1 with old istio-configuration component

components/kyma-environment-broker/internal/storage/driver/postsql/conflict_test.go, components/kyma-environment-broker/internal/storage/driver/postsql/operation.go, components/kyma-environment-broker/internal/storage/driver/postsql/operation_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Tests for new introduced storage methods 
- Tests covering InsertOperation, UpdateOperation, GetOperationByInstanceId, ListOperationsByInstanceId, ListOperationsByOrchestrationId
- Test covering conflict for direct UpdateOperation
=> Unit tests for new storage methods

components/kyma-environment-broker/Dockerfile.tcj, components/kyma-environment-broker/Makefile, components/kyma-environment-broker/cmd/trialcleanup/main.go, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, scripts/generic_make_go.mk
As a base for periodically run trial cleanup job supposed to remove trial clusters after 14 days we created almost empty implementation of a job (just logging two messages) to be run every 15 minutes. 
- main.go with logic
- updated Makefile to create and push image for new job
- cronJob template
=> Trial cleaner job with dummy logic

resources/kcp/values.yaml
- Plain cloud sql proxy image instead of a customised one.
=> Plain Cloud Sql Proxy Image

components/schema-migrator/main.go, resources/kcp/values.yaml
- Ignoring error when there is no migration changes on existing database.
=> Ignoring No Migration Changes Error

components/schema-migrator/main.go, resources/kcp/values.yaml
=> Additional Info Logs

resources/kcp/templates/migrator-job.yaml
=> Fix migrator yaml file

components/kyma-environment-broker/Dockerfile.tcj, components/kyma-environment-broker/cmd/trialcleanup/main.go, components/kyma-environment-broker/internal/storage/dbmodel/instance.go, components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go, components/kyma-environment-broker/internal/storage/postsql/read.go, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- service getting all instances with trial plan and selecting those with createdAt at least 14 days ago
- logging those selected instances
=> Listing trial jobs to expire

resources/kcp/values.yaml
- Image revert missed from previous revert of schema migrator changes
=> Added Not Reverted Image

components/kyma-environment-broker/cmd/trialcleanup/main.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Selecting dry run on environment settings
- Extended configuration structure, log when dry run selected.
- Still only dry run logic implemented
=> Dry run based on env

components/kyma-environment-broker/Dockerfile.tcj, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
Wait, clean trials and kill sql proxy 
- waiting 20 seconds before trying to get to DB
- killing sql proxy after completion of the cleaner job
=> Kill sql proxy in trial cleaner job

components/kyma-environment-broker/Dockerfile.tcj, components/kyma-environment-broker/cmd/trialcleanup/main.go, components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Fixes in code and docker file.
- Proper logic restored for selecting non expired trials
- curl added to image to fully facilitate killing cloud sql proxy
=> Fixes for logic and image in trial cleaner job

CODEOWNERS, OWNERS, resources/kcp/OWNERS
=> Update Framefrog OWNERS

components/provisioner/Dockerfile, resources/kcp/values.yaml
- Bump alpine image in Provisioner
=> Bump alpine image in Provisioner

components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/internal/broker/instance_update.go, components/kyma-environment-broker/internal/broker/instance_update_test.go, components/kyma-environment-broker/internal/dto.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- KEB consumes "expired" param
=> Consume expired

components/kyma-environment-broker/internal/broker/instance_update.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- allow to expire failed instances
- block expiration request if the active=false is not set
- use proper logger
=> Allow to expire failed instsances

components/kyma-environment-broker/internal/broker/instance_update.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Fix update endpoint, error must not be null

components/schema-migrator/go.mod
- Changed schema migrator module declaration path.
=> Changed Schema Migrator Module Declaration Path

components/kyma-environment-broker/cmd/trialcleanup/main.go, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
Configurable expiration period, to be set separately for different environments.
- Usage of time.Duration env with expiration period
- dryRun and expirationPeriod envs in helm template
- small fixes and refactoring
=> Configurable interval for expiration evaluation

resources/kcp/charts/kyma-environment-broker/values.yaml
Invalid expiration period specification caused parsing error
- Setting expiration period using hours as unit instead of days
=> Setting expiration period in hours

tools/reconciler/e2e-test/template-kyma-main.json
- Deploy telemetry component in reconciler-e2e test
Fixes https://github.com/kyma-project/kyma/issues/15090, See also https://github.com/kyma-project/kyma/issues/13143
=> Add telemetry component to reconciler e2e-test template

docs/kyma-environment-broker/03-14-broker-configuration-for-given-version-and-plan.md
- add documentation about ConfigProvider feature added in: 
#1859 
#1881
See #1824
=> KEB config for given Kyma version and plan docs

resources/kcp/values.yaml
followup to https://github.com/kyma-incubator/reconciler/pull/1153
requirement for https://github.com/kyma-project/control-plane/pull/1959
=> Remove sc-migration reconciler

components/kyma-environment-broker/Dockerfile.tcj, components/kyma-environment-broker/cmd/trialcleanup/main.go, components/kyma-environment-broker/internal/broker/client.go, components/kyma-environment-broker/internal/broker/client_test.go, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
Sending regular OSB API Update request from trial cleaner job with context.active = false and expired = false. This update request is supposed to trigger deletion of the trial.
- New method added to broker client - method sending at the moment PATCH request without active and expired fields set - just to check communication between trial cleaner job and KEB
https://github.tools.sap/kyma/backlog/issues/2730 - Task 9
=> Send patch to broker for to be expired instances

resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
- Corrected invalid shell invocation to use scratch image
=> Removed Shell from Env Cleanup Job

components/kyma-environment-broker/internal/broker/broker.go, components/kyma-environment-broker/internal/broker/instance_get.go, components/kyma-environment-broker/internal/broker/instance_get_test.go, components/kyma-environment-broker/internal/broker/response_labels.go, components/kyma-environment-broker/internal/broker/response_labels_test.go, resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- add labels related to a trial expiration to the response of GetInstance endpoint
=> KEB Trial expiration labels

components/kyma-environment-broker/cmd/trialcleanup/main.go, components/kyma-environment-broker/internal/broker/client.go, components/kyma-environment-broker/internal/broker/client_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Sending regular OSB API Update request from trial cleaner job. This update request is supposed to trigger deletion of the trial.
- Method sending at the moment PATCH request with active=false and expired=true  
https://github.tools.sap/kyma/backlog/issues/2730 - Task 9
=> Update request to make trial expire

components/kyma-environment-broker/cmd/accountcleanup/main.go, components/kyma-environment-broker/cmd/environmentscleanup/main.go, components/kyma-environment-broker/cmd/trialcleanup/main.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Added missing closure of connections before sending termination signal.
=> Added Missing Connection Closure

components/kyma-environment-broker/internal/broker/broker.go, components/kyma-environment-broker/internal/broker/instance_get.go, components/kyma-environment-broker/internal/broker/instance_get_test.go, components/kyma-environment-broker/internal/broker/response_labels.go, components/kyma-environment-broker/internal/broker/response_labels_test.go, resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- changes to the code introduced in #1972 with accordance to the established labels
=> Expiration labels fix

resources/kcp/charts/kyma-environment-broker/values.yaml
- set KEB image to the latest version in values.yaml
=> Bump KEB img to the latest ver

components/kyma-environment-broker/internal/broker/instance_get_test.go, components/kyma-environment-broker/internal/broker/response_labels.go, components/kyma-environment-broker/internal/broker/response_labels_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Improvement for: #1979 
- add a separate label with docs about the trial
=> KEB add a label with trial docs

scripts/dependabot_helper.bash
https://github.com/kyma-project/control-plane/pull/1934 provided temporary dependabot automation until https://github.com/kyma-project/control-plane/issues/1929 is properly resolved. Since https://github.com/kyma-project/control-plane/issues/1987, looks like having a commit as part of the PR no longer prevents the author to approve it too so adding approval to the script from https://github.com/kyma-project/control-plane/pull/1934 to reduce on manual steps.
=> Approve dependabot PRs

components/kyma-environment-broker/cmd/trialcleanup/main.go, components/kyma-environment-broker/internal/broker/client.go, components/kyma-environment-broker/internal/broker/client_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Incorrectly calculated number of accepted requests and logs messages hard to analyze due to not preserved chronological order. 
- where appropriate instanceID is logged  
- calculation of accepted, unprocessable based solely on http status code, not existence of operationID
https://github.tools.sap/kyma/backlog/issues/2730
=> Trial cleanup job logging enhanced and summary fixed 

components/kyma-environment-broker/internal/broker/instance_get.go, components/kyma-environment-broker/internal/broker/instance_get_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
For testing purposes we showed trial expiration info only when feature flag was enabled and when particular subaccount id was used.
Information should be shown for all trial plans if feature flag is enabled.
- Condition changed
https://github.tools.sap/kyma/backlog/issues/2730
=> Trial expire info for trial plans only

scripts/dependabot_helper.bash
https://github.com/kyma-project/control-plane/pull/1934 provided temporary dependabot automation until https://github.com/kyma-project/control-plane/issues/1929 is properly resolved and the consensus is reached. Enhancing https://github.com/kyma-project/control-plane/pull/1934 to filter open PRs by author login as well as the title content.
Also multiline string for `gh` doesn't work with `\n` and must be a bash multiline string https://github.com/cli/cli/issues/595
=> Improve dependabot PR filter

docs/kyma-environment-broker/03-15-trial-cleanup-cronjob.md
Trial cleanup job documentation: overview, details, prerequisites and configuration.
- Documentation page
https://github.tools.sap/kyma/backlog/issues/2730
=> Documentation for trial cleaner job

installation/resources/installer-cr.yaml.tpl
- Removing oidc-kubeconfig-service deployment as it will be managed separately by argo-cd
=> removing oidc-kubeconfig-service as it will be managed by argo-cd

CODEOWNERS
- Add jaroslaw-pieszka to codeowners of `control-plane`
=> Add Jaroslaw Pieszka to codeowners

components/kyma-environment-broker/internal/process/deprovisioning/init.go, components/kyma-environment-broker/internal/process/deprovisioning/init_test.go, components/kyma-environment-broker/internal/storage/driver/memory/operation.go
- new initialisation step for deprovisioning process
=> Deprovisioning init step

components/kyma-environment-broker/internal/fixture/fixture.go, components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go, components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step_test.go
Extraction of the release of the hyperscaler subscription as a step to be used by the new staged manager as a part of KEB improvements and refactoring
- Step implementation along with tests
=> Release hyperscaler subscription step

components/kyma-environment-broker/internal/metrics/operation_result.go, components/kyma-environment-broker/internal/metrics/step_result.go, components/kyma-environment-broker/internal/process/staged_manager.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Comparing "provision" with "provisioning"
- to be consistent with changes in step_result.go
https://github.tools.sap/kyma/backlog/issues/2939
=> Restoring missing metrics

components/kyma-environment-broker/internal/metrics/operation_duration.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- correct comparison of operation type for duration metrics
https://github.tools.sap/kyma/backlog/issues/2939
=> correct comparison introduced

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/internal/component_input_helpers.go, resources/kcp/charts/kyma-environment-broker/values.yaml
BTP-Operator will allow configuring `priorityClass` in https://github.com/kyma-incubator/sap-btp-service-operator/pull/23, KEB should set it properly to `kyma-system` for the deployment.
=> Configure btp-operator priorityClass

CODEOWNERS
GitHub indicates that @life0215 (Jack Change) has no longer write access to this repository, so we remove this id from codeowners - @ebensom gave a green light.
- removal from CODEOWNERS
=> Remove obsolete codeowner - life0215

components/kyma-environment-broker/internal/metrics/operations_db_collector.go, resources/kcp/charts/kyma-environment-broker/values.yaml
followup to https://github.com/kyma-project/control-plane/pull/1992
closes: #2030 
=> Enhance KEB compass_keb_operation_result with error_category and error_reason

resources/kcp/values.yaml
- update Provisioner image in values.yaml file
=> Update Provisioner to most recent image

resources/kcp/charts/mothership-reconciler/templates/deployment.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Add possibility to configure reconcile-interval option of mothership reconciler (default 5 minutes)
=> Configurability of reconcile interval

components/kyma-environment-broker/internal/broker/plans_schema.go, components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/openstack-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-additional-params.json, resources/kcp/charts/kyma-environment-broker/values.yaml
- change `Items` field in `Type` struct to `*Type` type so that plans schema meets the requirements of UI form rendering,
- adjust tests
=> Fix plans schema

tools/cli/pkg/credential/manager.go, tools/cli/pkg/ers/command/migrate_all.go, tools/cli/pkg/printer/custom.go
https://github.com/kyma-project/test-infra/pull/6034 bumped go to 1.19 which results in a diff for `go fmt` and `goimports` for CLI tools.
=> Run go fmt with 1.19 fixes

components/kyma-environment-broker/cmd/trialcleanup/main.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Logging messages made more comprehensible
=> Logging improved for trial cleanup job

resources/kcp/values.yaml
=> REvert reconciler to valid image

components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Deprovisioning does not contain global account nor runtime id, so it must be taken from instance
=> Fix Remove runtime step

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step.go, components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Fix check removal step

components/kyma-environment-broker/internal/kubeconfig/handler.go, components/kyma-environment-broker/internal/kubeconfig/handler_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- KEB should not provide kubeconfig for own cluster plan
=> Do not provide kubeconfig for owncluster

components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/broker/instance_create_test.go, components/kyma-environment-broker/internal/broker/response_labels.go, components/kyma-environment-broker/internal/broker/response_labels_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- dashboard url for own cluster instances does not contain kubeconfig id in the list of parameters
=> DAshboard url for own cluster

components/kyma-environment-broker/internal/avs/client.go, components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go, components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Make Avs more verbose, fix remove-runtime

components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step.go, components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go, components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step.go, components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- remove_instance step is able to work if the instance is already deleted
=> Fix remove instance step

components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step.go, components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Skip Runtime removal check if there is no provisioner operation

components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/broker/instance_create_test.go
=> Use provided shootdomain for own cluster

components/kyma-environment-broker/internal/broker/plans.go, components/kyma-environment-broker/internal/broker/plans_schema.go, components/kyma-environment-broker/internal/broker/plans_test.go, components/kyma-environment-broker/internal/broker/testdata/own-cluster-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/own-cluster-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-own-cluster-schema-additional-params.json, resources/kcp/charts/kyma-environment-broker/values.yaml
During review we concluded that there should neither be  `oidc` nor `administrators`
- OIDC and administrators removed from schema
- regex validation for schemaName and schemaDomain added 
=> Schema corrected for own cluster plan

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/internal/broker/instance_get.go, components/kyma-environment-broker/internal/dto.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- do not return kubeconfig and sm credentials in the get instance response
- add omitempty tag to fields of the provisionint parameters
=> Hide some data in the response of get instance endpoint.

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/internal/process/update/conditions.go, components/kyma-environment-broker/internal/process/update/init_kyma_step.go, components/kyma-environment-broker/internal/process/update/initialisation_step.go, components/kyma-environment-broker/internal/process/update/manager.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Aligning update operation with own_cluster plan.
- Upgrade_Shoot only for plans other than `own_cluster`
=> Handle own_cluster plan in update

components/kyma-environment-broker/go.mod, components/kyma-environment-broker/go.sum, components/kyma-environment-broker/internal/process/input/builder.go, components/kyma-environment-broker/internal/process/input/input.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Use regular mutex instead of nsync

tools/cli/pkg/command/orchestration.go
=> Prompt_User_Enchancement

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/process/upgrade_cluster/log_skipping_upgrade.go, components/kyma-environment-broker/internal/process/upgrade_cluster/manager.go, components/kyma-environment-broker/internal/process/upgrade_cluster/manager_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Manager extended to execute steps on condition 
- Skipping cluster update for own cluster plan
- For own cluster update we execute new step - the only action is logging execution
=> Skipping cluster upgrade for own cluster plan

components/kyma-environment-broker/internal/storage/postsql/write.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Error wrapping check for nil errors
=> Fix false nil errors for KEB events

components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step.go, resources/kcp/charts/kyma-environment-broker/values.yaml
We need more logging to investigate issues with database operations
- logging added for errors during database operations
=> More logging for errors added for instance removal step

components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go, components/schema-migrator/migrations/kyma-environment-broker/202210121025_drop_events_references.down.sql, components/schema-migrator/migrations/kyma-environment-broker/202210121025_drop_events_references.up.sql, resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/values.yaml
- removed references from events table. The reference to isntances table makes a problem with an instance deletion. We should be able to see events even if the instance is removed
https://github.tools.sap/kyma/backlog/issues/3050
=> Remove references from evetns table

components/kyma-environment-broker/Dockerfile.keb, components/kyma-environment-broker/Dockerfile.sac, components/kyma-environment-broker/Dockerfile.tcj
=> KEB bump alpine img in Dockerfiles to 3.16.2

resources/kcp/charts/provisioner/templates/gardener-creds-secret.yaml, resources/kcp/charts/provisioner/values.yaml
Description: SRE handles gardener SA credential rotation
=> resourcePolicy keep

components/kyma-environment-broker/README.md, components/kyma-environment-broker/internal/storage/config.go, docs/kyma-environment-broker/03-07-environments-cleanup.md, docs/kyma-environment-broker/03-09-subaccount-cleanup-cronjob.md, docs/kyma-environment-broker/03-15-trial-cleanup-cronjob.md, resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/configure-managed-gcp-postgresql.md, resources/kcp/templates/managed-postgresql-secret.yaml, resources/kcp/values.yaml
- Add possibility to configure db server's ca cert (sslrootcert)  for  kyma-environment-broker, environments-cleanup-job, subaccount-cleanup-job and trial-cleanup-job
- Fix sslMode configuration
=> Add SslRootCert, Fix SslMode for DB

docs/kyma-environment-broker/03-05-authorization.md
The configuration section for environment variables is not clear enough for new developers.
- Add note how to get cluster domain
- Add SCOPE environment variables exporting
=> Change env variables

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/provisioning_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- pivotal cf lib must not log instance details
=> Redact sensitive data from pivotal library logs

components/kyma-environment-broker/internal/storage/postsql/init.go
- Logs db connection failures for kyma-environment-broker
=> Logs db connection failures for kyma-environment-broker

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/internal/broker/instance_update.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go, components/kyma-environment-broker/internal/process/update/automock/runtime_version_configurator_for_updating.go, components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go, components/kyma-environment-broker/internal/process/update/check_step.go, components/kyma-environment-broker/internal/process/update/check_step_test.go, components/kyma-environment-broker/internal/process/update/conditions.go, components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go, components/kyma-environment-broker/internal/process/update/init_kyma_step.go, components/kyma-environment-broker/internal/process/update/initialisation_step.go, components/kyma-environment-broker/internal/process/update/initialisation_step_test.go, components/kyma-environment-broker/internal/process/update/sc_migration_check_step.go, components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go, components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go, components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- use staged manager for update process
Issue: https://github.tools.sap/kyma/backlog/issues/3078
=> Use StagedManager for updating process

resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
=> Swagger for events API in KEB

CODEOWNERS
- Removal of hanngos from codeowners files.
=> Hanngos Codeowners Removal

resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
I missed istio `VirtualService` config in https://github.com/kyma-project/control-plane/pull/2114 which resulted in all requests for events by KCP https://github.com/kyma-project/control-plane/pull/2126 were rejected with 404 by envoy proxy.
=> KEB istio config for events api

components/kyma-environment-broker/Makefile, components/kyma-environment-broker/go.mod, components/schema-migrator/Dockerfile, components/schema-migrator/Makefile, components/schema-migrator/go.mod, resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/values.yaml
https://github.com/kyma-project/test-infra/pull/6173
=> Bump KEB and schema-migrator to go v1.19.2

docs/kyma-environment-broker/03-03-runtime-operations.md
- adjusting the doc after refactoring of the deprovisioning process 
=> Update deprovisioning docs

resources/kcp/values.yaml
- after merging kyma-incubator/reconciler#1205 we need to bump the reconciler image on kcp
=> update reconciler images after kyma-incubator/reconciler#1205

OWNERS, resources/kcp/OWNERS
=> Remove hanngos from OWNERS

docs/kyma-environment-broker/03-01-service-description.md
- Docs amendments for `own_cluster` docs.
=> Added Own_cluster Plan to the Docs

README.md
- Remove the outdated 'Caution' panel.
- Fix the link to the documentation (which is now on GitHub and not on the website).
=> Update KCP README

docs/kyma-environment-broker/03-01-service-description.md, docs/kyma-environment-broker/03-03-runtime-operations.md, docs/kyma-environment-broker/03-11-swagger.md
- Update the info about the trial period in Runtime Operations.
- Fix links to the initialization stages in Runtime Operations.
- Update the info on the swagger.
- Fix typos.
=> Update KEB docs

tools/cli/pkg/printer/table.go
followup to https://github.com/kyma-project/control-plane/pull/2126, deduplicating common events for more compact table display. Following example was artificially created as it's not trivial to hit a situation when similar events get triggered, it usually means that some system is responding slower than usual, but because deduplication happens in KCP, it should not be relevant for the algorithm how the events got created.
Prior to this, the command would display:
```
GLOBALACCOUNT ID                       SUBACCOUNT ID                          SHOOT       REGION      PLAN    CREATED AT            STATE
e449f875-b5b2-4485-b7c0-98725c0571bf   19ea2000-865d-42fd-8d6f-3e3e2dcce3c8   c-36e69c3   eu-west-1   trial   2022/10/19 11:21:28   succeeded
˫operation …
```
=> KCP: deduplicate KEB tracing events

CODEOWNERS
- remove varbanv from codeowners
=> Remove varbanv from CODEOWNERS

CODEOWNERS
**Reason**
I do not contribute in those areas that often anymore as my team is looking into operator based reconciliation
=> Remove kwiatekus from reconciler charts

CODEOWNERS, OWNERS, resources/kcp/OWNERS
- remove @dbadura from codeowners
=> Remove myself from codeowners

CODEOWNERS
- Remove myself from owners in unnecessary file.
=> Remove myself from owners

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/internal/broker/plans.go, components/kyma-environment-broker/internal/metrics/operations_collector.go, components/kyma-environment-broker/internal/process/input/builder.go, components/kyma-environment-broker/internal/process/update/conditions.go, components/kyma-environment-broker/internal/process/upgrade_kyma/conditions.go, components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go, components/kyma-environment-broker/internal/runtime/disabled_components.go
- create Preview plan
- does not bump the image, this PR is needed for next Lifecycle Manager integration tasks
=> Enable Preview plan in KEB

components/kyma-environment-broker/cmd/broker/main.go, resources/kcp/charts/kyma-environment-broker/values.yaml
We need to investigate incident but unblock dev.
=> Secret injection omitted for time of investigation

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/process/provisioning/inject_btp_operator_credentials_step.go, components/kyma-environment-broker/internal/process/provisioning/inject_btp_operator_credentials_step_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Implementation in PR#2156 assumed the namespace is already created. Assumption was wrong.
- Creation of `kyma-system` namespace before secret creation
=> Creating namespace before secret creation - fixing PR#2156

components/kyma-environment-broker/Dockerfile.sac, components/kyma-environment-broker/Dockerfile.tcj, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- Migrated Trial Cleanup Job to use scratch image.
- Migrated Subaccount Cleanup Job to use scratch image.
=> Move Cleanup Jobs to Scratch

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/internal/broker/plans.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Fix preview plan id

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/internal/config/provider_test.go, components/kyma-environment-broker/internal/config/testdata/keb-config.yaml, components/kyma-environment-broker/internal/fixture/fixture.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go, components/kyma-environment-broker/internal/process/provisioning/initialisation.go, components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go, resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- implementation of a step which creates/updates Kyma resource
=> Create Kyma step

resources/kcp/values.yaml
- Update GCE proxy image to v1.33.0-d587c1be
=> Update GCE Proxy image

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/fixture/fixture.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go, components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go, components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step_test.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go, resources/kcp/charts/kyma-environment-broker/values.yaml
As a part of integration of `Lifecycle Manager` with KEB we need a step removing Kyma resource.
- Step removing Kyma resource 
- Step checking if Kyma resource is removed
- modification of Apply Kyma step to record Kyma resource namespace in the instance details
=> Delete Kyma resource step

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
As part of https://github.com/kyma-project/kyma/issues/15443, KEB should create `Secret` for each SKR and populate it with kubeconfig for lifecycle manager.
=> KEB lifecycle manager kubeconfig sync

components/kyma-environment-broker/cmd/broker/main.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Deleting Kyma resource should be executed after AVS, EDP, IAS unregistrations
- Delete Kyma resource (and check if it is deleted) moved after AVS, EDP and IAS unregistration steps
=> Reorder steps in deprovisioning

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/kyma-metrics-collector/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml, resources/kcp/charts/provisioner/values.yaml, resources/kcp/values.yaml
- the docker images should not be defined in the main values.yaml
Reasons:
- less spams from Github where someone creates a PR
=> Move image definitions to subcharts

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/internal/config/provider.go, components/kyma-environment-broker/internal/config/provider_test.go, components/kyma-environment-broker/internal/config/reader.go, components/kyma-environment-broker/internal/config/reader_test.go, components/kyma-environment-broker/internal/config/testdata/keb-config.yaml, components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go, docs/kyma-environment-broker/03-14-broker-configuration-for-given-version-and-plan.md, resources/kcp/charts/kyma-environment-broker/values.yaml
- use the latest official Kyma release version when the config for custom version is missing,
- add test cases.
Resolves #2167
=> KEB config defaults for missing custom Kyma version configs

components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- more logs in apply kyma steps
=> Fix Apply kyma step - more logging

CODEOWNERS
- remove the `/.kyma-project-io/` line because this folder does not exist any more
=> Remove pPrecel, m00g3n and moelsayed from the CODEOWNERS file

components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- adjust time settings for waiting for kyma deletion
=> Adjust timeouts in deletion kyma

components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- add annotation in Kyma CR with domain
=> Apply annotations for kyma CR

CODEOWNERS, OWNERS_ALIASES
- remove Maja from CODEOWNERS and OWNERS_ALIASES
https://github.com/kyma-project/kyma/issues/16151
=> remove Maja from codeowners

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/update_test.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go, components/kyma-environment-broker/internal/process/update/conditions.go, components/kyma-environment-broker/internal/process/update/init_kyma_step.go, components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- fix update process for preview
The implementation of update steps were expecting RuntimeState with reconciler input and a kyma version. The problem is that preview does not creates it.
The problem could be seen here: https://status.build.kyma-project.io/log?container=test&id=1595718914791182336&job=skr-preview-dev
=> Fix Update for preview

tools/cli/pkg/command/runtime.go
During the demo of tracing events for deleted instances, it was recommended to limit on KCP side fetching events for more than 100 instances - https://github.com/kyma-project/control-plane/issues/2256#issuecomment-1321910703
=> KCP skip fetching events for too many instances

docs/kyma-environment-broker/03-01-service-description.md
=> Update KEB service plan documentation

resources/kcp/values.yaml
- Bump schema-migrator image to PR-2249
=> Bump schema-migrator image

resources/kcp/values.yaml
- remove eventing reconciler as eventing now uses the base reconciler
=> remove eventing reconciler

components/kubeconfig-service/pkg/runtime/runtime.go
- add retry for RBAC deletion, including SA, ClusterRole and ClusterRoleBinding
https://github.tools.sap/kyma/backlog/issues/2918
=> enhancement: add retry for RBAC deletion

components/kyma-environment-broker/Dockerfile.scj, resources/kcp/charts/kyma-environment-broker/values.yaml
All of the other KEB images use `golang:1.19.4-alpine3.16` as build image. This also ensures dependabot will know how to keep the image up to date.
=> Bump subscription cleanup job go to 1.19.4

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Fix panic in istio reconciler
- https://github.tools.sap/kyma/backlog/issues/3310
=> Bump reconciler image to panic fix in Istio reconciler

tools/cli/pkg/command/runtime.go, tools/cli/pkg/printer/table.go
- ...
- ...
- ...
Resolves #2297
=> Enchance kcp events

resources/kcp/charts/component-reconcilers/values.yaml
- Component Reconciler updated to include fix in Connectivity Proxy Reconciler ([PR](https://github.com/kyma-incubator/reconciler/pull/1264))
=> Connectivity Proxy Image bump

components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/common/hyperscaler/account_pool.go, components/kyma-environment-broker/common/hyperscaler/account_pool_test.go, components/kyma-environment-broker/common/hyperscaler/account_provider.go, components/kyma-environment-broker/common/hyperscaler/account_provider_test.go, components/kyma-environment-broker/common/hyperscaler/automock/account_provider.go, components/kyma-environment-broker/common/hyperscaler/shared_pool.go, components/kyma-environment-broker/common/hyperscaler/shared_pool_test.go, components/kyma-environment-broker/internal/component_input_helpers.go, components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go, components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step_test.go, components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go, components/kyma-environment-broker/internal/process/provisioning/resolve_creds_test.go, docs/kyma-environment-broker/03-04-hyperscaler-account-pool.md, resources/kcp/charts/kyma-environment-broker/values.yaml
- HAP searches for subscribtions with auAccess: "true" if it is about cf-au11 or cf-ch20
=> Hap eu access

docs/eu_access.md, docs/kyma-environment-broker/02-02-broker-endpoints.md, docs/kyma-environment-broker/03-01-service-description.md
Updated documentation regarding plans and provisioner parameters when EU Access is in play.
- Docs file added and updated
=> EU Access in KEB - documentation update

components/kyma-environment-broker/common/runtime/model.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Making changes in KCP CLI that require some changes in KEB component splitting them into separate PRs. The PR https://github.com/kyma-project/control-plane/pull/2351  uses  changes made in the KEB component but ```pre-main-kcp-cli``` fails because it doesn't catch changes made to the KEB component in the same PR.
- Change variable type to be able to merge https://github.com/kyma-project/control-plane/pull/2351 
=> Change events flag var type

components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go, components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Change retry to fail if overrides not found
Resolves #2378
=> Fail process if overrides not found

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go, components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Fail operations causing an infinite loop if no overrides found
- Add test for provisioning without overrides
See #2378
=> Add tests for version overrides

components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go, resources/kcp/charts/kyma-environment-broker/values.yaml
closes: https://github.com/kyma-project/control-plane/issues/2394
=> Adjust kyma deletion timeout to 30 min

components/kyma-environment-broker/cmd/broker/testdata/kyma-installer-cluster.yaml, components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml, components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml, installation/resources/installer-cr-kyma-dependencies.yaml, installation/resources/installer-cr-kyma-kcp-dependencies.yaml, installation/resources/kyma-components.yaml, tools/reconciler/e2e-test/template-kyma-main.json
Kiali has been removed from Kyma. This PR removes it from the component lists in this repository.
- Remove Kiali from component lists
https://github.com/kyma-project/kyma/issues/16391
=> Remove Kiali from component lists

components/kyma-environment-broker/common/runtime/model.go, components/kyma-environment-broker/internal/process/operation_manager.go, components/kyma-environment-broker/internal/runtime/converter.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Followup to https://github.com/kyma-project/control-plane/pull/2412 which introduced a method for how failed steps are stored in DB, this exposes failed steps to KCP, see also https://github.com/kyma-project/control-plane/issues/2407.
=> KEB to give failed steps information for KCP

components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go, components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go, components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Removal of kubeconfig hash from logging.
=> Remove excessive log messages

resources/kcp/values.yaml
- Bump fluentbit image to latest to resolve security vulnerabilities
FB Image Bump: https://github.com/kyma-project/kyma/pull/16654/files#diff-8251166a8faac008e5d5d2ee4aadb240cc31cce01ed2dfea05955632aacb39ffL23
=> Bump fluentbit to latest image

docs/eu_access.md
For the time being we allow access to the EU Access only regions for whitelisted GlobalAccountIds only.
- Section about whitelisting added, where is whitelist defined, what message is returned in case the GlobalAccountId is not whitelisted
=> EU Access documentation updated with whitelisting details

resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml, resources/kcp/charts/kyma-metrics-collector/values.yaml
Configure PSA for KMC.
- https://github.com/kyma-project/kyma/issues/15919
=> Configure PSA for KMC

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml, resources/kcp/values.yaml
- Revert back eventing reconciler" https://github.com/kyma-project/control-plane/pull/2332
- https://github.com/kyma-project/kyma/issues/15046#issuecomment-1400250053
=> Revert back eventing reconciler

components/kyma-environment-broker/Dockerfile.drj, components/kyma-environment-broker/cmd/deprovisionretrigger/main.go, components/kyma-environment-broker/internal/storage/dbmodel/instance.go, components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go, components/kyma-environment-broker/internal/storage/postsql/read.go, resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
Sometimes during deprovisioning process not all steps are completed, the reasons could be provisional
so attempt to re-execute these steps later could be successful.
- Cronjob definition for job triggering deprovision process for all not completely removed instances.
See also #2408
=> Deprovision retrigger job definition

components/kyma-environment-broker/internal/broker/plans_schema.go, components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema.json, resources/kcp/charts/kyma-environment-broker/values.yaml
KEB catalog changes to support machine-type update.
[catalog.sorted.old.json.txt](https://github.com/kyma-project/control-plane/files/10569796/catalog.sorted.old.json.txt)
[catalog.sorted.new.json.txt](https://github.com/kyma-project/control-plane/files/10569797/catalog.sorted.new.json.txt)
<details>
<summary>catalog diff</summary>
```diff
163a164
>                     "machineType",
186a188,214
>                     "machineType": {
>                       "_enumDisplayName": {
>                         "m5.12xlarge": "m5.12xlarge (48vCPU, 192GB RAM)",
>                         "m5.2xlarge": "m5.2xlarge (8vCPU, 32GB RAM)",
>                         "m5.4xlarge": "m5.4xlarge (16vCPU, 64GB RAM)",
>                         "m5.8xlarge": "m5.8xlarge (32vCPU, 128GB RAM)",
> …
```
=> KEB catalog to allow machine type update

components/kyma-environment-broker/internal/runtime/handler.go, resources/kcp/charts/kyma-environment-broker/values.yaml
After https://github.com/kyma-project/control-plane/pull/2429, `kcp` cli was unable to list runtime that had finished deprovisioning but contained `executedButNotCompleted` steps the same way it was able before.
database:
```
broker=> select instance_id, created_at, deleted_at from instances where instance_id='test-jw270';
instance_id |          created_at           |          deleted_at
-------------+-------------------------------+-------------------------------
test-jw270  | 2023-02-10 08:04:06.112804+00 | 2023-02-10 11:08:18.484797+00
(1 row)
```
`kcp` before this change
```
$ kcp rt -itest-jw270 --only-deleted
GLOBALACCOUNT ID   SUBACCOUNT ID   SHOOT   REGION   PLAN   CREATED AT   STATE   EU ACCESS
$ kcp rt -itest-jw272
GLOBALACCOUNT ID   SUBACCOUNT ID   SHOOT …
```
=> Fix KEB runtime endpoint to list instances with incomplete deprovisioning

resources/kcp/charts/kyma-metrics-collector/values.yaml
Update KMC security context.
- https://github.com/kyma-project/kyma/issues/15919.
=> Update KMC security context

CODEOWNERS, OWNERS, OWNERS_ALIASES
- Add @ukff and @MarekMichali to the OWNERS and CODEOWNERS files
- Remove @tillknuesting from the OWNERS and CODEOWNERS files
=> Update code owners

CODEOWNERS, OWNERS
- Add @jaroslaw-pieszka to the OWNERS and CODEOWNERS file
=> Add a code owner

components/kyma-environment-broker/internal/broker/plans.go, components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/aws-schema-eu.json, components/kyma-environment-broker/internal/broker/testdata/aws-schema.json, components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/azure-schema-eu.json, components/kyma-environment-broker/internal/broker/testdata/azure-schema.json, components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json, components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json, resources/kcp/charts/kyma-environment-broker/values.yaml
- fixes: https://github.com/kyma-project/control-plane/issues/2371#issuecomment-1433043608
=> Production plan with minimum nodes 3

components/kyma-environment-broker/internal/broker/instance_deprovision.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- If deprovision succeeded we allow to create new deprovisioning operation (to clean up or not completed steps)
https://github.com/kyma-project/control-plane/issues/2406
=> Allow re-deprovision after successful deprovision

components/kyma-environment-broker/internal/broker/instance_deprovision.go, docs/kyma-environment-broker/03-16-deprovision-retrigger-cronjob.md, resources/kcp/charts/kyma-environment-broker/values.yaml
If there is not ongoing and not temporary deprovisioning operation but there are no steps to retry/redo, we skip creation of a new operation
- refactored check for ongoing, not temporary operation 
- added check for not ongoing, not temporary but with empty set on not completed steps
- added doc for deprovision retriever
=> Additional check to skip redeprovisioning

tools/cli/pkg/command/upgrade.go
- Modify KCP CLI to deploy with maintenancemode flag set to true by default.
=> Modify KCP CLI to deploy with maintenancemode flag set to true by default.

components/kyma-environment-broker/cmd/broker/update_test.go
followup to https://github.com/kyma-project/control-plane/pull/2447 with simple test for machine type update.
see also: https://github.com/kyma-project/control-plane/issues/2497
=> Adding MachineType update test

components/kyma-environment-broker/internal/fixture/fixture.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go, components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go, components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step_test.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- steps which creates/updates/deletes Kyma resource must not rely on RuntimeID as it was implemented. Runtime ID could be cleaned (in the deprovisioning process)
=> ApllyKyma steps works if RuntimeID is empty

components/kyma-environment-broker/cmd/broker/testdata/managed-runtime-components.yaml, components/kyma-environment-broker/internal/runtime/components_provider_test.go, components/kyma-environment-broker/internal/runtime/testdata/additional-runtime-components.yaml, components/kyma-environment-broker/internal/runtime/testdata/managed-runtime-components.yaml, docs/internal/runtime-upgrade.md, docs/provisioner/08-02-provisioning-gardener.md, installation/resources/installer-cr-compass-dependencies.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, tests/provisioner-tests/test/testkit/compass/director/oauth/client_test.go, tests/provisioner-tests/test/testkit/inputs.go
- compass-runtime-agent is deployed in the `kyma-system` namespace (previously was `compass-system`)
- removing dependencies to `compass-system` namespace in Provisioner and KEB
https://github.com/kyma-project/kyma/issues/15915
=> Remove compass-system dependencies

components/kyma-environment-broker/cmd/accountcleanup/main.go, components/kyma-environment-broker/internal/broker/client.go, components/kyma-environment-broker/internal/broker/instance_deprovision.go, components/kyma-environment-broker/internal/broker/server.go, components/kyma-environment-broker/internal/model.go, components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Alternative proposal to https://github.com/kyma-project/control-plane/pull/2514 on resolving https://github.com/kyma-project/control-plane/issues/2512. Instead of using `force` URL parameter, @PK85 recommended setting the HTTP header identifying the caller of `DELETE` instance endpoint. Using `User-Agent` header for this purpose.
closes: https://github.com/kyma-project/control-plane/issues/2512
=> KEB instance delete capture User-Agent header

components/kyma-environment-broker/common/setup/builder.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Correction of invalid assignment in builder that left cfg unassigned.
=> Assignment Correction

components/kyma-environment-broker/cmd/trialcleanup/main.go, resources/kcp/charts/kyma-environment-broker/values.yaml
Currently we refer to non-existent image.
=> Change image reference for trial cleanup job

components/kyma-environment-broker/cmd/trialcleanup/main.go, resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/values.yaml
Binary images are in /bin directory now.
- Deployments corrected
- fixing regression introduced by https://github.com/kyma-project/control-plane/pull/2477
=> Commands corrected in deployments

components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go, components/kyma-environment-broker/cmd/broker/deprovisioning_test.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/internal/provisioner/fake_client.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Add unit test for successfully redeprovision
- Add unit test for failed redeprovision
See also #2406
=> Add unit tests for redeprovisioning

resources/kcp/charts/kyma-environment-broker/values.yaml
- Added newest cloudsql_proxy_image version property to KEB's charts.
=> Missing Cloudsql Proxy Version

scripts/dependabot_helper.bash
dependabot merge script simplification because KCP `go mod tidy` is no longer necessary after https://github.com/kyma-project/control-plane/pull/2326 merged.
=> Dependabot merge script simplification

resources/kcp/charts/postgresql/templates/init-db-config-map.yaml
Supporting dashes is trivial and removes a hard to debug error
- add `"` to support dashes in db name
=> Add `-` in DB name support to KCP database

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
To avoid that failed the reconciliation due to a duplicated webhook error in Istio need a manual fix, we implemented a cleanup of the duplicated webhook when the error occured. This fix is included in the new reconciler version.
- Update reconciler
- https://github.com/kyma-project/kyma/issues/17054
=> Bump reconciler to include Istio duplicated webhook cleanup

resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
ORY Hydra is deprecated since kyma 2.2. This PR configures KEB endpoints to be accessible with token issued by Hydra client and with IAS app. Changes proposed in this pull request:
- KEB endpoints secured  with IAS app
=> secure KEB endpoints with IAS

CODEOWNERS, OWNERS, resources/kcp/OWNERS
Update OWNERS and CODEOWNERS due to changes in the team.
=> Update gophers owners and codeowners

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
Bump the reconciler image after following changes
https://github.com/kyma-incubator/reconciler/pull/1322
=> bump the reconciler image

components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go, components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- More logging while checking and deleting Kyma (deprovisioning)
- More logging while creating/updating Kyma resource (provisioning)
=> More logs for Kyma resource handling

.github/dependabot.yml
=> Add KCP cli to dependabot

components/kyma-environment-broker/cmd/deprovisionretrigger/main.go, components/kyma-environment-broker/internal/broker/client.go, components/kyma-environment-broker/internal/broker/client_test.go, resources/kcp/charts/kyma-environment-broker/values.yaml
- Checking if GET request for given instanceID returns 404 before deprovisioning again
=> Sanity check for deprovision retrigger redone

resources/kcp/templates/registration-job.yaml
Update registration-job image to image from new registry.
=> Set new image for registration-job

resources/kcp/values.yaml, tests/provisioner-tests/Dockerfile, tests/provisioner-tests/scripts/entrypoint.sh
- bump Go and Alpine version
- remove from Dockefile the unnecessary copying of `lincese` folder
=> Bump Golang and Alpine image versions in provisioner-tests

resources/kcp/values.yaml, tests/provisioner-tests/Dockerfile
=> Generate production images on new Artifact Registry for Provisioner tests

components/kyma-environment-broker/cmd/broker/testdata/kyma-installer-cluster.yaml, components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml, components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml, tools/reconciler/e2e-test/template-kyma-main.json
- Remove tracing component from installation 
- Jaeger is being removed from kyma
https://github.com/kyma-project/kyma/issues/16584
=> remove tracing component

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Update registry for component and mothership reconciler as well as for proxy
- Use latest tag for all
* https://github.com/kyma-project/lifecycle-manager/issues/523
=> Update reconciler images to latest and from new registry

CODEOWNERS
- use @kyma-project/eventing as codeowners for kmc related files
=> use eventing group in codeowners file

components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/common/orchestration/dto.go, components/kyma-environment-broker/common/orchestration/ext.go, components/kyma-environment-broker/internal/orchestration/manager/manager.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go, components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
-  refactored for periodic resolution of runtime targets into runtime operations
- .fix some mismatching data structure between KEB and CNS
=> feature: periodic resolving orchestration runtime

components/kyma-environment-broker/internal/broker/plans_schema.go, components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-additional-params-eu.json, components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/openstack-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json, components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-additional-params.json, docs/kyma-environment-broker/03-12-custom-oidc-configuration.md
- add more details in description for OIDC username prefix and signing algorithms,
- mention that payload presented in the doc is in JSON format.
=> Add more details in descriptions of OIDC schema

components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Fixing logging for Kyma apply step

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/internal/config/provider_test.go, components/kyma-environment-broker/internal/config/testdata/keb-config.yaml, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go, components/kyma-environment-broker/internal/process/steps/kyma_template_test.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
- Kyma resource version changed to v1beta2
- ...
- ...
=> Fixed resource version

resources/kcp/charts/provisioner/values.yaml
- switches provisioner image to a prod one
- ...
- ...
https://github.com/kyma-project/control-plane/pull/2718
=> switches provisioner image to a prod one

components/kyma-environment-broker/internal/environmentscleanup/service.go, components/kyma-environment-broker/internal/storage/postsql/init.go
- extend db connection retry interval,
- fix logs.
=> Fix Kyma Environments Cleanup Job database connection

resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- bump KEB related images to the latest ver. v20230509-34c5d99a.
=> Bump KEB related images to the latest ver. (v20230509-34c5d99a)

components/provisioner/cmd/main.go, resources/kcp/charts/provisioner/templates/deployment.yaml
- fixes template for the provioner image url
- ...
- ...
https://github.com/kyma-project/control-plane/pull/2737
=> fixes template for the provioner image url

components/kyma-environment-broker/internal/process/input/input.go, components/kyma-environment-broker/internal/process/input/input_test.go
- Do not trim any characters from the user provided issuerURL
Reverts https://github.com/kyma-project/control-plane/pull/1473
=> Revert issuerURL normalisation

resources/kcp/charts/kyma-environment-broker/values.yaml
- bump KEB image to rollout #2736 
#2736
=> Revert issuerURL normalisation - KEB image bump

resources/kcp/charts/provisioner/templates/deployment.yaml
- switches slash sign in provisioner template to unencoded version
- ...
- ...
- https://github.com/kyma-project/control-plane/pull/2739
=> switches slash sign in provisioner template to unencoded version

components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
=> Get kyma resource version from template

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Bump KEB related images to the latest ver (v20230512-1e4cab22).
=> Bump KEB related images to the latest ver (v20230512-1e4cab22)

components/kyma-environment-broker/internal/broker/client.go
- allows to provide do direct call to KEB from jobs without authorization
=> KEB jobs without authorization requirements

resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- jobs executes requests to KEB using local k8s service as domain instead of the external URL
=> KEB jobs with local url to KEB

resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
- revert local urls in keb jobs
=> Revert local urls in jobs

tools/reconciler/e2e-test/template-kyma-main.json
This reverts commit 9deca2e6485654787c7e098a63aeabea17f5b36a.
- revert changes introduced in #2756
https://github.com/kyma-project/kyma/issues/17379
=> Revert "restore tracing for reconciler tests (#2756)"

components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go, components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/broker/instance_update.go, components/kyma-environment-broker/internal/broker/instance_update_test.go
- added PlansConfig parameter to **Update** endpoint creation
- Schema update validator created and used for validation
=> Using schema validator to validate update input

resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
- enable istio, which allows local k8s requests without oauth
- configure APP_BROKER_URL as a k8s service name
=> Enable istio for KEB jobs, use direct url to keb

resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
- allow local connections to KEB
=> Enable local connections in istio auth policy

components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go, components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- Always call initialization 
- Do not call checkStatus if provisioningID is empty
https://github.tools.sap/kyma/backlog/issues/3932
=> Get rid of panic in get kubeconfig step for upgrade

resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- terminate istio sidecar after job completion
=> Stop istio after jobs completion

resources/kcp/charts/kyma-environment-broker/values.yaml
- bump KEB jobs - terminate istio at the end of a job
=> Bump KEB jobs

components/kyma-environment-broker/cmd/subscriptioncleanup/main.go
- halts istio in subscription cleanup job
=> Subscriptioncleanupjob haltistio

resources/kcp/charts/kyma-environment-broker/values.yaml
- Bump subaccount cleanup job - halt istio sidecar at the end
=> Bump subbaccount cleanup job - halt istio at the end

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
After changes from https://github.com/kyma-incubator/reconciler/pull/1347
=> Update reconciler images versions

resources/kcp/values.yaml
Bump to include https://github.com/kyma-project/control-plane/pull/2794 changes
=> Bump subscription cleanup job

resources/kcp/charts/kyma-environment-broker/values.yaml
Bump KEB to include changes from #2795 
=> Bump KEB image after PR-2795

resources/kcp/charts/mothership-reconciler/values.yaml
- added config to remove telemetry module from reconcilation when enabled for lifecycle-manager
- ...
- ...
=> added telemetry module exclusion from reconcilation

resources/kcp/charts/kyma-environment-broker/values.yaml
- Updated image version after PR-2818.
=> Update values.yaml for PR-2818

resources/kcp/charts/mothership-reconciler/values.yaml
- Stop reconciling serverless component if serverless CRD is detected
https://github.com/kyma-project/kyma/issues/16941
=> Add serverless to reconciler's exclusion list

resources/kcp/charts/kyma-environment-broker/values.yaml
- Include https://github.com/kyma-project/control-plane/pull/2822
=> Bump KEB to the latest version

components/provisioner/go.mod, components/provisioner/go.sum, components/provisioner/internal/api/resolver_integration_test.go, components/provisioner/internal/api/resolver_integration_with_gardener_test.go, components/provisioner/internal/api/testdata/config.json, components/provisioner/internal/gardener/auditlogging.go, components/provisioner/internal/gardener/auditlogging_test.go, components/provisioner/internal/gardener/shoot_reconciler.go, components/provisioner/internal/gardener/testdata/config.json
=> Audit log extension

resources/kcp/charts/provisioner/values.yaml, resources/kcp/values.yaml
=> Bump provisioner image

resources/kcp/charts/provisioner/templates/deployment.yaml, resources/kcp/charts/provisioner/values.yaml
=> Make the audit config change less invasive

resources/kcp/charts/provisioner/templates/deployment.yaml
One "if" was forgotten in PR #2837
=> Fix provisioner chart

components/kyma-environment-broker/internal/process/staged_manager.go, components/kyma-environment-broker/internal/process/staged_manager_test.go, components/kyma-environment-broker/internal/process/upgrade_cluster/manager.go, components/kyma-environment-broker/internal/process/upgrade_cluster/manager_test.go, components/kyma-environment-broker/internal/process/upgrade_kyma/manager.go, components/kyma-environment-broker/internal/process/upgrade_kyma/manager_test.go
- `RunStep` in staged_manager handles panic
- `RunStep` in upgrade_cluster/manager handles panic
- `RunStep` in upgrade_kyma/manager handles panic
=> Failing operation when panic occurs in the step

resources/kcp/charts/kyma-environment-broker/values.yaml
- bump KEB to the newest version
=> Bump KEB to the newest version

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
After changes from https://github.com/kyma-incubator/reconciler/pull/1355
=> Update reconciler images after changes for connectivity proxy version 2.9.2

resources/kcp/values.yaml
- Image bump for PR: https://github.com/kyma-project/control-plane/pull/2796
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-metrics-collector-build/1668594322993319936
- https://github.com/kyma-project/control-plane/issues/2711
=> Bumped KMC image

components/kyma-environment-broker/Dockerfile.job, components/kyma-environment-broker/Dockerfile.keb, components/kyma-environment-broker/Dockerfile.runtimereconciler, tests/e2e/provisioning/Dockerfile
- Golang builder version update to 1.20.5-alpine3.18.
=> Goland Update

resources/kcp/values.yaml
- Fixed KMC image name from `europe-docker.pkg.dev/kyma-project/prod/control-plane/prodkyma-metrics-collector:v20230613-34a5f5cf` to `europe-docker.pkg.dev/kyma-project/prod/control-plane/kyma-metrics-collector:v20230613-34a5f5cf`.
=> Fixed KMC image name

components/provisioner/internal/api/testdata/config.json, components/provisioner/internal/gardener/auditlogging.go, components/provisioner/internal/gardener/auditlogging_test.go, resources/kcp/charts/provisioner/values.yaml
- change auditlog config region (was taken from seed, should be taken from shoot spec)
- correct tests
=> Provisioner audit logs: Change region, add logging fields

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- use newest images with fix for nodePort conflicts
=> Fix NodePort conflict with internal docker registry 

components/kyma-environment-broker/internal/provisioner/graphqlizer.go, components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
- add shootNetworkingFilterDisabled field to upgrade shoot graphql payload
=> Add ShootNetworkingFilterDisabled to upgrade shoot body graphql

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- [change](https://github.com/kyma-incubator/reconciler/commit/b23e244ca29985a28c6bf5502898516db3d18fc1)
https://github.com/kyma-incubator/reconciler/pull/1365
=> Bump reconciler to deliver fix for nodeport conflict bug in serverless

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
After changes from https://github.com/kyma-incubator/reconciler/pull/1369
=> Update reconciler images after fixes to connectivity proxy reconciler

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
After changes from https://github.com/kyma-incubator/reconciler/pull/1370
=> Bump reconciler images after latest fixes to connectivity proxy reconciler

resources/kcp/values.yaml
- ...
- ...
- ...
Closing this PR: https://github.com/kyma-project/control-plane/pull/2816
=> Bump fb to latest image to fix CVE

components/kyma-metrics-collector/pkg/process/process.go
- Bug fix for not handled error in KMC
=> Bug fix for not handled error in KMC

resources/kcp/values.yaml
- Image bump for KMC: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-metrics-collector-build/1674380614532337664
- For PR: https://github.com/kyma-project/control-plane/pull/2894
=> Image bump for KMC

resources/kcp/charts/kyma-environment-broker/templates/oauth-client.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
=> Hydra removal

resources/kcp/values.yaml
- fix name for mothership reconciler audit log image
=> fix name for mothership reconciler audit log image

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Upgrade image ( [PR](https://github.com/kyma-incubator/reconciler/pull/1348) with changes )
=> Upgrade mothership reconciler image

components/kyma-environment-broker/cmd/broker/broker_suite_test.go, components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go, components/kyma-environment-broker/cmd/broker/main.go, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go, components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go, components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go, components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step_test.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
- read Group Version Kind from the template from configration for getting Kyma resource
=> Keb kyma resource version independent

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Bump KEB images to the latest versions.
=> Bump KEB images to v20230705-30c430b0

components/kyma-environment-broker/go.mod, components/kyma-environment-broker/go.sum
This PR hopes to fix a security vulnerability.
- bumps KEB's dependency to provisioned to `20230418152422-ee68639cb3ab`
=> bumps KEB's dependency to provisioner

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml, resources/kcp/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Bump cloudsql-proxy image to v1.33.8-afb993b8
=> Bump cloudsql-proxy image to v1.33.8-afb993b8

resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, utils/kyma-environments-cleanup-job/apply.sh, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- fix jobs by removing KEB oauth credentials/token url
=> Fix failing cronjobs

components/kyma-environment-broker/Dockerfile.job, components/kyma-environment-broker/Dockerfile.keb, components/kyma-environment-broker/Dockerfile.runtimereconciler, tests/e2e/provisioning/Dockerfile
=> Golang upgrade

resources/kcp/charts/provisioner/values.yaml
=> bump provisioner version

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
#2927 version
- ...
- ...
- ...
=> Bump KEB images to #2927

resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, resources/kcp/charts/mothership-reconciler/templates/serviceaccount.yaml, resources/kcp/charts/mothership-reconciler/values.yaml, resources/kcp/charts/provisioner/templates/service-account.yaml, resources/kcp/charts/provisioner/values.yaml
Extend Helm charts to expose service account annotations
=> Service account annotation

resources/kcp/charts/mothership-reconciler/values.yaml
- Bump to latest image to include following PR: https://github.com/kyma-project/control-plane/pull/2933/files
=> Bump image of mothership-reconciler

components/kyma-environment-broker/internal/runtime/components_provider.go, components/kyma-environment-broker/internal/runtime/components_provider_fake.go, components/kyma-environment-broker/internal/runtime/components_provider_test.go, components/kyma-environment-broker/internal/runtime/provider_test.go
- change Kyma components URL for release version to github release artifacts,
- adjust tests
=> Change Kyma components URL for release version

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- bump KEB related images to v20230801-b6b0b483.
=> Bump KEB related images to v20230801-b6b0b483

components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
- check Provider field in Instance struct before attempting to release subscription.
See https://github.com/kyma-project/control-plane/issues/2663
=> Check Provider in Instance before attempting to release subscription

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/mothership-reconciler/templates/deployment.yaml, resources/kcp/charts/provisioner/templates/deployment.yaml, resources/kcp/values.yaml
=> Workload Identity

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
=> Fix a typo

resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
- oauth2 endpoint was moved to IAS
=> Remove hydra OAuth2 endpoint from KEB

components/kyma-environment-broker/Dockerfile.job, components/kyma-environment-broker/Dockerfile.keb, components/kyma-environment-broker/Dockerfile.runtimereconciler
- bump golang builder to golang:1.21.0-alpine3.18 in dockerfiles.
=> Bump golang builder to golang:1.21.0-alpine3.18 in dockerfiles

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/mothership-reconciler/templates/deployment.yaml, resources/kcp/charts/provisioner/templates/deployment.yaml
=> Add missing bracket 

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Bump reconciler images to bring [fix](https://github.com/kyma-incubator/reconciler/pull/1381) for PVC reconciliation
Fixes https://github.com/kyma-incubator/reconciler/issues/1379
=> Bump reconciler - PVC interceptor

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- bump KEB related images to v20230811-cdd7db1d
=> Bump KEB images to v20230811-cdd7db1d

resources/kcp/charts/mothership-reconciler/values.yaml
- Istio module will be installed and upkeep with Istio reconciler, the reconciliation should not stop
- https://github.com/kyma-incubator/reconciler/issues/1383
=> Don't stop istio reconciliation on v1alpha2

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Update reconcilers images to latest `v20230816-6b351968`
- https://github.com/kyma-incubator/reconciler/pull/1382
**Related issues**
- https://github.com/kyma-incubator/reconciler/issues/1383
=> Update reconciler to image v20230816-6b351968 - use Istio operator as installation method for Istio

components/kyma-environment-broker/internal/fixture/fixture.go, components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go, components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
- Set `operator.kyma-project.io/internal` to true during provisioning and upgrading Kyma for internal users
See also #3005
=> Add internal label for Kyma resource

components/provisioner/pkg/gqlschema/schema.graphql
- document a follow-up for cids fields storage in provisioner db
- ...
- ...
https://github.com/kyma-project/control-plane/issues/3038
=> document a follow-up for cids fields storage in provisioner db

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- bump KEB related images to the latest available ver. v20230901-053636e6
=> Bump KEB images to the latest ver. v20230901-053636e6

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/cmd/broker/suite_test.go, components/kyma-environment-broker/go.mod, components/kyma-environment-broker/go.sum, components/kyma-environment-broker/internal/broker/broker.go, components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/broker/instance_create_test.go, components/kyma-environment-broker/internal/broker/plans.go, components/kyma-environment-broker/internal/broker/plans_schema.go, components/kyma-environment-broker/internal/dto.go, components/kyma-environment-broker/internal/process/input/input.go, components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go, components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go, components/kyma-environment-broker/internal/provider/aws_provider.go, components/kyma-environment-broker/internal/provider/aws_provider_test.go, components/kyma-environment-broker/internal/provider/azure_provider.go, components/kyma-environment-broker/internal/provider/azure_provider_test.go, components/kyma-environment-broker/internal/provider/gcp_provider.go, components/kyma-environment-broker/internal/provisioner/graphqlizer.go, resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- allow to specify Network IP ranges: worker CIDR (nodes CIDR), Pods CIDR, services CIDR
- default nodes CIDR: 10.250.0.0/22
- ...
=> Networking params

components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/provider/aws_provider.go, components/kyma-environment-broker/internal/provider/aws_provider_test.go
- fix AWS IP ranges zone generation
=> Fix AWS zones

resources/kcp/charts/kyma-environment-broker/values.yaml
=> Bump KEB - fix AWS IP ranges in zones

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/internal/broker/instance_create.go, components/kyma-environment-broker/internal/broker/instance_create_test.go, components/kyma-environment-broker/internal/broker/plans_schema.go, components/kyma-environment-broker/internal/dto.go, components/kyma-environment-broker/internal/networking/cidr.go, components/kyma-environment-broker/internal/process/input/input.go, components/kyma-environment-broker/internal/provider/aws_provider.go, components/kyma-environment-broker/internal/provider/azure_provider.go, components/kyma-environment-broker/internal/provider/gcp_provider.go, components/kyma-environment-broker/internal/provider/openstack_provider.go, docs/kyma-environment-broker/03-01-service-description.md
- only Node CIDR is allowed
- json schema for preview plan only (for testing)
=> Only Node CIDR is allowe, json schemas for ip ranges

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/internal/broker/plans.go
- Networking params in preview plan
- ...
=> Ipranges in preview

components/kyma-environment-broker/cmd/broker/provisioning_test.go, components/kyma-environment-broker/internal/broker/plans_schema.go, components/kyma-environment-broker/internal/broker/plans_test.go
- networking params in all plans
=> IP ranges in all plans JSON schemas

resources/kcp/charts/kyma-environment-broker/values.yaml
=> KEB Version Bump

resources/kcp/charts/kyma-environment-broker/values.yaml
- Updated KEB image to the newest version,
- Changed KEB path to point to new repo's images.
=> Version Bump for New Keb Repo

components/provisioner/README.md
- updates provisioner readme with tips on running tests
- ...
- ...
=> updates provisioner readme with tips on running tests

resources/kcp/charts/kyma-environment-broker/values.yaml
=> Networking params in json schema tests

resources/kcp/charts/provisioner/templates/gardener-creds-secret.yaml, resources/kcp/charts/provisioner/values.yaml
Remove obsolete secrets in gardener-credentials.
=> Conditionally remove helm/argo annotations in gardener-credentials

resources/kcp/charts/provisioner/values.yaml
=> Update provisioner image to latest version from prod repo

resources/kcp/charts/kyma-environment-broker/values.yaml
- Bump KEB images to v20230915-bbc9f156
=> Bump KEB images to v20230915-bbc9f156

resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/templates/migrator-job.yaml
- Enable workload identity for jobs
=> Enable workload identity for jobs

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml, tools/reconciler/e2e-test/template-kyma-main.json
- Update reconciler version to include changes to Ory reconciler required for Ory Hydra migration
**Related PR**
- https://github.com/kyma-incubator/reconciler/pull/1392
=> Bump reconciler for Ory Hydra migration

resources/kcp/templates/migrator-job.yaml
=> remove typo extra j letter

resources/kcp/charts/kyma-environment-broker/templates/refactoring-config.yaml
- Test dummy config map to verify argo pruning mechanics.
=> Test Config Map

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- bump KEB related images to the latest available ver. `v20230929-752f7838`
=> Bump KEB imgs to the latest ver. v20230929-752f7838

resources/kcp/charts/kyma-environment-broker/templates/refactoring-config.yaml
- Removal of test config map simulating migration process for KEB resources.
=> Testing Argo Resource Migration

resources/kcp/charts/kyma-environment-broker/values.yaml
- Bump KEB image to v20231003-7756a730
=> Bump KEB images to v20231003-7756a730

resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/templates/managed-postgresql-secret.yaml, resources/kcp/templates/migrator-job.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Not using cloudsql credentials secret when workload identity is enabled
Follows up on:
https://github.com/kyma-project/control-plane/pull/2956
https://github.com/kyma-project/control-plane/pull/3069
=> workload identity disables cloudsql credential

resources/oidc-kubeconfig-service/templates/virutalservice.yaml
=> Fix typo in kubeconfig virtualservice

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
related: [Kyma runtime AvS compatibility with CE ANS subscription (Outage Mapper)](https://github.tools.sap/kyma/backlog/issues/4251)
=> extend AvS integration with KEB

tools/reconciler/e2e-test/template-kyma-main.json
- Since the monitoring component is removed from Kyma in the [PR](https://github.com/kyma-project/kyma/pull/18265), we should remove the monitoring component from the reconciler e2e test
kyma-project/kyma#18258
=> Remove monitoring component from reconciler e2e test

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
=> Bump images

resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml, resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml, resources/kcp/charts/kyma-environment-broker/templates/dashboard.yaml, resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/gardener-dashboard.yaml, resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/keb-migrations.yaml, resources/kcp/charts/kyma-environment-broker/templates/policy.yaml, resources/kcp/charts/kyma-environment-broker/templates/profiler-pvc.yaml, resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml, resources/kcp/charts/kyma-environment-broker/templates/request-authentication.yaml, resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml, resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml, resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml, resources/kcp/charts/kyma-environment-broker/templates/service.yaml, resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
- Added a temporary annotation for disabling pruning in ArgoCD for the time of migrating to new KEB repository.
=> Disabled Pruning for KEB Resources Migration

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- Fix the error (tab and ”) from the PR https://github.com/kyma-project/control-plane/pull/3112 as in [the jenkins job](https://sapcpxfkyma.jaas-gcp.cloud.sap.corp/job/kyma-management-plane/job/ci/job/argocd%20charts/job/chart%252Fkcp-sap/128/consoleFull), it reported below error:
```
14:58:37  Error: YAML parse error on kcp-sap/charts/kcp/charts/kyma-environment-broker/templates/deployment.yaml: error converting YAML to JSON: yaml: line 265: found a tab character that violates indentation
```
=> Fix typo error

resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
=> Typo Correction

resources/kcp/charts/kyma-environment-broker/values.yaml
=> Fix typo in subaccount cleanup job image tag

resources/kcp/charts/provisioner/values.yaml
=> Bump provisioner image after #3113

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- bump KEB related images to the latest ver. v20231019-e8cdf9dc.
=> Bump KEB images to v20231019-e8cdf9dc

resources/kcp/charts/mothership-reconciler/values.yaml
=> Skip Eventing

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- bump KEB images to the latest available ver. v20231023-ebbc2f78
=> Bump KEB images to v20231023-ebbc2f78

resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
- Bump KEB images to v20231026-da3a18d9.
=> Bump KEB images to v20231026-da3a18d9

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Add a FF for https://github.com/kyma-project/kyma-environment-broker/pull/90/files and bump KEB images
See also #3006
=> Add FF env for mandatory region

tests/e2e/provisioning/pkg/client/broker/broker_client.go
Add missing platform region to e2e tests.
See also #3006
=> Add platform region to e2e tests

resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml, resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
- Missing  prune annotation for KEB migration.
=> Added Missing Prune Annotation

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml, utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Add a flag to only expose new schema on the endpoint without changing accepted schemas by KEB and bump KEB images.
See also #3006
=> Add FF env to expose schema with mandatory region

resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
Missing changes from https://github.com/kyma-project/kyma-environment-broker/pull/137
- ...
- ...
- ...
=> Add missing externalTesterDisabled env to KEB chart

docs/internal/runtime-upgrade.md, tools/reconciler/e2e-test/template-kyma-2-19.json, tools/reconciler/e2e-test/template-kyma-main.json
Application connector moved to be a module and remove the manifests, thus it needs to be removed from the mothership reconciler e2e test.
=> Remove application connector from reconcile request

resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml, resources/kcp/charts/kyma-environment-broker/values.yaml
- add Subaccount Cleanup CronJob rate limiting config
=> Add Subaccount Cleanup CronJob rate limiting config

resources/kcp/charts/kyma-environment-broker/values.yaml
- bump KEB related images to the latest ver. v20231115-a5b94831
=> Bump KEB images to v20231115-a5b94831

resources/kcp/charts/kyma-environment-broker/values.yaml
- Fix maxRequestRetries value for subaccount-cleanup-job template
ref: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables
=> Fix maxRequestRetries value for subaccount-cleanup-job template

resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
- quote values for environment variables in pod spec
=> Fix Subaccount Cleanup CronJob chart template

resources/kcp/charts/provisioner/values.yaml
PR to enable fix in Provisioner made by 
https://github.com/kyma-project/control-plane/pull/3186
Please see the internal issue with number 4750
/area control-plane
=> Update provisioner image to v20231121-fee25d8e prod

resources/kcp/charts/kyma-environment-broker/values.yaml
- bump KEB - add GardenerCluster steps (creating and waiting to be ready)
=> Bump KEB - add Infrastructure Manager integration (provisioning steps)

resources/oidc-kubeconfig-service/values.yaml
Bump kubeconfig service image to v20231128-21b583e5
https://github.tools.sap/kyma/backlog/issues/3116
=> Bump kubeconfig service image to v20231128-21b583e5

resources/kcp/values.yaml
Update values.yaml to remove ory from components.
Ory Hydra cleanup
related to issue:
https://github.tools.sap/kyma/backlog/issues/4361
=> Ory Hydra cleanup

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
After changes from https://github.com/kyma-incubator/reconciler/pull/1403
=> Bump reconciler images after latest fixes to connectivity-proxy-reconciler

resources/kcp/charts/provisioner/values.yaml
PR to enable fix in Provisioner made by
https://github.com/kyma-project/control-plane/pull/3194
**Related issue:**
https://github.com/kyma-project/control-plane/issues/3085
=> Update provisioner image to v20231207-70b43c2b prod

resources/kcp/charts/mothership-reconciler/templates/serviceaccount.yaml, resources/kcp/values.yaml, tools/reconciler/e2e-test/template-kyma-main.json
Adding RBAC rules for allowing access to secrets.
Relates to: https://github.com/kyma-incubator/reconciler/pull/1406
=> Add RBAC for mothership reconciler

tools/reconciler/e2e-test/template-kyma-main.json
- Remove all components from Reconcile request, since they do not exist
- ...
- ...
=> Remove all components from Reconcile request, since they do not exist

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
After changes from https://github.com/kyma-incubator/reconciler/pull/1419
=> Update reconciler image to version v20231213-0a99672a

resources/kcp/values.yaml
- Change KMC image as used in Prod `europe-docker.pkg.dev/kyma-project/prod/control-plane/kyma-metrics-collector:v20230629-a4c63495`
=> Change KMC image as used in Prod

resources/kcp/Chart.yaml
- Update Chart.yaml remove kyma-environment-broker from dependency
=> Update Chart.yaml remove kyma-environment-broker from dependency

resources/kcp/values.yaml
- Bump KMC image to fix security issues, PR: https://github.com/kyma-project/control-plane/pull/3228
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-metrics-collector-build/1737409556155207680
=> Bump KMC image to fix security issues

resources/kcp/charts/provisioner/values.yaml
- remove duplicated entry in provisioner values.yaml
=> remove duplicated entry in provisioner values.yaml

resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
- Added machine types for `sap-converged-cloud` in KMC.
- https://github.com/kyma-project/control-plane/issues/3244
=> Added machine types for sap-converged-cloud in KMC

tests/provisioner-tests/go.mod, tests/provisioner-tests/go.sum
- fixes appdash dependency in provisioner-tests
- ...
- ...
- Affected PR https://github.com/kyma-project/control-plane/pull/3251/
=> fixes appdash dependency in provisioner-tests

resources/kcp/charts/provisioner/values.yaml
- bumps provisioner with https://github.com/kyma-project/control-plane/pull/3261 fix
- ...
- ...
=> bumps provisioner image

resources/kcp/charts/provisioner/templates/subscription-cleanup-job.yaml
- corrected invalid reference to .dir property in subscription-cleanup-job.yaml
=> Corrected Invalid Values Reference

resources/kcp/charts/provisioner/values.yaml
- Includes https://github.com/kyma-project/control-plane/pull/3272 
- ...
- ...
=> bumps provisioner

tests/e2e/provisioning/pkg/client/runtime/runtime_client.go, tests/e2e/provisioning/test/test_suite.go
- use kubeconfig from secret instead of provisioner
=> Use kubeconfig from secret e2etest

components/provisioner/e2e_test/test.sh
- change the URL to Compass DEV in the E2E Provisioner tests
https://github.com/kyma-project/compass-manager/issues/91
=> [Provisioner E2E] The new URL to Compass System on DEV

resources/kcp/charts/kyma-metrics-collector/templates/rolebinding.yaml
- Fix KMC chart
- Removed `namespace` from rolebinding.
=> Fix KMC chart

resources/kcp/values.yaml
- Includes https://github.com/kyma-project/subscription-cleanup-job/pull/15
- ...
- ...
=> bumps subscription cleanup job

resources/oidc-kubeconfig-service/values.yaml
- Bump kubeconfig-service to v20240124-709e778b
=> Bump kubeconfig-service to v20240124-709e778b

resources/kcp/charts/kyma-metrics-collector/values.yaml
- bump KMC image for https://github.com/kyma-project/control-plane/pull/3286
- Prow job: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-metrics-collector-build/1752262441133150208
- https://github.com/kyma-project/control-plane/issues/3179
=> bump KMC image

components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go, components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json, resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
- Added Azure machine types in KMC.
- [Dv5 and Dsv5](https://learn.microsoft.com/en-us/azure/virtual-machines/dv5-dsv5-series#dsv5-series)
=> Added Azure machine types in KMC

resources/kcp/charts/kyma-metrics-collector/values.yaml
- Added comment in KMC helm chart, to avoid bump KMC image in the wrong place.
=> Added comment in KMC helm chart

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml, resources/kcp/values.yaml
- brings volumemount cleanup reconciler for warden - https://github.com/kyma-incubator/reconciler/pull/1448
https://github.com/kyma-incubator/reconciler/issues/1447
https://github.tools.sap/kyma/backlog/issues/4985
=> Warden reconciler to handle invalid certs volumemounts

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
Image update to include bugfix for connectivity-proxy reconciler 
Changes from: https://github.com/kyma-incubator/reconciler/pull/1450 - enhance resource search on the cluster
=> Update reconciler image to version v20240201-9591c364

resources/kcp/charts/provisioner/values.yaml
=> Bump Provisioner image (CCEE regions)

components/kyma-metrics-collector/pkg/process/public_cloud_info.go, components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go, components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json, resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
- Changed machine types to lowercase in KMC
=> Changed machine types to lowercase in KMC

components/provisioner/go.mod, components/provisioner/go.sum, tools/cli/go.mod, tools/cli/go.sum
Related vulnerability https://github.com/opencontainers/runc/security/advisories/GHSA-xr7r-f8xq-vfvv
- bump the opencontainers/runc version
=> Fix vulnerability in runc

CODEOWNERS
- Add Jellyfish for component reconcilers as CodeOwner
=> Add Jellyfish for component reconcilers as CodeOwner

resources/kcp/charts/provisioner/values.yaml
=> Update Provisioner image

resources/kcp/charts/component-reconcilers/values.yaml, resources/kcp/charts/mothership-reconciler/values.yaml
- Fix warden reconciler (https://github.com/kyma-incubator/reconciler/pull/1452)
https://github.com/kyma-incubator/reconciler/issues/1447
=> Fix warden reconciler image bump

resources/kcp/values.yaml
=> chore: Update KMC image

resources/kcp/values.yaml
- Image bump for PRs:
- https://github.com/kyma-project/control-plane/pull/3342
- https://github.com/kyma-project/control-plane/pull/3355
- Prow job: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-metrics-collector-build/1759568683807543296
- https://github.com/kyma-project/control-plane/issues/3306
=> chore: bump KMC image

components/provisioner/internal/api/resolver_integration_test.go, components/provisioner/internal/model/gardener_config.go, components/provisioner/internal/provisioning/input_converter.go, components/provisioner/internal/provisioning/input_converter_test.go, components/provisioner/pkg/gqlschema/models_gen.go, components/provisioner/pkg/gqlschema/schema.graphql, components/provisioner/pkg/gqlschema/schema_gen.go
- Provisioner sets `cloud-profile` OpenStack parameters field with default value
=> [CCEE] Set Cloud Profile as default

components/provisioner/internal/model/gardener_config.go
- set the correct value of cloud-provider in Gardener object [fix]
=> Set correct parameter in Gardener object

components/kyma-metrics-collector/go.mod
- Bump Go version to `1.22.0` in `Kyma-metrics-collector`. 
=> Chore: Bump Go version in mod file

components/kyma-metrics-collector/pkg/edp/metrics.go, components/kyma-metrics-collector/pkg/keb/metrics.go
- changed buckets for histogram metrics in KMC
- https://github.com/kyma-project/control-plane/issues/3306
=> feat: changed buckets for histogram metrics in KMC

components/kyma-metrics-collector/go.mod, components/kyma-metrics-collector/go.sum, components/kyma-metrics-collector/pkg/edp/client.go, components/kyma-metrics-collector/pkg/edp/client_test.go, components/kyma-metrics-collector/pkg/keb/client.go, components/kyma-metrics-collector/pkg/keb/client_test.go
- change retry policy for EDP and KEB in KMC, because the EDP retry was getting stuck in backoff.
- https://github.com/kyma-project/control-plane/issues/3306
=> fix: changed retry policy for EDP and KEB in KMC

resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml, resources/kcp/charts/kyma-metrics-collector/prometheus/alerts_test.yaml
- Added alerts for KMC.
- Manual test results: [link](https://github.com/kyma-project/control-plane/issues/3306#issuecomment-1954227746)
- https://github.com/kyma-project/control-plane/issues/3306
=> feat: added alerts for KMC

resources/kcp/charts/provisioner/values.yaml
https://github.com/kyma-project/control-plane/pull/3386
=> Bump image in Provisioner

components/kyma-metrics-collector/README.md, components/kyma-metrics-collector/dev/deployment.yaml
**Changes proposed in this pull request:**
Gardener dependency has been removed in the following PRs: #3347 and #3353 
This change should also be reflected in the README.
#3312
=> docs: update README with gardener removal

components/schema-migrator/main.go
- Enhance temporary error logs
- Log the start and end of the step
- Log current migration version
- Make logs more consistent
See also #3402
=> Add more logs to schema-migrator

resources/kcp/charts/provisioner/values.yaml
Includes changes from https://github.com/kyma-project/control-plane/pull/3399
=> Update provsioner image to v20240312-b74ff6dd

resources/kcp/charts/provisioner/values.yaml
To include changes from https://github.com/kyma-project/control-plane/pull/3415
=> Update provsioner image to v20240320-dd88e90c

resources/kcp/charts/provisioner/values.yaml
PR to include changes from
https://github.com/kyma-project/control-plane/pull/3411
=> Update provisioner image to version v20240507-ff9c0545 prod

resources/kcp/values.yaml
- `compass-runtime-agent` component skipped.
=> Skip compass-runtime-agent component.

components/provisioner/pkg/gqlschema/models_gen.go, components/provisioner/pkg/gqlschema/schema.graphql, components/provisioner/pkg/gqlschema/schema_gen.go
- Introduction of a new field called `ShootAndSeedSameRegion` - no logic, just an API extension.
https://github.com/kyma-project/kyma/issues/18182
=> ShootAndSeedSameRegion Field

components/schema-migrator/cleaner/halt.go
Sending `sigterm` allows to exit proxy with 0 code (if properly configured).
- sending signal
- logging if process was found and signal sent
=> Sending sigterm to terminate `cloud-sql-proxy`

resources/kcp/charts/provisioner/templates/deployment.yaml, resources/kcp/templates/migrator-job.yaml
- do the same changes as it in https://github.com/kyma-project/kyma-environment-broker/pull/832/files
=> Add --exit-zero-on-sigterm for cloudsql-proxy

resources/kcp/values.yaml
related to latest changes in sqlproxy image to use v2 version.
https://sap-btp.slack.com/archives/CQF0V9075/p1718171574791199?thread_ts=1718100827.409909&cid=CQF0V9075
=> bump schema migrator tag to latest

resources/kcp/charts/provisioner/values.yaml
PR to include changes from
https://github.com/kyma-project/control-plane/pull/3457
=> Update Provisioner image to version v20240703-110e15f7

resources/kcp/charts/provisioner/templates/deployment.yaml, resources/kcp/charts/provisioner/templates/pvc.yaml, resources/kcp/charts/provisioner/values.yaml
- Added reference to Persistent Volume Claim
=> Added Persistent Volume Claim reference

components/provisioner/internal/gardener/provisioner.go
- setting toleration field in Shoot.Spec section for `me-central2` region
#3459
=> feat: Setting tolerations-field in `me-central2` region

resources/kcp/charts/provisioner/values.yaml
- Image bumped to include the feature of [saving GraphQL mutations](https://github.com/kyma-project/control-plane/pull/3460)
https://github.com/kyma-project/infrastructure-manager/issues/185
=> Bump Provisioner's image

.github/workflows/schema-migrator.yaml
- Migrate tests from Prow
- Migrate build from Prow
- https://github.com/kyma-project/test-infra/issues/9490
- https://github.com/kyma-project/test-infra/issues/9492
=> Migrate schema-migrator pipelines

resources/kcp/charts/provisioner/values.yaml, resources/kcp/values.yaml
PR to include changes from:
https://github.com/kyma-project/control-plane/pull/3467
=> Update provisioner image to version v20240903-8152ffd9 prod

.github/workflows/provisioner.yaml
=> Migrate provisioner build

.github/workflows/provisioner.yaml
=> Trigger provisioner build on pipeline change

.github/workflows/provisioner.yaml
=> Fix provisioner build triggers

.github/workflows/provisioner.yaml
=> Fix pointless dependency in provisioner workflow

components/provisioner/cmd/main.go
- tiny log change to test new build pipelines
- ...
- ...
=> tiny log change to test new build pipelines

resources/kcp/values.yaml
=> Bump `subscription_cleanup_job` image

CODEOWNERS, OWNERS
Gophers don't have any components in the repository. Schema Migrator has been incorporated into Kyma Environment Broker.
See https://github.com/kyma-project/kyma-environment-broker/issues/1185
=> Remove Gophers from CODEOWNERS
