kyma-project/control-plane

- installation/resources/COMPASS_VERSION
Bump compass version to include https://github.com/kyma-incubator/compass/pull/1462 and also to be aligned with current master version.
> Bump compass to master-3a1554f2

- components/kubeconfig-service/cmd/generator/main.go
- components/kubeconfig-service/go.mod
- components/kubeconfig-service/go.sum
- components/kubeconfig-service/pkg/env/env.go
- components/kubeconfig-service/pkg/reload/watch.go
- components/kubeconfig-service/pkg/reload/watch_test.go
The file-watching mechanism we have at the moment re-loads files when only attributes are changing (ctime, mtime, permission bits).
This causes problems in some k8s scenarios where attributes may change frequently, although the data stays the same.
- Bump fsnotify library to the latest version (it's a new fork)
- Improve watching logic to skip only-attribute-changed scenarios
- Improved and extended tests for watch logic
See also: https://github.com/kyma-project/kyma/issues/8868
> kubeconfig-service fsnotify

- components/kyma-environment-broker/internal/broker/broker.go
- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/plans_validator.go
- components/kyma-environment-broker/internal/dto.go
- components/kyma-environment-broker/internal/hyperscaler/azure/env.go
- components/kyma-environment-broker/internal/hyperscaler/azure/env_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/process/provisioning/input/builder.go
- components/kyma-environment-broker/internal/process/provisioning/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- docs/kyma-environment-broker/03-06-runtime-overrides.md
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- Provides new Azure lite plan with smaller machines, less max nodes, default settings for ory, istio and monitoring charts
- Cluster with plan lite is marked in shoot annotation on Gardener
- New id for plan lite is `8cb22518-aa26-44c5-91a0-e669ec9bf443`
> Add Azure lite plan

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- tests/e2e/provisioning/internal/provisioner/components_provider.go
- Allow configuring "master" as the upgrade version to test upgrading to the latest
- Separate the e2e-upgrade-azure SKR configmap from the e2e-azure as the two conflict when run concurrently 
> Fix a few issues with e2e-upgrade test

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
The `volumeMounts` in e2e-upgrade `TestDefinition` is erroneous.
> Fix e2e-upgrade test podspec

- components/kyma-environment-broker/internal/event/pubsub_test.go
- because KEB pubsub is asynchronous, the unit test must have some synchronization.
> Fix undeterministic KEB pubsub test

- docs/provisioner/08-02-provisioning-gardener.md
- docs/provisioner/08-03-runtime-operation-status.md
- docs/provisioner/08-04-runtime-status.md
- docs/provisioner/08-05-deprovisioning.md
- docs/provisioner/08-06-upgrading-shoots.md
- docs/provisioner/provisioning-api.md
A new functionality has been added to the Runtime Provisioner that allows for upgrading Gardener shoot clusters using the Provisioning API. This needs to be documented.
- Add the `upgradeShoot` mutation description to the Provisioning API
- Add a tutorial on how to upgrade a Gardener Shoot cluster
**Related issue**
See kyma-incubator/compass#1422
**Related PR**
See https://github.com/kyma-project/control-plane/pull/28
> Document Runtime Provisioner's upgradeShoot mutation

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/avs/client.go
- components/kyma-environment-broker/internal/avs/client_test.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/avs/external_eval_assistant.go
- components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
- components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations_test.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
- components/kyma-environment-broker/internal/process/provisioning/internal_eval_test.go
- resources/kcp/values.yaml
- AVS step refactoring - moving method responsible for calls to external server from `delegator` to `avs client`
- Adding the possibility of updating the oauth2 initail token
> Fix AVS client authorization process

- docs/provisioner/provisioning-api.md
Recently a new functionality has been added to the Runtime Provisioner that allows for upgrading Gardener shoot clusters using the Provisioning API. Moreover, certain fields now have specific restrictions and/or value requirements. These requirements need to be added to the documentation.
- Update the `upgradeShoot` mutation description in the Provisioning API with required values and restrictions for certain parameters
- Update formatting
**Related issue**
See kyma-incubator/compass#1422
**Related PRs**
See #28, #40
> Update upgradeShoot() mutation description

- installation/resources/installer.yaml
- Increase kyma-installer container memory limit to 2Gi (#1506)
- Also increased LimitRange to 2048Mi
> Increase kcp-installer container memory limit to 2Gi

- resources/kcp/charts/gateway/templates/gateway.yaml
- resources/kcp/charts/gateway/values.yaml
This is needed to be able to host KCP / Kyma virtual services under two virtual host names (until KCP - Compass final split)
> Allow configuring additional domain names for KCP gateway

- components/kyma-environment-broker/cmd/broker/main.go
No monitoring and SLAs are provided for trial SKRs and they shouldn't be included in monthly SLA reports.
Skip internal AVS evaluation creation besides external AVS.
> Disable internal AVS monitoring for Trial Plan

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
- resources/kcp/charts/provisioner/templates/deployment.yaml
- resources/kcp/charts/provisioner/templates/tests/test-provisioner.yaml
- resources/kcp/values.yaml
- resources/oidc-kubeconfig-service/templates/deployment.yaml
- Eliminate compass URLs which hard-code the use of the cluster domain name
- Introduce chart variable for external compass gateway domain name
> Allow configuring external compass URLs

- components/kyma-environment-broker/cmd/broker/orchestration_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/orchestration/dto.go
- components/kyma-environment-broker/internal/orchestration/handlers/converter.go
- components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager_test.go
- components/kyma-environment-broker/internal/orchestration/strategy_instant.go
- components/kyma-environment-broker/internal/orchestration/strategy_instant_test.go
- components/kyma-environment-broker/internal/orchestration/strategy_parallel.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/manager.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/manager_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma_operation_test.go
- components/kyma-environment-broker/internal/provisioner/fake_client.go
- components/kyma-environment-broker/internal/storage/dbsession/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/dbsession/dbmodel/orchestration.go
- components/kyma-environment-broker/internal/storage/dbsession/factory.go
- components/kyma-environment-broker/internal/storage/dbsession/read.go
- components/kyma-environment-broker/internal/storage/dbsession/write.go
- components/kyma-environment-broker/internal/storage/driver/memory/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/orchestration.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- components/kyma-environment-broker/internal/storage/tests_utils.go
- components/schema-migrator/migrations/kyma-environment-broker/202009230900_add_orchestration_id_to_operation.down.sql
- components/schema-migrator/migrations/kyma-environment-broker/202009230900_add_orchestration_id_to_operation.up.sql
- Remove RuntimeOperation is not a separate object, it is a type in operation hierarchy. UpgradeKymaOperation inherits from RuntimeOperation which inherits from Operation.
- RuntimeObject contains OrchestrationID (new column in operations table)
- New operation in the storage which allows to summarize how number of operations per status for given orchestration id
- Orchestration contains Parameters as an object instead of serialized JSON
- Orchestration does not contain RuntimeOperations
Related:
> Refactor KEB orchestration model

- components/kyma-environment-broker/common/storage/storage.go
- components/kyma-environment-broker/internal/storage/dbsession/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/dbsession/read.go
- components/kyma-environment-broker/internal/storage/dbsession/write.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/values.yaml
- Fixed field type
it fails on dev with the following message:
```
"while reading Operation from the storage: Failed to get operation: sql: Scan error on column index 10, name \"orchestration_id\": converting NULL to string is unsupported
```
proposed solution: http://devtidbits.com/2020/08/03/go-sql-error-converting-null-to-string-is-unsupported/ 
> Fix field type

- components/kubeconfig-service/go.mod
- components/kubeconfig-service/pkg/client/client.go
- components/kubeconfig-service/pkg/client/client_test.go
Needed for the SKR CLI kubeconfig command.
- Implement client based in terms of oauth2.TokenSource and http.Client
- Add simple unit test for sanity checking
#238
> Implement kubeconfig-service client

- components/kyma-environment-broker/common/hyperscaler/account_pool.go
- components/kyma-environment-broker/common/hyperscaler/account_pool_test.go
- components/kyma-environment-broker/common/hyperscaler/account_provider.go
- components/kyma-environment-broker/common/hyperscaler/account_provider_test.go
- resources/kcp/values.yaml
- HAP now checks if secret is labeled as internal before marking it as dirty. This is because some secrets (for example dedicated e2e test secret) should not be returned to the pool despite being unused.
> Exclude internal secrets from being cleaned up

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/cmd/cli/credential/manager.go
- components/kyma-environment-broker/cmd/cli/skr/login.go
- components/kyma-environment-broker/cmd/cli/skr/orchestration.go
- components/kyma-environment-broker/cmd/cli/skr/skr.go
Fixes https://github.com/kyma-project/control-plane/issues/214
- Implement `credential.Manager` in terms of [kubelogin](https://github.com/int128/kubelogin/) credentialplugin.GetToken.Do().
- Implement input validation and handler for skr login command which uses `credential.Manager.GetToken()` and `GetTokenByROPC()`
> SKR CLI: login command

- components/kyma-environment-broker/internal/avs/client.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/edp/client.go
- components/kyma-environment-broker/internal/ias/client.go
- components/kyma-environment-broker/internal/lms/client.go
- components/kyma-environment-broker/internal/process/provisioning/lms_cert_step.go
- components/kyma-environment-broker/internal/process/provisioning/lms_tenant_step.go
- resources/kcp/values.yaml
PR changes HTTP clients for external services bahavior. Now steps are repeated if the execution of `Do()` method from HTTP client returns an error.
The provisioning process consists of 13 steps of which 7 of them uses HTTP client
- _provideLmsTenantStep_, _lmsCertStep_,  _InternalEvaluationStep_ - error from client treat as temporary already (all errors, no matter what kind of error), handling of temporary errors has been added, other errors are repeated for a shorter period of time
- _EDPRegistrationStep_
- _IASRegistrationStep_
- _CreateRuntimeStep_ - already support temporary error for network connection
- _InitialisationStep_ - already support temporary error for network connection
[#193](https://github.com/kyma-project/control-plane/issues/193)
> Upgrade HTTP clients - treat connection error as a temporary

- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- resources/kcp/values.yaml
- change failure information for the operation in the `create runtime` step. The current information is misleading.
> Change failure information for the operation in create runtime step

- components/kyma-environment-broker/internal/process/deprovisioning/manager.go
- resources/kcp/values.yaml
Changes introduced in https://github.com/kyma-project/control-plane/pull/256 revealed that we have some broken instances in database, which have no corresponding ProvisioningOperation. This causes the deprovisioning manager to stuck on trying to fetch ProvisioningOperation from database infinitely until timeout. 
Example log with failure:
```
{"level":"info","msg":"Adding \"d3642db7-dc81-467a-803a-a2c3a4ab138e\" item after 3s","operationID":"d3642db7-dc81-467a-803a-a2c3a4ab138e","time":"2020-10-21T12:21:25Z"}
{"deprovisioning":"manager","level":"error","msg":"Cannot fetch ProvisioningOperation from storage: operation does not exist","time":"2020-10-21T12:21:25Z"}
```
- Modifed deprovisioning manager behaviour when there is no …
> Fix deprovisioning manager error loop

- components/kyma-environment-broker/internal/process/deprovisioning/manager.go
- components/kyma-environment-broker/internal/storage/driver/postsql/config.go
- resources/kcp/values.yaml
- Fail DeprovisionOperation when there is no ProvisioningOperation in db for instance
- ...
- ...
> Fix KEB crashing when ProvisioningOperation for instance does not exist

- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- resources/kcp/values.yaml
- initialisation steps must save modified operation to the storage
> KEB saves operation in initialisation step

- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- resources/kcp/values.yaml
- Default shoot purpose applies only if not set by provider specific defaults
- Set evaluation purpose as default for trial plan
> Configure evaluation purpose for trial runtimes

- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- resources/kcp/values.yaml
With kyma upgrade orchestrations it's possible that a runtime gets deprovisioned while the upgrade operation is waiting in the queue for processing. This is even more likely with maintenance window schedule where operations are pending until the next consecutive window. 
When such situation is detected, the upgrade operation should be marked succeeded (skipped) instead of failed.
> Succeed upgrade of deprovisioned instances

- components/kyma-environment-broker/cmd/cli/command/runtime.go
Take the first kyma upgrade operation when determining state on CLI side as the operations are sorted by CreatedAt DESC on KEB side.
> Fix runtimes upgrade state

- components/metris/README.md
- components/metris/internal/gardener/handlers.go
- components/metris/internal/provider/azure/azure.go
- components/metris/internal/provider/azure/clients.go
- components/metris/internal/provider/azure/instance.go
- components/metris/internal/provider/azure/instance_test.go
- components/metris/internal/provider/azure/types.go
- components/metris/internal/provider/azure/utils.go
- components/metris/internal/provider/types.go
- resources/kcp/values.yaml
- add poll duration parameter with 5m default instead of 1m constant value  (408 errors)
- add logic to remove cluster from storage when not found in Azure but never got a Gardener delete event (404 errors)
- add some debug information about request time
- remove unnecessary code
> fix for metris timeout(408) and not found(404) errors

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/broker/instance_deprovision.go
- components/kyma-environment-broker/internal/broker/instance_deprovision_test.go
- components/kyma-environment-broker/internal/broker/instance_last_operation.go
- components/kyma-environment-broker/internal/broker/instance_last_operation_test.go
- resources/kcp/values.yaml
Currently when a deprovision request is sent from CIS to Kyma service broker for an instance which doesn't exist (has been deprovisioned internally), Kyma responds with `200 OK` and empty JSON body. This seems to be valid response ([see the spec.](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-10)) even if client requests async processing with accepts_incomplete=true .
CIS seems to treat `200 OK` same as `202 Accepted` and starts to poll `service_instance/last_operation` API with empty `operation_id` parameter ([which it shouldn’t do](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#parameters)). Kyma returns `500 Internal Server Error`, [which is also not …
> Fix contract between KEB and CIS

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/orchestration_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/cmd/cli/command/orchestration.go
- components/kyma-environment-broker/common/orchestration/dto.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager_test.go
- resources/kcp/values.yaml
Needed to move KCP CLI out from `components/kyma-environment-broker` to `components/cli`
> Make orchestration states external

- components/provisioner/internal/api/resolver_integration_with_gardener_test.go
- components/provisioner/internal/operations/stages/upgrade/upgrade_kyma.go
- resources/kcp/values.yaml
UpgradeKymaStep which is a first step in upgrade doesn't requeue  operation. As a result operation occupies a queue and can starve upgrades waiting in the queue (and they will timeout instantaneously after picking from the queue). 
- Concurrency level for upgrade operation increased
> Fix for upgrade concurrency issue in Provisioner

- components/kyma-environment-broker/README.md
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/avs/client.go
- components/kyma-environment-broker/internal/avs/client_test.go
- components/kyma-environment-broker/internal/avs/config.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
- components/kyma-environment-broker/internal/process/provisioning/internal_eval_test.go
- components/kyma-environment-broker/internal/process/provisioning/internal_eval_updater.go
- components/kyma-environment-broker/internal/process/provisioning/internal_eval_updater_test.go
- components/kyma-environment-broker/internal/provisioner/automock/client.go
- components/kyma-environment-broker/internal/provisioner/client.go
- components/kyma-environment-broker/internal/provisioner/fake_client.go
- components/kyma-environment-broker/internal/provisioner/query.go
- components/kyma-environment-broker/internal/ptr/ptr.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- Added `AddTags` method to AVS client
- Extend `mockAvsServer` with new action
- Added new post-action to `initialisation` step - adding Tags to internal AVS evaluation containing additional information from Provisioner: `gardener_seed_name`, `gardener_shoot_name` and `region` after cluster is provisioned
> Add Tags to internal AVS evaluation

- docs/cli/commands/kcp_orchestrations.md
- tools/cli/pkg/command/orchestration.go
Split the `kcp orchestrations {ID}` command in two modes:
- without the `"operations"` | `"ops"` subcommand, it shall display orchestration summary, without the list of operations
- with the  `"operations"` | `"ops"` subcommand, it shall display the list of operations.
Prepare subcommand for orchestration cancellation (not implemented yet).
> Enhancements to CLI orchestrations command

- CODEOWNERS
Since Barbara Sz. (@bszwarc) left us in September and is no longer an active contributor, she should be removed from CODEOWNERS.  
At the same time, Justyna Sz. (@superojla) joined us in September and has been contributing to Kyma documentation, so it's time to add her to CODEOWNERS. 
- Remove @bszwarc from documentation CODEOWNERS
- Add @superojla to documentation CODEOWNERS
> Update KCP documentation CODEOWNERS

- tools/cli/pkg/command/orchestration.go
The cli states was used as index when accessing operation statistics instead of orchestration states.
> Fix orchestration statistics for in progress operations

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/avs/config.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/avs/eval_assistant.go
- components/kyma-environment-broker/internal/avs/external_eval_assistant.go
- components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
- components/kyma-environment-broker/internal/avs/model.go
- components/kyma-environment-broker/internal/avs/model_configurator.go
- components/kyma-environment-broker/internal/avs/model_test.go
- components/kyma-environment-broker/internal/runtime/disabled_components.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- Introduce new AVS config values for trial group, push tester ID & key, parent (compound) evaluation
- Enable AVS internal step for trial plan.
> Enable internal AVS for trials in separate group

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.sac
- resources/kcp/values.yaml
- Bump alpine to 3.12.3 in KEB images
- Install curl from edge (7.74.0-r0) as 7.69.1-r1 has vulnerabilities detected
> Bump alpine to 3.12.3 in KEB images

- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
- Bump alpine to 3.12.3 in schema migrator image
- Install curl from edge (7.74.0-r0) as 7.69.1-r1  has vulnerabilities detected
> Bump alpine to 3.12.3 in schema migrator image

- components/kyma-environment-broker/internal/process/provisioning/external_eval.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- resources/kcp/values.yaml
Provisioning a SKR with `TrialPlanID` caused setting the `disabled` flag in `externalEvalCreator` to `false` permanently
- Fixed AVS external evaluation creation
> Fix AVS external evaluation creation

- components/kyma-environment-broker/common/gardener/config.go
- resources/kcp/values.yaml
- Make shoot domain gardener parameter optional, because Gardener config is used by two application and only one of them require this parameter.
> Make shoot domain gardener parameter as optional

- components/kyma-environment-broker/internal/avs/client.go
- components/kyma-environment-broker/internal/avs/client_test.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/avs/eval_assistant.go
- resources/kcp/values.yaml
Wrong parent evaluation ID is being used when trying to remove trial evaluation from parent (compound) evaluation.
> Fix AVS trial eval removal during deprovisioning

- components/kyma-environment-broker/common/orchestration/strategies/parallel.go
- components/kyma-environment-broker/internal/orchestration/handlers/converter.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step.go
- components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
- resources/kcp/values.yaml
- Fill orchestration DTO with runtime op attributes, as there are many legacy runtimes which doesn't have shoot and subaccount data properly sert/migrated in KEB DB
- add stack trace to kyma upgrade operation panic
> Fix KEB kyma upgrade errors

- components/kyma-environment-broker/internal/process/input/builder.go
- resources/kcp/values.yaml
The `initUpgradeRuntimeInput()` function returns the original `InputBuilderFactory.fullComponentsList` slice to the operation. Later on at `RuntimeInput.disableComponentsForProvisionRuntime()` the slice backing array is edited in place with the notorious in-place filtering algorithm implemented in `NewGenericComponentDisabler`
> Fix building components list for upgrade

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
- Added check for orchestration state in upgrade initialisation
* we need that because of race condition which may happen between orchestration manager's waiting loop and the parallel strategy executor
> Check orchestration state in upgrade initialisation

- components/kyma-environment-broker/internal/metrics/metrics.go
- components/kyma-environment-broker/internal/metrics/operation_result.go
1. Implement the [task 927](https://github.tools.sap/kyma/backlog/issues/927)
2. Looks like the [definition of domain](https://github.com/pivotal-cf/brokerapi/blob/master/v7/domain/service_broker.go#L63) doesn't include the `pending/canceled/canceling`, hence, added the `const var`  as below for `switch/case`
```
type LastOperationState = domain.LastOperationState
const (
Pending   LastOperationState = "pending"
Canceling LastOperationState = "canceling"
Canceled  LastOperationState = "canceled"
)
```
> add compass_keb_upgrade_result

- components/kyma-environment-broker/internal/process/upgrade_kyma/evaluation_manager.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- resources/kcp/values.yaml
As per Kyma upgrade Manager requirement, zero delay means the operation has finished. 
https://github.com/kyma-project/control-plane/blob/83bd1342cc40ef7b9fb3679f04b88985315fb0e0/components/kyma-environment-broker/internal/process/upgrade_kyma/manager.go#L96-L98
This means pre- and post- logic should always return non-zero delay to avoid data collisions.
> Ensure pre- and post- logic return valid data on Kyma upgrade

- resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
Schemas in KEB Swagger for `/runtimes` endpoint was not up to date - operation was missing `createdAt` and `operationID` fields and currently `upgradingKyma` section of RuntimeStatus is an array (limited to last 2 upgradeKymaOperations)
- Aligned schemas in KEB Swagger
> Align schemas in KEB swagger

- components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
- components/kyma-environment-broker/internal/process/provisioning/internal_eval_test.go
- resources/kcp/values.yaml
- declared the avs apikey overwrite as sensitive to get it stored in a secret on the cluster rather than a configmap
- ...
- ...
> declaring the AVS api key as sensitive data

- components/kyma-environment-broker/common/runtime/model.go
- components/kyma-environment-broker/internal/runtime/converter.go
- resources/kcp/values.yaml
Orchestration ID in runtime's upgradingKyma.data block is duplicated for all operations:
```
"upgradingKyma": {
"data": [
{
"state": "in progress",
"description": "kyma upgrade in progress",
"createdAt": "2021-01-14T09:57:59.070884Z",
"operationID": "71c63c56-54c5-420d-8e9a-d0949982d52e",
"orchestrationID": "1c887a00-42fd-44a4-ae59-0f4118a9251d"
},
{
"state": "in progress",
"description": "Operation created",
"createdAt": "2021-01-13T10:35:36.471386Z",
"operationID": "afd519b4-6947-4ade-a1f7-6d8e23afdcc7",
"orchestrationID": "1c887a00-42fd-44a4-ae59-0f4118a9251d"
}
```
It is caused by the local variable used in the for loop being reused, and pointer to the `source.OrchestrationID` being used.
> Fix converting orchestration ID in upgrade ops

- tools/cli/pkg/command/runtime.go
Deprovisioned and suspended SKRs should not be displayed as succeeded.
> Fix kcp runtimes suspended status

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
After the kyma upgrade to 1.16.0-rc3, e2e-provisionining-azure-cleanup pod fails to be created due to the following error:
```
{"level":"error","ts":1612264845.4608088,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"testsuite-controller","request":"/testsuite-e2e-azure-cleanup","error":"while scheduling next testing pod for suite [testsuite-e2e-azure-cleanup]: while creating testing pod for suite [testsuite-e2e-azure-cleanup] and test definition [name: e2e-provisioning-azure-cleanup, namespace: kcp-system]: Pod \"oct-tp-testsuite-e2e-azure-cleanup-e2e-provisioning-azure-cleanup-0\" is invalid: metadata.labels: Invalid value: \"oct-tp-testsuite-e2e-azure-cleanup-e2e-provisioning-azure-cleanup-0\": must …
```
> Shorten the names of the e2e testing pods

- installation/resources/installer-cr-kyma-kcp-dependencies.yaml
- installation/scripts/generate-installer-artifacts.sh
- Add new `installer-cr-kyma-kcp-dependencies.yaml` only for installation on `mps` where  `xip-patch` component is removed
> Remove xip-patch component from kyma installer for KCP installation

- components/kyma-environment-broker/internal/suspension/handler.go
- components/kyma-environment-broker/internal/suspension/handler_test.go
- resources/kcp/values.yaml
Currently updating context with the same `Active` value as the one in `instance.Parameters.ErsContext.Active` in database results in skipping the update. However, `instance.Parameters.ErsContext.Active` is always updated if there is no error here:
https://github.com/kyma-project/control-plane/blob/b5e8b6e1163a47c6e819895af45bb3204d11df3c/components/kyma-environment-broker/internal/broker/instance_update.go#L69
`Handle()` method does not check, if the deprovisioning operation created underneath succeeded or failed in the process, and afterwards the instance is updated anyways which prevents from retriggering the failed suspension call when user tries updating context again (instance state in DB is `Active: false` and incoming call also contains `Active: false` parameter) …
> Add retriggering runtime suspension

- components/kyma-environment-broker/internal/edp/client_fake.go
- components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration_test.go
- components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
- resources/kcp/values.yaml
EDP fake client has been introduced to replace EDPClient mocks in tests.
- New source file: client_fake.go, which contains fake EDP client implementation
- Mock replaced with fake client in: edp_deregistration_test.go
- Mock replaced with fake client in: edp_registration_test.go
> Implement fake edp client for tests

- components/kyma-environment-broker/internal/broker/broker.go
- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
Currently, the limit for TRIAL SKR is one per global account. To improve the testing process, the flag indicating if KEB should allow more than one trial SKR per global account is introduced in this PR. This should be enabled on `dev` environment only.
- Added a flag to KEB to allow more than one trial SKR per global account ID
> Allow changing trial limit per GA

- resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/charts/provisioner/templates/policy.yaml
#473 introduced a DestionationRule for provisioner to disable mTLS for downstream peers of provisioner. It results in an error for peers within the Istio mesh as provisioner's istio-proxy is configured with STRICT TLS settings (i.e. not allow clients with plain-text HTTP connection). 
To fix this issue while still allowing KEB environments-cleanup job to reach provisioner's GraphQL endpoint, provisioner's istio-proxy ios configured in PERMISSIVE mode which will allow both TLS and plain-text connections from within the cluster.
> Enable PERMISSIVE mTLS for provisioner for all endpoints

- components/kyma-environment-broker/common/orchestration/resolver.go
- components/kyma-environment-broker/common/orchestration/resolver_test.go
- components/kyma-environment-broker/common/runtime/model.go
- resources/kcp/values.yaml
Resolver skips SKRs which were suspended and then unsuspended successfully.
> Make orchestration resolver fully aware to suspension/unsuspension

- docs/provisioner/08-02-provisioning-gardener.md
While provisioning Kyma with Runtime Provisioner, it is now possible to choose a strategy for conflicts resolution if such should occur for Kyma/component overrides. You can choose to merge them, or replace them with the new ones. 
This change introduced a new field in the GraphQL schema, which needs to be documented.
- Add the `conflictStrategy` field with its possible values to the example GraphQL schema in the provisioning tutorials
#504
> Add the conflictStrategy field to the example schema in provisioning tutorials

- docs/cli/commands/kcp_orchestrations.md
- docs/cli/commands/kcp_runtimes.md
- tools/cli/pkg/command/options.go
- tools/cli/pkg/command/orchestration.go
- tools/cli/pkg/command/runtime.go
- tools/cli/pkg/printer/custom.go
- tools/cli/pkg/printer/customcolumn.go
Implement task [`KCP CLI: custom-columns output format`  ](https://github.tools.sap/kyma/backlog/issues/935)
```
$ go run main.go runtimes  -o custom-columns="INSTANCE ID:instanceID,SHOOTNAME:shootName,runtimeID:runtimeID,REGION:region" INSTANCE ID                            SHOOTNAME   runtimeID                              REGION          
8213F8C9-5268-478A-A910-3B61518251C2   c-57e10b5   2538930c-2dff-4e6e-b7ef-370659b33c46   westeurope      
371B2BDA-D094-4E18-A584-C3B050B226BD   df2b91e     b470f00e-9374-4fba-a95e-07a3d8daed40   centralus       
5C429A13-6F93-418C-8528-F4EAF95AD044   ed72781     3efcfbf0-d2fe-4aa1-8617-1e0d4b9cdbae   northeurope     
EDCBAC01-5300-4CE8-8CF8-13A060CE5C5E   ba5dbac     3bab8f22-1084-4844-821f-1c7530b3f661   centralus …
```
> Enable kcp cli -o custom-columns output format

- components/kyma-environment-broker/internal/avs/external_eval_assistant.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- resources/kcp/values.yaml
Reason: AVS external eval is created in provisioning Initialization step as a post-action, and by the time Initialization step gets here, the 20 minutes timeout of AVS task is already reached.
Solution: After the provisioning has succeeded and when post actions are launched first, mark & update the operation description indicating we are at the post-actions step. This will reset the UpdatedAt time, which is also good for `checkRuntimeStatus(`)'s provisioning timeout check:
```
if time.Since(operation.UpdatedAt) > s.provisioningTimeout {
log.Infof("operation has reached the time limit: updated operation time: %s", operation.UpdatedAt)
return s.operationManager.OperationFailed(operation, fmt.Sprintf("operation has reached the time limit: %s", s.provisioningTimeout))
}
```
> Fix retrying the creation of AVS external evaluations

- components/kyma-environment-broker/internal/runtimeoverrides/runtimeoverrides.go
- resources/kcp/values.yaml
When using `PR-123` custom version for Subaccount mapping, there is an error while applying overrides:
```
{"instanceID":"1CD31DBA-57EF-4E4A-9F81-1DD176DA05E7","level":"info","msg":"Retry Operation was triggered with message: error when appending overrides for operation a38d718b-e286-440b-9988-98aa39455072: no global overrides for plan 'azure' and Kyma version 'PR-10674'","operation":"a38d718b-e286-440b-9988-98aa39455072","planID":"4deee563-e5ec-4731-b9b1-53b42d855f0c","provisioning":"manager","step":"Overrides_From_Secrets_And_Config_Step","time":"2021-02-26T02:45:44Z"}
```
- ...
- ...
- ...
> Change overrides labels to lowercase

- components/kyma-environment-broker/internal/avs/client.go
- components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
- resources/kcp/values.yaml
- `RetryOperationWithoutFail` always updates the `UpdatedAt` field, making the deprovision operation timeout not to be reached.
- Removal of duplicated `if response.StatusCode >= http.StatusInternalServerError`... line
> AVS deprovisioning step fails the operation properly

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- resources/kcp/values.yaml
- Bump library `github.com/tidwall/gjson` version from v1.6.3 to v1.6.8 because of vulnerability issue
- Bump `github.com/Peripli/service-manager` and `github.com/Peripli/service-manager-cli` libraries because only these two libraries use mentioned `gjson` library.
> Bump tidwall/gjson library version

- tools/cli/pkg/command/options.go
- tools/cli/pkg/command/root.go
- tools/cli/pkg/credential/manager.go
Fix broken resource owner password credentials support for all commands in KCP CLI. This flow is needed for service accounts used in automation (e.g. pipeline), where interactive browser login is not possible.
> Fix ROPC support in KCP CLI

- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
- bump alpine version from `3.12.3` to `3.13.2`
- bump [migrator tool](https://github.com/golang-migrate/migrate) version from `4.5.0` to `4.14.1`
due to vulnerability issue
> Bump alpine version and migrator tool version for schema-migrator job

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- resources/kcp/values.yaml
- bump KEB `golang.org/x/text` library from `v0.3.3` to `v0.3.5`
- bump KEB `github.com/gogo/protobuf` library from `v1.2.1` to `v1.3.2`
due to vulnerability issue
> Bump KEB go libraries

- components/kyma-environment-broker/internal/cls/client.go
- components/kyma-environment-broker/internal/cls/client_test.go
- components/kyma-environment-broker/internal/cls/overrides_test.go
- components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step_test.go
- components/kyma-environment-broker/internal/process/provisioning/cls_binding_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_audit_log_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_binding_test.go
- Adds CLS Kibana URL to the overrides since SREs rely on it. Basically, it reverts the following commit: https://github.com/kyma-project/control-plane/pull/563/commits/0e36826e3993c43002bdbe7ec6dbf9a530607d1e
See also #563
> Re-add Kibana URL

- components/kyma-environment-broker/common/orchestration/strategies/parallel.go
- components/kyma-environment-broker/internal/avs/delegator_test.go
- components/kyma-environment-broker/internal/avs/external_eval_assistant.go
- components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- resources/kcp/values.yaml
- Fix setting AVS evaluation status when the refreshed, current status is the same as the target status. This has caused problems when restoring the original status, as it was left empty.
- Fix checking input execution ID in `ParallelOrchestrationStrategy.Cancel()`
> Fixes to a few minor upgrade issues

- resources/kcp/charts/kyma-environment-broker/files/gardener-dashboard.json
- resources/kcp/charts/kyma-environment-broker/templates/gardener-dashboard.yaml
Implement the task of [Grafana Dashboard for Gardener Usage Exporter](https://github.tools.sap/kyma/backlog/issues/1281) by adding new dashboard (see [example](https://grafana.cp.dev.kyma.cloud.sap/d/mnpIkYUGk/gardener-metrics-test?orgId=1) )
> add garadener-metrics dashboard

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
- components/kyma-environment-broker/internal/provider/aws_provider.go
- docs/provisioner/08-02-provisioning-gardener.md
Changing from M4 to M5 machines for cost reduction and gaining higher performance.
https://github.tools.sap/kyma/backlog/issues/1201
> Using M5 machine types for AWS

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-skr.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-suspension.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
In Kyma version `>1.21`, Azure Event Hubs are not provisioned anymore and testing this integration in `e2e_provisioning_test` does not work.
- Set `APP_TEST_AZURE_EVENT_HUBS_ENABLED` to `false` for all e2e `TestDefinitions`
> Disable testing Azure Event Hubs in e2e provisioning test

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- Always deprovision Azure Event-Hub during the upgrade pipeline
> Deprovision Azure Event-Hub at upgrade

- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
- resources/kcp/values.yaml
- Add conflict strategy parameter to ProvisionRuntimeInput
- Set global value for conflict strategy parameter as "Replace"
- Add posibility to set conflict strategy parameter per component
> Add conflict strategy parameter to ProvisionRuntimeInput

- resources/kcp/values.yaml
Upgrade KEB version to PR-669 after adding support for AWS M4 + M5 VM machines.
> Bump version of KEB to PR-669

- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
- components/kyma-environment-broker/internal/suspension/handler.go
- components/kyma-environment-broker/internal/suspension/handler_test.go
- resources/kcp/values.yaml
- do not start unsuspension if the instance is being deprovisioned (or the deprovisioning is failed)
- unsuspension starts Pending operation
- the provisioning initialisation process checks if there is ongoing deprovisioning - if not - then changes from pending to inprogress status
> Block unsuspension if the instance is being deprovisioned

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/suspension/handler.go
- resources/kcp/values.yaml
- old instances does not have shootName saved (and shootDomain) and there is a logic which takes it from dashboardURL. Unfortunately, this logic is not executed in every instance details copying. This PR is fixing it
> KEB: Move shootName recovering to an Instance model

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/common/hyperscaler/account_provider.go
- components/kyma-environment-broker/common/hyperscaler/azure/env.go
- components/kyma-environment-broker/common/hyperscaler/azure/env_test.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_schema.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/plans_validator.go
- components/kyma-environment-broker/internal/broker/plans_validator_test.go
- components/kyma-environment-broker/internal/broker/services_test.go
- components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
- components/kyma-environment-broker/internal/dto.go
- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/input/builder_test.go
- components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider_test.go
- components/kyma-environment-broker/internal/provider/common.go
- components/kyma-environment-broker/internal/runtime/disabled_components.go
- resources/kcp/charts/kyma-environment-broker/files/catalog.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
For Multizone PoC we need new High Availability plans with multiple zones - `azure_ha` plan uses 2 zones by default (randomly generated from `[1;3]`) on 4 nodes, machine type `Standard_D4_v3`. A new provisioning parameter `zonesCount` is introduced in `Azure_HA` plan schema to allow the user to choose more than 2 zones.
- Added new plan: `azure-ha` with 2 zones - `planID: f2951649-02ca-43a5-9188-9c07fb612491`
- Added new `zonesCount` provisioning parameter (only visible in schema for `Azure_HA` plan) which controls how many AZ are created for a cluster
https://github.tools.sap/kyma/backlog/issues/1308
> Add Azure HA plan

- components/kyma-environment-broker/internal/provider/aws_provider.go
- Remove AWS us-west-1b availability zone as you can't create VPC subnets in it and it breaks Gardener provisioning
Internal 1467
> Remove AWS us-west-1b Availability Zone

- components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
- components/kyma-environment-broker/cmd/broker/deprovisioning_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/provisioner/fake_client.go
- resources/kcp/values.yaml
Currently deprovisioning steps are tested separately. This PR introduces Kyma runtime deprovisioning test as a whole process, where all steps are queued and called.
- Add e2e test covering DeprovisioningOperation processing in the deprovisioning queue
#619
> Runtime deprovisioning test

- components/kyma-environment-broker/internal/metrics/operations_collector.go
Try to implement the[ [kcp grafana] add planID label for AWS provisioning/deprovisioning metrics in kcp](https://github.tools.sap/kyma/backlog/issues/1475)
> add AWSPlanID for metrics

- components/kyma-environment-broker/internal/avs/model.go
- resources/kcp/values.yaml
The AVS evaluation names have to reflect the correct cloud provider type correctly:
- for Azure it should be AZR
- for AWS it's AWS
Added shoot name to the AVS evaluation description.
> Set cloud provider type in AVS evaluation names correctly

- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/avs/eval_assistant.go
- components/kyma-environment-broker/internal/avs/external_eval_assistant.go
- components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
- resources/kcp/values.yaml
During unsuspension the AVS evaluation for the Kyma runtime is not recreated, as the previous AVS lifecycle data is kept and the code does not check correctly whether it should recreate the evaluation or not.
> Recreate AVS evaluations during unsuspension

- components/provisioner/go.sum
- components/provisioner/internal/installation/installation.go
- components/provisioner/internal/operations/stages/provisioning/install_kyma.go
- components/provisioner/internal/operations/stages/provisioning/install_kyma_test.go
- components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
- resources/kcp/values.yaml
- Fix Installation status checking while provisioning a Runtime
I analyzed many cases that end up with installation timeout. All of them consist of such Provisioner's logs:
`log:time="123" level=error msg="error while processing operation, stage failed: error: failed to start installation: Failed to prepare installation: failed to create configuration secrets: failed to apply somesecret secret: Post \"https://host.com/api/v1/namespaces/kyma-installer/secrets\": unexpected EOF" Component=Executor OperationId=123 OperationType=PROVISION RuntimeId=123 ShootName=qwe Stage=StartingInstallation`
>First attempt of proceeding the `StartingInstallation` step ends with the error. Applying the configuration failed and there is no `action=label` …
> Fix Installation status checking while provisioning a Runtime

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.sac
- resources/kcp/values.yaml
Alpine `3.13.3` has some know security vulnerabilities
- Bumped alpine base image to `alpine:3.13.5` in KEB Subaccount Cleanup Job and E2E provisioning tests
> Bump alpine base image to 3.13.5

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
Fix e2e provisioning test by adding APP_BROKER_URL env to the `e2e-azure` test.
> Fix e2e provisioning test

- components/kyma-environment-broker/internal/metrics/metrics.go
- components/kyma-environment-broker/internal/metrics/operation_result.go
- resources/kcp/values.yaml
- Rename `compass_keb_upgrade_result` metric to `compass_keb_upgrade_kyma_result`  ⚠️Will require adjustment in all uses, e.g. in `PrometheusRules` ⚠️
- Expose upgrade cluster operation states when processed in  `compass_keb_upgrade_cluster_result` metric
> Expose upgrade cluster operation results in metrics

- resources/kcp/values.yaml
New cloudsql-proxy image is built using `alping:3.13.5` which is free from known security vulnerablities
- Bumped cloudsql-proxy image in KEB
> Bump cloudsql-proxy image in KEB

- components/provisioner/go.mod
- components/provisioner/go.sum
- components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
- components/provisioner/internal/operations/stages/provisioning/wait_for_installation_test.go
- components/provisioner/internal/operations/stages/upgrade/upgrade_kyma.go
- components/provisioner/internal/operations/stages/upgrade/upgrade_kyma_test.go
- resources/kcp/values.yaml
- Stop waiting for Kyma installation (step used both during provisioning and upgrade) when unrecoverable error is detected, and fail the operation
- Allow triggering Kyma upgrade when the current installation state is unrecoverable (terminal) error.
> Distinguish recoverable vs. unrecoverable Kyma installation errors

- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/broker/instance_update_test.go
- resources/kcp/values.yaml
- KEB returns 5xx error on instance update method when instance is not found in db. This proposes a simple change to return 404 instead.
https://github.com/orgs/kyma-project/projects/10#card-60954090
> Return NotFound on KEB instance updates when instance is missing

- components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
- resources/kcp/templates/registration-job.yaml
Image `eu.gcr.io/kyma-project/test-infra/alpine-kubectl` is deprecated and removed from the test-infra repo. This PR changes image `eu.gcr.io/kyma-project/test-infra/alpine-kubectl` to `eu.gcr.io/kyma-project/tpi/k8s-tools:20210504-12243229`.
https://github.com/kyma-project/test-infra/issues/3647
> Change alpine-kubectl image to k8s-tools

- resources/kcp/values.yaml
Provisioning payload was changed in #722 - there was `UserID` field added to ERSContext. `broker_client.go` was adjusted to the new flow, but the image itself wasn't bumped which results in e2e pipelines failing with error:
```
"error":"while extracting ers context: UserID parameter cannot be empty"
```
- Bumped `e2e_provisioning_test` image version to `PR-722`
> Bump e2e-provisioning test image

- components/kyma-environment-broker/internal/appinfo/runtime_info.go
- components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/storage/dbmodel/instance.go
- components/kyma-environment-broker/internal/storage/driver/memory/instance.go
- components/kyma-environment-broker/internal/storage/driver/memory/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/values.yaml
/info/runtimes endpoint should distinguish between provisioning & unsuspension operations and deprovisioning & suspension operations.
- modify DTO so it contains a field with operation details (type, creation time, is operation temporary),
- update handler with logic that allows to distinguish operations.
See also #709
> Update /info/runtimes endpoint

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/broker/instance_get.go
- components/kyma-environment-broker/internal/broker/instance_get_test.go
- resources/kcp/values.yaml
- KEB to return 404 error on instance get method when instance is not found in db
- KEB to return 404 error when instance provisioning operation has not finished successfully
Fixes https://github.com/kyma-project/control-plane/issues/751
Followup to https://github.com/kyma-project/control-plane/pull/736
> Return NotFound on KEB instance get when instance is missing

- components/kyma-environment-broker/internal/metrics/operation_result.go
- resources/kcp/values.yaml
Cluster upgrade operation result is wrongly exposed as compass_keb_upgrade_kyma_result metric.
> Fix compass_keb_upgrade_cluster_result metric

- components/kubeconfig-service/pkg/endpoints/endpoint.go
- components/kubeconfig-service/pkg/env/env.go
- components/kubeconfig-service/pkg/transformer/kubeconfig.go
- components/kubeconfig-service/pkg/transformer/transformer.go
- components/kubeconfig-service/pkg/transformer/transformer_test.go
- resources/oidc-kubeconfig-service/templates/deployment.yaml
- resources/oidc-kubeconfig-service/values.yaml
With OIDC authorization code grant + PKCE flow the OIDC client secret is not needed in the generated kubeconfig of the SKR.
> Enable OIDC authcode + PKCE flow in kubeconfig-service

- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/openstack_provider.go
- resources/kcp/values.yaml
- tools/cli/pkg/command/options.go
The autoscaler maxUnavailable is set to 1. With this setting, Gardener starts to drain the only single worker node while the new node is being created, causing several minutes downtime for all workloads.
> Don't allow unavailable nodes during trial cluster upgrades

- components/kyma-environment-broker/internal/avs/model.go
- resources/kcp/values.yaml
In #699 the way AVS eval description was changed to use `CloudProvider` logic which results in panic:
```
{"level":"error","msg":"panic error from process: runtime error: invalid memory address or nil pointer dereference. Stacktrace: goroutine 357 [running]:\nruntime/debug.Stack(0xc000b6fda8, 0x1bedaa0, 0x2df8ba0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/kyma-project/control-plane/components/kyma-environment-broker/internal/process.(*Queue).worker.func1.1.1(0xc0007e4fc0, 0x2127e38, 0xc000054660, 0x1b6c2a0, 0xc000ce8110)\n\t/go/src/github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/process/queue.go:82 +0x8c\npanic(0x1bedaa0, 0x2df8ba0)\n\t/usr/local/go/src/runtime/panic.go:965 …
```
> Hotfix AVS eval creation step in KEB

- resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- tools/cli/pkg/command/login.go
- tools/cli/pkg/command/options.go
- tools/cli/pkg/command/root.go
- tools/cli/pkg/credential/manager.go
- KCP CLI: Support client credential login besides auth code grant + PKCE login (needed)
- KEB: Support multiple OIDC clients on KEB endpoints, don't verify OIDC client as audience in JWT.
> Support client credential login in CLI; Support multiple OIDC clients on KEB endpoints

- components/kyma-environment-broker/internal/edp/client.go
- components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
- components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration_test.go
- components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
- components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
- resources/kcp/values.yaml
EDP step, during the provisioning process, will make one extra call with a service plan name:
Call on:
```
POST /namespaces/{namespace}/dataTenants/{subAccountID}/{environment}/metadata
```
with body:
```
{
"key": "maasConsumerServicePlan",
"value": "standard|free" 
}
```
> Add sending ServicePlan parameter to the EDP step

- docs/provisioner/08-02-provisioning-gardener.md
Since multiple zones were added to the AWS provisioning mutation and the schema's changed, the provisioning 
tutorial must be updated.
- Update the AWS provisioning mutation in the provisioning tutorial
**Related PRs**
#688 
#699
> Update the provisioning tutorial with multiple zones for AWS

- resources/kcp/values.yaml
Bump alpine version in cloudsql proxy image from `3.13.5` to `3.14.0`
> Bump alpine version in cloudsql proxy image

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/kubeconfig/builder.go
- components/kyma-environment-broker/internal/kubeconfig/handler.go
- components/kyma-environment-broker/internal/kubeconfig/handler_test.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
Add CORS headers to the kubeconfig endpoint. Origins can be set by `APP_KUBECONFIG_ALLOW_ORIGINS` environment.
> Add CORS headers to the kubeconfig endpoint

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
- docs/kyma-environment-broker/03-01-service-description.md
- FIxed default value for `AutoScalerMax` for Azure HA plan in KEB docs
- `AutoscalerMax.Maximum` for AWS HA changed to `40`
- Removed unnecessary assignments for Autoscaler values - those have already proper values set in `NewProvisioningProperties()` and there is no need to override those
- Added info about maximum value of `AutoscalerMax` to docs
> Change Azure HA AutoscalerMax parameter in docs

- components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/process/provisioning/external_eval_step.go
- resources/kcp/values.yaml
External evaluation must not be created for freemium clusters. Internal evaluation must be created in the trial AVS group instead of production.
https://github.tools.sap/kyma/backlog/issues/1638
> Move freemium SKRs from production AVS group to trial AVS group

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
M4 machines should be removed as available machine types from BTP cockpit.
JFYI: M4 support was only required because the static env-page dialog of the "Enable Kyma"-button in BTP cockpit was sending a hard-coded m4 machine type to KEB. This dialog is now replaced by a fully dynamically generated HTML-form which is using the exposed JSONSchema from KEB for rendering the form-fields.
Reverting #669
> Remove m4 machine type support

- resources/kcp/values.yaml
- tests/e2e/provisioning/pkg/client/broker/broker_client.go
After changing update process in https://github.com/kyma-project/control-plane/pull/795 the broker client in e2e tests need to send requests with OSB API async parameter. Otherwise, the e2e fails with error:
```
{\"error\":\"AsyncRequired\",\"description\":\"This service plan requires client support for asynchronous service operations.\"}\n" service=broker_client
time="2021-07-15T08:11:15Z" level=warning msg="while executing request: got unexpected status code while calling Kyma Environment Broker: want: 200, got: 422
```
- Added `accept_incomplete=true` parameter to PATCH requests in e2e tests' KEB client
> Add async parameter to patch requests in e2e tests

- resources/kcp/values.yaml
- tests/e2e/provisioning/pkg/client/broker/broker_client.go
Suspension/unsuspension update calls are executed without `?async_required=true` parameter in real scenario. Asynchronous execution of the update is only required when passing `parameters` in update call payload - in case of supsension/unsuspension, we only pass `context` and this has to be synchronous to reflect the real scenario.
- Removed `async_required=true` parameter from URL when calling update (suspension and unsuspension, context update)
- nit: use `InstanceID(), ClusterName()` methods to access `client` non-exported fields
> Remove async execution of suspension context update in e2e test

- components/provisioner/internal/gardener/provisioner.go
- components/provisioner/internal/gardener/provisioner_test.go
- resources/kcp/values.yaml
- ...Randomize maintenance window for non-porduction clusters
- ...Add purpose attribute to provision unit test
- ...Update image version in kcp chart to PR-821
Resolves #1583
> Randomize maintenance window for non-porduction clusters

- components/kyma-environment-broker/internal/metrics/operations_collector.go
…
- consolidate plan_id usage in metrics, propose to use plan_id as metric label instead of using plan_name as part of metric name
> use plan_id as metric label instead of using plan_name in metric name

- installation/cmd/run.sh
from @desislavaa's suggestion,  try to not install compass component when executing the `pre-main-control-plane-integration` case
```
#bash "${ROOT_PATH}"/installation/scripts/run-compass-installer.sh
```
[PR 861](https://github.com/kyma-project/control-plane/pull/861) test case failed at installing compass component see  https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/861/pre-main-control-plane-integration/1418488550613061632
> remove the compass-installer step in /cmd/run.sh

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/servicemanager/config.go
- components/kyma-environment-broker/internal/servicemanager/factory.go
- components/kyma-environment-broker/internal/servicemanager/factory_test.go
- components/kyma-environment-broker/internal/servicemanager/fake.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- allow to use request SM credentials for defined subaccount even if the overrideMode is set to Always
> Use sm creds for configured subaccount

- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
- components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
- resources/kcp/values.yaml
- fix missing administrator list in request for Provisioner bug,
- add more tests regarding input creation for Provisioner.
> Fix UpgradeShootInput to always contain admins list

- CODEOWNERS
Add @ebensom to code owners of KEB and e2e provisioning. The reason is that there are some places of KEB heavily influenced and developed by me (orchestration, upgrade operations, runtime/orchestration query API handlers), and SRE still contributes to these parts actively.
List of contributions by me (88 commits    20,041 ++    7,950 --):
https://github.com/kyma-project/control-plane/commits?author=ebensom
> Add ebensom to code owners of KEB and e2e provisioning tests

- resources/kcp/charts/provisioner/templates/deployment.yaml
- resources/kcp/charts/provisioner/values.yaml
Shoot upgrade timeout in provisioner is currently not configurable. The current hardcoded 30 minutes timeout is not enough in practice.
> Allow configuring shoot upgrade timeout (default 90 mins)

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/kubeconfig/builder.go
- components/kyma-environment-broker/internal/kubeconfig/builder_test.go
- components/kyma-environment-broker/internal/provisioner/query.go
- resources/kcp/values.yaml
- the kubeconfig endpoint fetches alsop oidc params from provisioner and put it to the result
> Fix OIDC param in the returned kubeconfig

- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
Introduce configuration for K8S version and machine image version auto-upgrade Gardener/provisioner parameters in KEB. 
Currently provision applies default values for these parameters, which have changed over time and not provisioner reapplies inconsistent settings from it's DB over the runtimes upon every upgrade orchestration.
> Configurable auto-update (maintenance) settings in KEB

- components/provisioner/README.md
- docs/provisioner/01-01-provisioner-overview.md
- docs/provisioner/05-01-app-entry-parameters.md
- docs/provisioner/08-02-provisioning-gardener.md
- docs/provisioner/08-03-runtime-operation-status.md
- docs/provisioner/08-04-runtime-status.md
- docs/provisioner/08-05-deprovisioning.md
- docs/provisioner/08-06-upgrading-shoots.md
Runtime Provisioner can now provision clusters without installing Kyma. 
Apart from that, it now also includes configuration to leverage Gardener [DNS](https://github.com/gardener/external-dns-management) and [certificate management](https://github.com/gardener/cert-management). 
Because of these changes, its documentation must be updated. 
- Update info on provisioning clusters - state that provisioning with Kyma installation is optional
- Add info about extensions to leverage Gardener DNS and cert management
- Remove the definite article `the` from Runtime Provisioner's name
**Related issues**
#875 
#876
**Related PRs**
#887
#909
> Update Runtime Provisioner's documentation

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
- components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/aws_provider_test.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider_test.go
- resources/kcp/values.yaml
- Azure and AWS HA plans create clusters spanning 3 zones (currently min and max are both fixed to 3)
- Azure and AWS HA plans create one node per zone with 8 vCPU / 32 GiB RAM by default (`autoscalerMin.mininum` = `autoscalerMin.default` = 1)
- AWS HA plan support provisioning clusters with machine types larger than 8 vCPU / 32 GiB RAM 
- HA plans should never create more than 2 surge nodes per zone during cluster maintenance
- Fix AWS supported zones mapping. In https://github.com/kyma-project/control-plane/pull/916 zones for `ca-central-1`, `sa-east-1`, `ap-northeast-2`, `ap-south-1` were removed, assuming we can't support them because they don't support M4 machine types, however our AWS plan only use M5 machines which are …
> Adjust HA plans and AWS supported zones

- components/kyma-environment-broker/internal/metrics/metrics.go
- components/kyma-environment-broker/internal/metrics/operation_duration.go
- components/kyma-environment-broker/internal/process/events.go
- components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
- components/kyma-environment-broker/internal/process/provisioning/staged_manager_test.go
- add ProvisioningSucceeded event
- For provision operation duration, instead of subscribing to every provision step,
it will subscribe to provision ProvisioningSucceeded event(sent from last step of last provision stage which finished without issue)
> collect provision_duration metrics

- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/dto.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
- resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
- resources/kcp/values.yaml
Enhance KEB instance update endpoint to allow users to modify autoscaler parameters
Sample test using port-forwarded deployment:
```
instance=test-jw34
curl -XPATCH "localhost:8080/oauth/v2/service_instances/$instance?accepts_incomplete=true" -i \
-H "X-Broker-API-Version: 2.14" \
-H "Content-Type: application/json" \
--data-binary @- << EOF
{
"service_id":"47c9dcbf-ff30-448e-ab36-d3bad66ba281",
"plan_id":"4deee563-e5ec-4731-b9b1-53b42d855f0c",
"context":{
"globalaccount_id":"***",
"subaccount_id":"***",
"user_id":"jan.wozniak@sap.com"
},
"parameters":{
"name":"$instance",
"autoScalerMin": 10,
"autoScalerMax": 11,
"maxSurge": 12,
"maxUnavailable": 13
}
}
EOF
```
and then connecting to the broker SQL database
```
broker=> select type, finished_stages, …
```
> Update endpoint for autoscaler options for KEB

- components/kyma-environment-broker/internal/monitoring/monitoring.go
- components/kyma-environment-broker/internal/process/deprovisioning/monitoring_uninstall.go
- components/kyma-environment-broker/internal/process/provisioning/monitoring_integration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade.go
- resources/kcp/charts/kyma-environment-broker/templates/monitoring.yaml
- resources/kcp/values.yaml
- Fix non-existent role in monitoring rolebinding
- Allow deploying the monitoring integration config to namespaces other than kcp-system (using ClusterRole & ClusterRoleBinding)
- Treat all helm API calls working with K8S API as KEB temporary error so that queue managers retry
- Only retry monitoring steps up to 10 minutes in 30 seconds intervals
> Fix KEB monitoring integration step issues

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
- components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
This PR fixes a problem with stages in provisioning process. The InputCreator (a field in the opertation) is created in the create_runtime stage. If the stage is finished, it won't be retried. N ext steps will be executed. If any step is taking more than 15 minutes, the engine will put the operation to the queue and start again by loading the operation from the storage (without Inpiut Creator). That's why all steps which plays with the input creator must be in the same stage.
> One KEB stage for provisioning steps

- components/kubeconfig-service/Dockerfile
- bump alpine to eu.gcr.io/kyma-project/external/alpine:3.14.2
Resolves: CVE-2021-3711, CVE-2021-3712
> bump alpine to eu.gcr.io/kyma-project/external/alpine:3.14.2

- resources/oidc-kubeconfig-service/values.yaml
update kubeconfig-service image after alpine bump (#948)
Resolves: CVE-2021-3711, CVE-2021-3712
> update kubeconfig-service image after alpine bump

- components/kyma-environment-broker/internal/broker/instance_update.go
I introduced a bug in https://github.com/kyma-project/control-plane/pull/958 which required users to pass `PlanID` for updating instances. According to [OSB API](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md), it shouldn't be required and we should default to `PlanID` provided during provisioning when the update param doesn't contain `PlanID`.
> Default PlanID from instance details for update when request doesn't specify any

- components/kyma-environment-broker/internal/orchestration/manager/manager.go
- resources/kcp/values.yaml
Fix `orchestration.Manager` crashing due to empty Kyma/Kubernetes parameters.
#866
> Fix nil pointer panic in orchestration manager

- resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
Errors found in swagger yaml:
1. swagger failed to render request bodies, because of wrong indentations in
`ServiceManagerCredentialsBasic, ServiceManagerCredentials, SMPlatformCredentials`  
err msg: `TypeError: Cannot create property 'type' on string '#/components/schemas/ServiceManagerCredentials'`
2. 2x missing `in:` next to `force` parameter
3. error `security.oAuth2ClientCredentials should be array` & `found unexpected ':'` 
```
security:
- oAuth2ClientCredentials: [broker:write] 
```
[link to swagger](https://kyma-env-broker.cp.dev.kyma.cloud.sap/#/Instances/serviceInstance.provision)
- correcting indentations
- adding `in:` next to `force` parameter
- fixing `security.oAuth2ClientCredentials`
> Fixing errors in swagger yaml

- components/kyma-environment-broker/internal/orchestration/runtime_lister.go
- components/kyma-environment-broker/internal/runtime/converter.go
- components/kyma-environment-broker/internal/runtime/handler.go
- resources/kcp/values.yaml
- tools/cli/go.mod
- tools/cli/go.sum
- tools/cli/pkg/command/runtime.go
- [BUGFIX]: KEB: Allow runtime `converter.ApplySuspensionOperations()` to work without initial provision operation (i.e. full list of provision operations). This is needed for runtime handler's `setRuntimeLastOperation()` function to work properly. Adjust all users of `converter.ApplySuspensionOperations()` according to the new contract.
- [BUGFIX]: KEB: populate `AVSInternalEvaluationID` from the last provisioning operation (unsuspension) instead of the first. The current behavior returns obsolete, deleted AVS IDs. 
- [ENHANCEMENT]: CLI: `kcp runtimes` command queries only the last operation now by default. Add `--ops` parameter to query all operations.
- [ENHANCEMENT]: CLI: `kcp runtimes` command table output now displays the state …
> KCP CLI: use KEB runtime state

- resources/kcp/values.yaml
- bump reconciler images to include [custom reconciler for cluster essentials](https://github.com/kyma-incubator/reconciler/pull/354) and [allow the definition of a URL for a component](https://github.com/kyma-incubator/reconciler/pull/335)
- include `cluster-essentials` in templating of custom reconcilers
Fixes https://github.com/kyma-project/kyma/issues/12531
Fixes https://github.com/kyma-incubator/reconciler/issues/285
> Preserve pod-preset certs via custom reconciler

- components/kyma-environment-broker/internal/process/input/input.go
- resources/kcp/values.yaml
During investigation of an OOMKill KEB https://github.com/kyma-project/control-plane/pull/1111/files, we found a memory leak
```
(pprof) top10
Showing nodes accounting for 5877.13MB, 99.19% of 5925.21MB total
Dropped 124 nodes (cum <= 29.63MB)
Showing top 10 nodes out of 57
flat  flat%   sum%        cum   cum%
3817.15MB 64.42% 64.42%  3817.15MB 64.42%  github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/process/input.(*RuntimeInput).AppendOverrides
676.34MB 11.41% 75.84%   676.34MB 11.41%  encoding/base64.(*Encoding).DecodeString
386.48MB  6.52% 82.36%  1062.81MB 17.94%  github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/storage.(*Encrypter).Decrypt
224.34MB  3.79% 86.15%   224.34MB  3.79% …
```
> Append overrides based on unique override key

- components/kyma-environment-broker/internal/runtime/handler.go
- resources/kcp/values.yaml
This changes is to capture cases when the runtime state cannot be reliably determined from the state of the last operation. One example is when the last operation was `upgradeKyma` type, which was `canceled`. In these cases fall back by default to assume the runtime is in an active "succeeded" state.
> KEB runtimes state: set to succeeded by default when operation state doesn't match

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json
- components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
- components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json
- components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema.json
- components/kyma-environment-broker/internal/provider/azure_provider.go
- docs/kyma-environment-broker/03-01-service-description.md
- resources/kcp/values.yaml
- Adjust autoScalerMax for create and update on azure_lite plan to:
```
"properties": {
"autoScalerMax": {
"default": 10,
"description": "Specifies the maximum number of virtual machines to create",
"maximum": 40,
"minimum": 2,
"type": "integer"
}
```
- #1072
> Adjust azure_lite autoScalerMax settings

- resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml
- resources/kcp/charts/kyma-metrics-collector/prometheus/alerts_test.yaml
- Adjust the alerting rule for `GardenerErrors` to only fire if collection for a specific shoot fails for 15 minutes
> Finetune Alerting for KMC

- components/kyma-environment-broker/README.md
- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/templates/profiler-pvc.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
During debugging OOMKilled KEB https://github.com/kyma-project/control-plane/pull/1111, use for a configurable profiler was discovered. This PR introduces a switch for enabling memory profiler as well as enabling PVC for persisting the profiler traces in a PVC.
**Here is 5 minute 101 course on how to use this functionality**
1. enable profiler in helm chart switching this from `false` to `true`
https://github.com/kyma-project/control-plane/blob/2f7b1384dc59901c4b08cc09f53b71b84e33eda7/resources/kcp/charts/kyma-environment-broker/values.yaml#L23
2. copy the profiles from the running pod
```
$ mkdir -p /tmp/keb-profiles
$ k cp -c profiler kcp-kyma-environment-broker-jw-76548f646-rnclv:/tmp/profiler /tmp/keb-profiles
```
3. look at any profile
```
$ go tool pprof …
```
> Configurable profiler for KEB

- tools/cli/pkg/command/reconciliations.go
- tools/cli/pkg/command/reconciliations_test.go
Using the kcp command
```
kcp rc -c <shoot_name>
```
sorts the entries by date in "Created at" column
- Added sorting functionality
- Added unit tests for sorting
See also https://github.com/kyma-incubator/reconciler/issues/454
> Kcp reconciliations commands lists items in historical order

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/services.go
- components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema-additional-params.json
- components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
- components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
- components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
- components/kyma-environment-broker/internal/provider/aws_provider.go
- docs/kyma-environment-broker/03-01-service-description.md
- resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
- resources/kcp/values.yaml
- machine types available for plans `aws` and `aws_ha` extended with `"m6i.2xlarge", "m6i.4xlarge", "m6i.8xlarge", "m6i.12xlarge"`
- [default machine type](https://github.com/kyma-project/control-plane/pull/1152/files#diff-50bac063fd6efced9ab53ac5e58a250131a3d60e540159e417e33063023272c8R216) for freemium and trial plans  (`aws` provider) changed to `m6i.xlarge`)
- Introduced `catalogRawSchema` which, if provided, overwrites the schema rendered by Services endpoint at `GET v2/catalog` - user's provisioning input is still validated using `provisioningRawSchema` field. This implementation allows backwards compatibility until the consumer updates the schema - new deployment will serve schema with `m6-*` machines for `aws` and `aws_ha` …
> Adjust AWS plans' machine types

- resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/templates/deployment.yaml
- Added liveness and readiness probes to rma reconciler. As SRE, we need the liveness probe defined in deployment.yaml so that istio can overwrite it. As a result, avs will be able to monitor this component.
> Add liveness and readiness probes to rma-reconciler

- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
- Add possibility to configure deployment strategy of mothership-reconciler
- Set rollingUpdate strategy with `maxSurge` = 0, `maxUnavailable` = 1 because PV with ReadWriteOnce is used by default, which could fail to be attached properly during rolling update. 
> Configurable deployment strategy for mothership-reconciler

- components/kyma-environment-broker/internal/runtime/handler.go
- resources/kcp/values.yaml
The previous [PR about exposing current Kyma version on /runtimes endpoint](https://github.com/kyma-project/control-plane/pull/1190) has multiple flaws, e.g. it doesn't take into account whether upgrade operations has been processed or not.
This PR fixes these issues.
> Fix determining current Kyma version by operations

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
- components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
- components/kyma-environment-broker/internal/process/update/sc_migration.go
- components/kyma-environment-broker/internal/process/update/sc_migration_check_step.go
- resources/kcp/values.yaml
In #825, I have introduced an error in update queue where irrecoverable errors from reconciler are silently ignored. This ensures that non-retryable errors related to reconciler are failing the operation as well.
related to recent debugging in https://github.com/kyma-project/control-plane/issues/1122
> Explicitly fail KEB update operations on irrecoverable errors

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
- components/kyma-environment-broker/internal/process/update/conditions.go
- resources/kcp/values.yaml
In #825, I introduced interactions with reconciler. The algorithm would execute reconciler  checks when operation contained `ClusterConfigurationVersion` populated from status of the last apply changes in reconciler. This number is inherited from previous operations and essentially meant that every update on kyma 2.0 would execute this check. An update to gardener could fail the operation if reconciler is having troubles. But we don't need to check status of the reconciler for purely gardener update operations.
This PR changes the check from looking at `ClusterConfigurationVersion` to explicit flag on an operation, that is set when certain step really talks to the reconciler and we need to wait for the processing to move forward to the next step. …
> Check reconciler status in update queue only when required

- components/kyma-environment-broker/internal/storage/driver/postsql/ext.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/encrypt.go
- resources/kcp/values.yaml
https://github.com/kyma-project/control-plane/pull/980 has introduced `SMOperatorCredentials` in the `ERSContext`. The encryption implemented for each operation and instance would drop the `SMOperatorCredentials` and not store them in database.
This enhances the work by storing encrypted credentials in `SMOperatorCredentials` struct for each operation and instance.
https://github.com/kyma-project/control-plane/issues/1163
> Encrypt BTP Operator ERS credentials

- components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
- resources/kcp/values.yaml
In #825, the `sc-migration` component was introduced and disabled for all queues except for upgrade with kyma2.0. 
For kyma1.x it is disabled here:
https://github.com/kyma-project/control-plane/blob/b7bdccf6100da21795877ad798777a6867d81238/components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step.go#L52
> Disable sc-migration component for upgrade queue on kyma2

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/appinfo/runtime_info.go
- components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
- components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_deprovision_operation.golden.json
- components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_provision_and_deprovision_operations.golden.json
- components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_provision_operation.golden.json
- components/kyma-environment-broker/internal/runtime/handler.go
- resources/kcp/values.yaml
updatedAt/modifiedAt timestamp value was taken from Instance, which is updated only in special cases for corresponding OSB API change like PATCH request (for example changing Instance parameters). Because `/runtimes` and `/info/runtimes` are technical endpoints and the entity which is described Runtime, the proper timestamp for the last "change" for particular Runtime is the timestamp of last operation update for this Runtime.
For example, if the provisioning operation for the Runtime has finished (despite the state - success or failure), and this is the only operation for this particular Runtime, the last operation's `updatedAt` timestamp should be shown in the presentation layer as the last change for the chosen Runtime.
- KEB takes …
> KEB takes updateAt/modifiedAt field for runtime status from last operation

- tools/cli/pkg/command/options.go
- USERNAME environment variable collides with shell default OS username on Windows and some Linux distributions. 
- Only allow specifying username in configuration file for tech user purposes, when ROPC is needed
> KCP CLI: username is not allowed to be set by USERNAME environment variable

- components/kyma-environment-broker/internal/cis/e2e/tests_utils.go
- components/kyma-environment-broker/internal/storage/tests_utils.go
- Replacing fixed tables in tests with SQL statements defined in the schema migrator
> KEB DB tests use SQL statements defined in the schema migrator instead of test_utils

- resources/kcp/values.yaml
- tests/e2e/provisioning/test/e2e_provisioning_test.go
- tests/e2e/provisioning/test/e2e_suspension_test.go
- disable dashboard-checker in e2e tests for kyma 2.0
> workaround: disable dashboard-checker in e2e tests for kyma 2.0

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
- components/kyma-environment-broker/internal/reconciler/fake.go
- resources/kcp/values.yaml
- the deprovisioning (suspension) process must clean the ClusterConfigurationVersion, so the unsuspension (proviosioning) process does not skip the reconciler call (https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go#L39)
> Suspension process cleans the ClusterConfigVersion

- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
- resources/kcp/values.yaml
- Check_Cluster_deregistration step is finished in few cases: cluster is "deleted" or cluster does not exists. In all cases it must clean the ClusterConfigurationVersion so the unsuspension process will start properly
> Cluster deregistration must clean ClusterConfigurationVersion if done.

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
- components/kyma-environment-broker/internal/process/update/initialisation_step.go
- components/kyma-environment-broker/internal/process/update/sc_migration_check_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- resources/kcp/values.yaml
Upgrade kyma queue currently ignores the fact ERS call could have updated ERSContext with new BTP operator credentials and would always install service catalog. This ensures KEB picks up the up to date ERSContext.
closes: https://github.com/kyma-project/control-plane/issues/1163
depends on:
> Make KEB upgrade kyma queue aware of BTP Operator credentials

- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- components/kyma-environment-broker/internal/provider/openstack_provider.go
- resources/kcp/values.yaml
Set shoot maxSurge to 1 in all plans for the least disruptive Gardener upgrades. Do not allow 2 concurrent drains for typical 2-node runtimes.
Workaround until https://github.tools.sap/kyma/backlog/issues/2122 is implemented.
> Set maxSurge = 1 for least disruptive Gardener upgrades

- tools/cli/pkg/command/runtime.go
- adds flag `--subscription-global-account-id` to kcp-cli to display additional field
```bash
$ ./kcp-darwin runtimes --subscription-global-account-id
GLOBALACCOUNT ID                        Subscription Global Account ID   SUBACCOUNT ID                               SHOOT       REGION         PLAN         CREATED AT            STATE
3e64ebae-38b5-46a0-b1ed-9ccee153a0ae    empty-gaID                                                                   c-48452c7                               2020/03/30 08:05:11   failed (deprovision)
3e64ebae-38b5-46a0-b1ed-9ccee153a0ae                                                                                                                         2020/04/01 14:01:35   failed (deprovision) …
```
> add flag to display subscription-global-account-id to kcp-cli

- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/process/update/sc_migration.go
- resources/kcp/values.yaml
```
panic: Operation cannot be fulfilled on usagekinds.servicecatalog.kyma-project.io "serverless-function": the object has been modified; please apply your changes to the latest version and try again
```
The update queue should disable svcat related components for the sc-migration. Disabling a reconciler currently won't remove the component, it will just stop reconciler on reconciling resources for those disabled components.
https://github.com/kyma-project/kyma/issues/12843
https://github.com/kyma-project/control-plane/pull/825
> Disable SVCAT related components for migration

- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/values.yaml
- Use the same (configurable) reconciler `ProvisioningTimeout`  in Kyma 2 upgrade process when polling mothership-reconciler, which is used during the provisioning process.
> KEB: Use configurable reconciler timeout in upgrade Check_Cluster_Configuration step

- CODEOWNERS
As @grego952 has been working with Kyma for over 3 months as a Technical Writer and has gained expertise in this domain, he should be added to the documentation CODEOWNERS.
- Add @grego952 to KCP documentation CODEOWNERS
**Related issue**
[#13077 ](https://github.com/kyma-project/kyma/issues/13077)
> Add grego952 as a documentaion CODEOWNER in KCP

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/internal/component_input_helpers.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides_test.go
- resources/kcp/values.yaml
For update and provisioning, we explicitly disable BTP operator and only enable it when appropriate creds are present. For upgrade, we relied on different logic and that is inheriting `InputCreator` from previous operations which may not be as robust as we thought. This is an effort to unify components enablement/disablement related to SVCAT migration.
mitigation of https://github.com/kyma-project/control-plane/issues/1286
> Explicitly disable BTP Operator for upgrade queue

- components/kubeconfig-service/pkg/transformer/kubeconfig.go
- components/kubeconfig-service/pkg/transformer/transformer_test.go
- components/kyma-environment-broker/internal/kubeconfig/builder_test.go
- components/kyma-environment-broker/internal/kubeconfig/kubeconfig.go
- resources/oidc-kubeconfig-service/values.yaml
- target `kubectl-oidc_login` executable in kubeconfig file in user section
- apply installHint in case the required `kubectl-oidc_login` plugin is not installed
https://github.com/kyma-project/control-plane/issues/1295
> Use installHint in generated kubeconfig

- resources/kcp/values.yaml
Add "cleaner" component reconciler (introduced to the reconciler codebase some time ago) in order to perform final cleanup of resources during Kyma undeploy (delete) operation.
- Add "cleaner" component reconciler to the global components list
See also: https://github.com/kyma-incubator/reconciler/issues/333
> Add "cleaner" component reconciler

- components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go
- resources/kcp/values.yaml
Service Instance update API call can change a runtime's autoscaler min/max parameters. However during orchestrated cluster upgrade, the provisioner shoot upgrade input is built using the original provisioning parameters used during runtime creation, which case updated parameters to be reset back to their original value.
> Fix resetting autoscaler params in cluster upgrade operation

- components/provisioner/cmd/init.go
- components/provisioner/cmd/main.go
- components/provisioner/internal/api/resolver_integration_with_gardener_test.go
- components/provisioner/internal/provisioning/service.go
- components/provisioner/internal/provisioning/service_test.go
- resources/kcp/values.yaml
Previous implementation to recognise if the version of the cluster being deprovisioned was Kyma 2.x was based on checking  missing `activeKymeConfigId` entry in the database. This entry was present only for previously provisioned `Kyma 1.x `clusters.
It turned out there are some cases when `Kyma 2.x` cluster might still have assigned this data. It is in the case of Kyma 1.x clusters upgraded to version `Kyma 2.x` because the upgrade was performed by the Reconciler and Provisioner was not aware about it. As a result Kyma version installed on the cluster was not identified correctly and deprovisioning ended with a failure.  
The current mechanism is using `installationSDK` library to identify if deprovisioned cluster was installed as `Kyma 1.x` (with `kyma-installer` and `installation CR`). …
> Improvement of checking Kyma version before starting cluster deprovision 

- components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
- components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
- components/kyma-environment-broker/internal/storage/postsql/factory.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/values.yaml
- replace GetLatestRuntimeStatesByRuntimeID() with GetLatestRuntimeStateWithKymaVersionByRuntimeID(),
- adjust GetLatestWithKymaVersionByRuntimeID(),
- provide test case for fetching the latest Runtimestate with Kyma version by RuntimeId
Ref: #1264
> Adjust query function to get latest Runtimestate with Kyma version

- components/provisioner/third_party/machinebox/graphql/graphql.go
- components/provisioner/third_party/machinebox/graphql/graphql_json_test.go
- components/provisioner/third_party/machinebox/graphql/graphql_multipart_test.go
- resources/kcp/values.yaml
Provisioner error logs contain all headers, which include sensitive data - authorisation headers.
- hide sensitive headers from logs (`Authorization`)
> Hide authorization headers in logs

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step.go
- components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
- components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
- components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
- resources/kcp/values.yaml
The runtime_state entity contains a field in the DB "kyma_version" which was updated by manual SQL script. The logic in the code executes a query, which filters by that field. But after that, it reads the kyma version from other field. In that case, the runtimestate contains the kyma_version (so the row was returned), but it was only gardener cluster update  - no kyma version in the data.
> Keb add kyma version

- components/kyma-environment-broker/Dockerfile.sac
- resources/kcp/values.yaml
OpenSSL from edge has version [1.1.1m-r1](https://pkgs.alpinelinux.org/package/edge/main/x86/openssl#), this is to remediate CVE-2021-4160 present in current `1.1.1l-r7`.
> Install openssl from edge

- resources/kcp/values.yaml
Using latest upstream CloudSQL proxy image to remediate [OpenSSL CVE-2021-4160](https://nvd.nist.gov/vuln/detail/CVE-2021-4160).
> Bump CloudSQL proxy image to 1.28.1

- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
OpenSSL from edge has version [1.1.1m-r1](https://pkgs.alpinelinux.org/package/edge/main/x86/openssl#), this is to remediate CVE-2021-4160 present in current `1.1.1l-r7`.
> Bump schema-migrator base image to 3.15.0

- tools/cli/pkg/command/reconciliations.go
- tools/cli/pkg/command/reconciliations_test.go
- IF shoot filter is provided it has to correspond to a valid runtime, otherwise no call to mothership is made
https://github.com/kyma-incubator/reconciler/issues/693
> Fix shoot filter response

- components/kyma-environment-broker/Dockerfile.sac
- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
Recently, I updated only OpenSSL client but not the library, which was still installed from the stable repo.
```
$ docker run kyma-environment-subaccount-cleanup-job openssl version
OpenSSL 1.1.1m  14 Dec 2021 (Library: OpenSSL 1.1.1l  24 Aug 2021)
```
this ensures the library is also the latest available from edge and not vulnerable to https://github.com/advisories/GHSA-ph2x-8239-7xc7
```
$ docker run kyma-environment-subaccount-cleanup-job openssl version
OpenSSL 1.1.1m  14 Dec 2021
```
https://github.com/kyma-project/control-plane/pull/1343, https://github.com/kyma-project/control-plane/pull/1339
> Install OpenSSL lib from edge in various KEB components

- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
Add startupProbe to mothership-reconciler deployment
See: https://github.com/kyma-incubator/reconciler/issues/820
> Add a startupProbe

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/avs_maintenance.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- resources/kcp/values.yaml
- Extract Setting & restoring AVS maintenance status to functions outside of Initialization step
- Set AVS statuses in maintenance correctly in Initialization step for both Kyma 1 and Kyma 2 runtimes
- Restore AVS statuses at the end of processing in Initialization step for Kyma 1 runtimes
- Restore AVS statuses at the end of processing in Check_Cluster_Configuration step for Kyma 2 runtimes
> Fix setting/restoring AVS maintenance during Kyma 2 upgrade

- components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
- resources/kcp/values.yaml
Check_Cluster_Configuration step shall ensure AVS evaluation status during Kyma upgrade based on reconciliation state. 
Check runtime status part in Initialization step is skipped even after KEB triggers reconciler, and should not be depended on (as there is no provisioner input in operation).
> Fix handling AVS evaluation statuses during Kyma 2 upgrade

- components/kyma-environment-broker/internal/metrics/operation_duration.go
- components/kyma-environment-broker/internal/metrics/operation_result.go
- components/kyma-environment-broker/internal/metrics/step_result.go
- resources/kcp/values.yaml
There are duplicate time-series for the same instance, once with `RuntimeID` and once without. For example:
```
compass_keb_provisioning_result{global_account_id="e449f875-b5b2-4485-b7c0-98725c0571bf",instance_id="test-jw148",operation_id="1d02bba0-20cc-4203-8d1d-84d2d2e21eb5",plan_id="361c511f-f939-4621-b228-d0fb79a1fe15",runtime_id=""} 2
compass_keb_provisioning_result{global_account_id="e449f875-b5b2-4485-b7c0-98725c0571bf",instance_id="test-jw148",operation_id="1d02bba0-20cc-4203-8d1d-84d2d2e21eb5",plan_id="361c511f-f939-4621-b228-d0fb79a1fe15",runtime_id="588a6fc4-ea11-407b-9906-25fcb2119a4e"} 2
```
The reason for duplicated `compass_keb_provisioning_result` time-series for each `InstanceID` is that KEB updates the value after each step in the provisioning queue. The …
> Remove RuntimeID from KEB metrics

- components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
- components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
- resources/kcp/values.yaml
- Once the cluster name is created, it is stored as a `clusterName` in the instance details and can be reused by next operations
> Resuse cluster name for reconciler calls

- components/provisioner/internal/operations/executor.go
- components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
Change the text in the log to indicate that empty Kubeconfig is a warning, not an error.
**Changes proposed in this pull request**
- change the log message from error to warning
> Change the level of logs regarding "cluster kubeconfig is nil" error

- components/kyma-environment-broker/internal/metrics/operation_result.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- resources/kcp/values.yaml
When the deprovisioning operation is triggered while the provisioning operation is still in progress, KEB reports confusing metrics and duplicate time-series for each `instance_id`.
```
compass_keb_deprovisioning_result{global_account_id="",instance_id="test-jw160",operation_id="782f1126-fc42-44c9-98a5-b4b8686f1a44",plan_id=""} 0
compass_keb_deprovisioning_result{global_account_id="e449f875-b5b2-4485-b7c0-98725c0571bf",instance_id="test-jw160",operation_id="782f1126-fc42-44c9-98a5-b4b8686f1a44",plan_id="361c511f-f939-4621-b228-d0fb79a1fe15"} 2
```
This is because `initialization_step` in the provisioning queue detects the provisioning operation is not finished and tells the manager to put the processing of this back in the queue before getting `ProvisioningParameters`.
The …
> Set provisioning parameters when processing deprovisioning operation

- resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
Disabling SQL validator by in-proper behaviour. Bugfix following soon.
https://github.com/kyma-incubator/reconciler/issues/937
> Disable SQL validator

- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- Remove trailing slash '/' from issuer URL when configuring OIDC provider from user input
> Normalise user input for isserURL

- tools/cli/pkg/command/options.go
- tools/cli/pkg/command/send_slack_notification.go
- tools/cli/pkg/command/upgrade_cluster.go
- tools/cli/pkg/command/upgrade_kyma.go
To implement task [kcp-cli orchestration sends slack info message ](https://github.tools.sap/kyma/backlog/issues/2323) that is auto-trigger  a slack message when execute the command `kcp upgrade kyma/cluster ***` 
testing example is https://sap-ti.slack.com/archives/CSCAQLZ98/p1646799451784189
[](https://app.slack.com/services/BSTAJ7YMC):high_brightness:[upgrade-info](https://app.slack.com/services/BSTAJ7YMC)APP  [12:17 PM](https://sap-ti.slack.com/archives/CSCAQLZ98/p1646799451784189)[](https://app.slack.com/services/BSTAJ7YMC)
upgrade kyma
kcp upgrade kyma  --target shoot=c-6a24f3f  --version 2.0.4
OrchestrationID:c94d828d-812a-4b20-a79b-4e27fe84403b
[](https://app.slack.com/services/BSTAJ7YMC):high_brightness:[upgrade-info](https://app.slack.com/services/BSTAJ7YMC)APP  [12:31 …
> kcp-cli orchestration sends slack info message

- components/kyma-environment-broker/internal/provider/aws_provider.go
- resources/kcp/values.yaml
- the aws lite (freemium) plan was overriding default lite region to different one, but not updating zones which makes a problem with aws freemium provisioning
> Fix aws lite regions

- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- Sets the value for  flags (via args) to enable new inventory and reconciliations cleanup
- All reconciliations and deleted inventory clusters before 4 days will be dropped
- Only recent 150 reconciliations will be retained, others will be dropped
https://github.com/kyma-incubator/reconciler/issues/884
https://github.com/kyma-incubator/reconciler/issues/867
> feat: enable new cleaner script on mothership

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
This PR changes the go.mod to force-replaces helm to only use 2.17.0 to fix security issues.
> replace helm to newest 2.17 version

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go
- components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go
- components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance_test.go
- resources/kcp/values.yaml
- add step for getting kubeconfig for deprovisioned cluster in deprovisioning queue
- add step for removing uaa-issuer service instance in deprovisioning queue
> Add remove service instance step to deprovisioning queue

- resources/kcp/charts/mothership-reconciler/values.yaml
- Introduces 10m Idle Time to not immediately close connections for the mothership DB Pool
> fix: Mothership Reconciler Values: increase connMaxIdleTime to not immediately close the connection

- CODEOWNERS
This only adds some new users as code owners for `/resources/kcp/value.yaml` so PRs with image bump in KMC can be done by these users.
> add new users to CODEWONERS for resources/kcp/values.yaml

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/internal/component_input_helpers.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
- resources/kcp/values.yaml
The ClusterID is not used by the BTP-Operator itself, only by the migration tool. For the update operation, KEB still populates this information but in the upgrade queue, it's no longer necessary.
closes: https://github.com/kyma-project/control-plane/issues/1597
> Remove ClusterID override from BTP-Operator upgrade queue

- resources/kcp/charts/mothership-reconciler/values.yaml
- resources/kcp/values.yaml
- Bumps Fluent-Bit Image in addition to regular image bump of reconciler to 1.8.15-a6fa9cb0
- Increases Connection Defaults in Control Plane for ConnMaxIdleTime in sync with https://github.com/kyma-incubator/reconciler/pull/1021
https://github.com/kyma-incubator/reconciler/pull/1049
https://github.com/kyma-incubator/reconciler/issues/959
https://github.com/kyma-project/control-plane/commit/1af9a289ec83cde0e40b548ed9e9e2aa09421a27
> Bump Mothership Fluent-Bit Plugin to 1.8.15-a6fa9cb0 / Fix Connection Defaults

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
- Added variables `error_category` and `error_reason` which are dependent on the query of selected plan_id.
- Added pannel `Success Rate (All)`  to show the overall success rate (all plans) for provision and deprovision.
- Added pannel `Provision - Top 3 error category and reason ($plan_id)` to show the top 3 pair of error category&reason for provision.
- Added pannel `Deprovision - Top 3 error category and reason ($plan_id)` to show the top 3 pair of error category&reason for deprovision.
- Update the `Fail` section number of each `Provision/Deprovision ($plan_id)` panel depending on the selected error_category and error_reason values as well.
> Update kcp-kyma-environment-broker-dashboard to have error category and reason

- components/kyma-environment-broker/cmd/subscriptioncleanup/job/cleaner.go
- components/kyma-environment-broker/cmd/subscriptioncleanup/job/cleaner_test.go
- components/kyma-environment-broker/cmd/subscriptioncleanup/main.go
- components/kyma-environment-broker/common/gardener/client.go
- components/kyma-environment-broker/go.mod
- components/kyma-environment-broker/go.sum
- resources/kcp/values.yaml
followup to https://github.com/kyma-project/control-plane/pull/1527, where KEB is stripping its dependency on gardener. Gardener is a rich source of CVEs There is only a very small subset of gardener API that KEB needs and it doesn't depend on the implementation at all.
https://github.com/kyma-project/control-plane/issues/1471
> Remove gardener for subscriptioncleanup job

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
This PR adds a `replace` of `k8s.io/helm` to version `2.16.1` in KMC to prevent potential security vulnerabilities.
> replace k8s.io/helm to 2.16.1 in go.mod

- resources/kcp/charts/component-reconcilers/charts/rma/templates/rbac.yaml
The extended permissions are needed for a change in runtime monitoring integration:
https://github.tools.sap/kyma/management-plane-config/pull/1590
> Extend RMA reconciler permissions

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
- Fixed the wrong numbers on kcp-kyma-environment-broker-dashboard for upgraded kyma/cluster which was reported in backlog [#2415](https://github.tools.sap/kyma/backlog/issues/2415)
> Fix the wrong numbers on kcp-kyma-environment-broker-dashboard for upgraded clusters

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
This PR bumps `gardener/gardener-extension-provider-azure` to prevent potential security vulnerabilities.
> bump gardener/gardener-extension-provider-azure

- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/runtime/handler.go
- components/kyma-environment-broker/internal/runtime/handler_test.go
- components/kyma-environment-broker/internal/storage/dbmodel/instance.go
- components/kyma-environment-broker/internal/storage/driver/memory/instance.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- components/kyma-environment-broker/internal/suspension/handler.go
- resources/kcp/values.yaml
Necessary adjustments due to changes introduced by https://github.com/kyma-project/control-plane/pull/1571.
Continuation of https://github.com/kyma-project/control-plane/pull/1655.
- change db queries to fetch shoot names from last operation (instead of extraction from dashboard URL),
- adjust tests,
- remove unnecessary code.
This PR is a quick fix for issues related to fetching runtimes, kubeconfig from kcp cli.
Improvement to implement in future: Instance and InstanceDTO should contain shootName field.
#1571, #1655
> Fix list instances query

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
- resources/kcp/values.yaml
For all components, when some input data changes, it is desired to go through Kyma upgrade. BTP operator will be the only exception because, for migration, it might be necessary to upgrade btp-operator component input data even on update operation when resolving upstream bugs when migration is still in progress.
> Update btp-operator overrides on KEB update operation

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/internal/component_input_helpers.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/btp_operator_overrides.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
- components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
- components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
- resources/kcp/values.yaml
https://github.com/kyma-project/control-plane/pull/1599 removed ClusterID from upgrade queue. This is actually required to be persisted and we can't send empty string to render the helm chart because reconciler does `helm template` first without any access to the cluster and then runs `kubectl apply` making the ClusterID different for every reconciliation.
> KEB manages cluster-id in cluster-config ConfigMap in SKR

- components/kyma-metrics-collector/Dockerfile
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
This PR bumps the version of `golang` 1.18.2.
> bump the build image to golang 1.18.2 in EC

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
This PR bumps the dependency `github.com/gardener/gardener` to `1.46.1` to prevent potential security issues.
> bump dependency github.com/gardener/gardener to 1.46.1 in KMC

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
This PR bumps `prometheus/client_golang` to `1.12.2` to prevent potential security issues.
> bump prometheus/client_golang to 1.12.2 in KMC

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
this PR bumps `gardener/gardener` to `1.46.2` to prevent potential security issues.
> bump gardener to 1.46.2

- components/provisioner/go.mod
- components/provisioner/go.sum
- resources/kcp/values.yaml
Update:
opencontainers/runc from `v1.0.0-rc92` to `v1.1.2`
> Update opencontainers/runc in Kyma Runtime Provisioner to latest version v1.1.2

- components/kyma-environment-broker/internal/broker/instance_last_operation.go
- components/kyma-environment-broker/internal/broker/instance_last_operation_test.go
- resources/kcp/values.yaml
- add mapStateToOSBCompliantState() to return OSB compliant operation states on last operation endpoint,
- add tests.
> Map last operation state to compliant OSB operation states

- components/kubeconfig-service/Dockerfile
fix protecode issue https://github.tools.sap/kyma/security-scans/issues/17529
> update to go1.18.2 for kubeconfig-service

- resources/kcp/charts/mothership-reconciler/values.yaml
We agreed with SREs to reduce the reconciliation redention to 100 entires instead of 150.
> reduce redention of reconciliation from 150 to 100

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
bumps the dependency `gardener` to `v1.48.1` to prevent potential security vulnerabilities.
> bump gardener to 1.48.1 in KMC

- tools/license_type_sync.bash
this provides a simple script along with the usage on how to synchronize ERS license type information to KEB via update instance endpoint. By default, it expects KUBECONFIG to be correctly set and port-forwards KEB database as a background process.
example usage:
```
$ ./license_type_sync.bash < ers_instances > log
```
> License type sync to KEB

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
this pr replaces all versions of the dependency `github.com/emicklei/restful` with `v3.8.0` for security concerns.
> Add replace dependency emicklei/restful with v3.8.0

- tools/reconciler/e2e-test/template-kyma-main.json
`Rafter` is no longer part of kyma main. This PR removes the component entry in the e2e test template for main test to allow the test job `nightly-main-reconciler-e2e` to pass successfully.
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/5616
https://github.com/kyma-project/kyma/issues/13155
> Remove rafter component from main e2e test template

- components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go
- components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
- components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go
- resources/kcp/values.yaml
there were cases when kyma upgrade failed with using kubeconfig to an SKR from provisioner
```
"msg":"Process operation failed: failed to create BTP Operator input: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable",
```
When debugging I have stumbled upon an interesting case when executing graphql query directly to provisioner. Sometimes it returns operational and valid kubeconfig, sometimes it returns nil
```
$ cat gql_runtime_status.bash
runtime_id=5ecffe9c-7663-4433-b813-705cf70179a0
curl 'localhost:3000/graphql' \
-H 'Content-Type: application/json' \
-H 'tenant: e449f875-b5b2-4485-b7c0-98725c0571bf' \
--data-binary @- << EOF
{
"query":"query {\n runtimeStatus(id: \"$runtime_id\") {\n …
```
> Log provisioner kubeconfig parameters

- resources/oidc-kubeconfig-service/templates/deployment.yaml
- resources/oidc-kubeconfig-service/values.yaml
- increase initialDelaySeconds for oidc-kubeconfig-service from 30s to 180s
> enhancement: increase initialDelaySeconds for kubeconfig-service

- resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
Allow authenticated access to KEB /runtimes to specified principals. 
KMC and mop-agent will have to be allowed to use the API.
> Allow authenticated access to KEB /runtimes to specified principals

- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- components/provisioner/internal/model/infrastructure.go
- components/provisioner/internal/model/infrastructure/azure/infrastructure.go
- components/provisioner/internal/provider-config-migrator/migrator_db_integration_test.go
- components/provisioner/internal/provisioning/service.go
- components/provisioner/pkg/gqlschema/models_gen.go
- components/provisioner/pkg/gqlschema/schema.graphql
- components/provisioner/pkg/gqlschema/schema_gen.go
- resources/kcp/values.yaml
- `.spec.networking.nodes` is configured provider specific way, as per suggestion from Gardener documentation. For Azure, it's the same as the VNET CIDR. For AWS, it's the VPC CIDR. For GCP, it's the Worker CIDR from GardenerConfig, which is used to configure the regional VPC subnet.
- `GardenerConfigInput` is extended to support specifying multiple Azure zones, using the [dedicated subnet per zone](https://github.com/gardener/gardener-extension-provider-azure/blob/master/docs/usage-as-end-user.md#infrastructureconfig-with-dedicated-subnets-per-zone) config which also enables zone redundant NAT Gateway. API change is backwards compatible with the current model, so both the old config input (single AZ zoned cluster) and the new config …
> provisioner: add support for Azure multi AZ, having dedicated subnet per zone

- tools/reconciler/e2e-test/template-kyma-2-4-x.json
The pipeline `pre-main-control-plane-reconciler-e2e-latest-release` is failing since Kyma 2.4.0 release - Due to the reason that `helm-broker`, `service-catalogue`, and `service-catalogue-addons` have been removed. This PR has a new template vor Kyma version >= 2.4.x.
After this PR has been merged, the prow script has to be adapted: https://github.com/kyma-project/test-infra/pull/5669
> Introducing body template for Kyma2.4.x

- tools/reconciler/e2e-test/template-kyma-2-4-x.json
Removed `rafter` from 2.4.x template
**Related PR(s)**
https://github.com/kyma-project/control-plane/pull/1829
> Fix pre-main-control-plane-reconciler-e2e-latest-release

- components/provisioner/pkg/gqlschema/schema.graphql
- components/provisioner/pkg/gqlschema/schema_gen.go
- resources/kcp/values.yaml
The new `azureZones` field in `AzureProviderConfigInput` input parameter was meant to be optional, to keep backwards compatibility with the current API (providing `zones` list only). 
> provisioner: fix azureZones input to be optional

- components/kyma-metrics-collector/README.md
- components/kyma-metrics-collector/dev/deployment.yaml
- components/kyma-metrics-collector/pkg/gardener/secret/client.go
- components/kyma-metrics-collector/pkg/gardener/secret/client_test.go
- components/kyma-metrics-collector/pkg/gardener/shoot/client.go
- components/kyma-metrics-collector/pkg/gardener/shoot/client_test.go
- components/kyma-metrics-collector/pkg/logger/logger.go
- components/kyma-metrics-collector/pkg/process/process.go
- resources/kcp/values.yaml
- Stop reporting error metrics from KMC if secrets or shoots are not found.
- Fix the development mode deployment.
- https://github.com/kyma-project/control-plane/issues/1640
> Stop reporting error metrics from KMC if secrets or shoots are not found

- resources/kcp/values.yaml
Reverts kyma-project/control-plane#1871
=> mandatory tests were not executed
> Revert "Update Reconciler images as necessary"

- components/provisioner/Dockerfile
- resources/kcp/values.yaml
CVE - 2022 - 2097 vulnerability in Provisioner
- change the Alpine version to 3.16 to avoid OpenSSL security vulnerability in the previous Alpine release
**Additional info**
[Link to reported CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-2097)
[Changes in Alpine 3.16, bumped OpenSSL to version 1.1.1q and 3.0.5 free from vulnerability](https://git.alpinelinux.org/aports/log/?h=3.16-stable&qt=grep&q=openssl)
> Change Alpine version in Provisioner -  OpenSSL security vulnerability fix

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
- components/kyma-environment-broker/internal/dto.go
- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
- components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
- components/kyma-environment-broker/internal/provisioner/client_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
The initial requirement was worded as:
> Gardener sets Enterprise Policy Filter by default. Provisioner accepts Enterprise Policy Filter true/false value as an input (field in GraphQL) for cluster provisioning. On KEB side when license_type:CUSTOMER/PARTNER/TRIAL keep Filter OFF, if any other value FILTER ON.
3.1) if license_type is not persisted on KEB side then TURN ON FILTER, we treat those Kyma instances as SAP ones.
Previously this was satisfied by https://github.com/kyma-project/control-plane/pull/1735 together with https://github.com/kyma-project/control-plane/pull/1478. But after https://github.com/kyma-project/control-plane/pull/1746 reverted the defaulting, I think it's probably best to always explicitly set this flag in KEB without any expectations of default …
> Always explicitly enable or disable network filter in KEB

- components/kyma-environment-broker/internal/process/operation_manager.go
- components/kyma-environment-broker/internal/process/operation_manager_test.go
This PR introduces generic operations helper called `OperationManager`. 
Every type of operation
* `ProvisioningOperation` 
* `DeprovisioningOperation`
* `UpgradeKymaOperation`
* `UpgradeClusterOperation`
* `UpdateOperation`
had their own implementation of set of database convenience methods in for of operation managers called:
* `ProvisioningOperationManager`
* `DeprovisioningOperationManager` 
* `UpgradeKymaOperationManager`
* `UpgradeClusterOperationManager`
* `UpdatingOperationManager`
As part of the refactoring and simplification initiative, we would like to unify this approach to avoid code duplication. Given each manager evolved later slightly differently, I selected subset of following functions
* `UpdateOperation` and its derivatives `OperationFailed`, …
> Generic storage helper

- components/kyma-environment-broker/internal/broker/plans.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Due to discrepancy between GCP machine types in KEB and in Gardener selection of n2-standard-48 causes error since Gardener do not allow this machine type. See https://github.tools.sap/kyma/backlog/issues/2790
https://github.wdf.sap.corp/kubernetes/landscape-setup/pull/4635 introduced missing machine type to Gardener but it will take up to two weeks till the change reaches productions. 
So temporarily we remove n2-standard-48 and we will restore it when the new version of Gardener is on production.
- Removal of n2-standard-48 GCP machine type
https://github.tools.sap/kyma/backlog/issues/2790
> temporarily removed n2-standard-48

- components/kyma-environment-broker/cmd/broker/upgrade_cluster_test.go
- components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
- components/kyma-environment-broker/internal/storage/driver/memory/runtime_state.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
- fix getting last kyma version
The problem is that the code is looking for a runtime state with kyma version, but getting a version from such record uses different places than the filtering "where" statement.
The in memory implementation differs than SQL so unit tests were working fine
> Fix getting last kyma version

- scripts/dependabot_helper.bash
Dependabot is enabled for KEB, however, after making `pre-main-kcp-cli` check run for KEB as part of https://github.com/kyma-project/test-infra/pull/5776, the bot is struggling to produce PRs that would pass the `pre-main-kcp-cli` check. The discussion about long-term path is currently under https://github.com/kyma-project/control-plane/issues/1929 and this script is intended as temporary remediation until the consensus on what to do in future is reached.
> Add dependabot helper for KEB

- components/kyma-environment-broker/internal/broker/plans.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Restoring n2-standard-48 as available machine type after gardener allows this type as well.
- n2-standard-48 machine type added to available set of machines for GCP
Fixes https://github.tools.sap/kyma/backlog/issues/2790
> n2-standard-48 restored since gardener allows this machine type at last

- components/kyma-environment-broker/internal/process/provisioning/check_runtime_step.go
- components/kyma-environment-broker/internal/process/update/check_step.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go
- components/kyma-environment-broker/internal/suspension/handler.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Managed kyma reports cases when unsuspension fails with the following error
```
"Operation dos not contain Provisioner Operation ID"
```
In the reported cases, the preceding suspensions for these cases failed as well. Additional symptoms are that the `RuntimeID` is the same before suspension as well as after. In all cases are log entries similar to these:
**Failure in unsuspending** happening on `2022-08-08T02:18:14Z`
<details>
<summary>unsuspend log payload</summary>
```json
{
"insertId": "kijpt7l3i1ua2wxq",
"jsonPayload": {
"operation": "0002a0d9-0d19-4378-93c8-ef13b6f90f99",
"provisioning": "manager",
--"instanceID": "0B83FC4F-731A-46D9-BECC-528FAD307DCB",
--"runtimeID": "a23c1dd9-c231-4e6d-8760-87f0edcff56d",
"stage": "create_runtime",
"step": "Check_Runtime",
"planID": …
```
> Require succeeded suspension to call unsuspension

- tools/cli/pkg/command/options.go
- I have made Oauth2 related parameters optional. 
Reason: 
Deprovision command uses oauth2 to send the request and thus we had previously added oauth2 related configs to cli. One of the configs is a secret value. That secret value should be added manually by the cli user. The problem about this setup is that, we have just realized developers do not have access to secret resources in mps-stage and mps-prod. 
I am going to initiate a discussion to come up with a solution. In the meantime, I need to make oauth2 related config optional in order not to cause any problems. 
`See also #1691`
`See also #1692`
`See also`  https://github.tools.sap/kyma/documentation/pull/244
> Delete oauth2 config from required list of params

- components/kubeconfig-service/cmd/generator/main.go
- components/kubeconfig-service/pkg/runtime/runtime.go
- components/kubeconfig-service/pkg/runtime/runtime_kcp.go
- resources/oidc-kubeconfig-service/templates/deployment.yaml
- resources/oidc-kubeconfig-service/values.yaml
enhance the initialization process of kubeconfig service to solve slow-start problem
- make readinessProbeDelay editable
- reduce expire time to 24 hours
- move ConfigMaps initialization to goroutine
https://github.tools.sap/kyma/backlog/issues/2801
> enhancement: kubeconfig service slow start

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go
- components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
After removing https://github.com/kyma-project/control-plane/pull/1956, it was identified that there is currently a need for SKR cleanup of BTP Operator resources by KEB for suspensions.
KEB doesn't currently have any built-in mechanism to mark the operation as failed while still going through all the steps of deprovisioning. As a result, if the suspension operation fails to cleanup BTP-Operator resources, the errors appear in logs only and after the 30 min timeout, the operation processing continues forward with next steps as if nothing was wrong. This may result in external resource leakage but the team consensus is that this is acceptable.
> BTP-Operator cleanup for suspensions

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
Partial kubernetes versions (e.g. major.minor: 1.23) can be configured in Gardener, however KEB chart doesn't support it as helm will convert the input value from string to a float number automatically. 
> Fix missing quote around .Values.gardener.kubernetesVersion

- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/dto.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
As a part of PoC we extend provisioning request with field (optional) containing encoded kubeconfig.
It should facilitate provisioning Kyma on cluster provided by the caller.
- DTO with Kubeconfig field
> Kubeconfig field added to provisioning request

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup_test.go
- components/kyma-environment-broker/internal/test_utils.go
I switched the runtime scheme in tests to use globally defined scheme in https://github.com/kyma-project/control-plane/pull/1974#discussion_r951331308, but this has introduced flakiness within the tests failing with:
```
fatal error: concurrent map read and map write
...
[0119] | /workspace/go/src/github.com/kyma-project/control-plane/components/kyma-environment-broker/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:267 +0x1b5 fp=0xc000feb190 sp=0xc000feb0a0 pc=0x9a5b35
[0119] | sigs.k8s.io/controller-runtime/pkg/client/apiutil.GVKForObject({0x1c38fa8, 0xc0005265b0}, 0xc0005265b0)
...
```
the reason is that multiple tests can be run in parallel and they each initialize their own additional API groups.
This PR goes back to scheme per test so no concurrent map read/write …
> Use runtime scheme per unit test thread

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_schema.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json
- components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
- resources/kcp/charts/kyma-environment-broker/values.yaml
It is requested that KEB catalog contains detais for machine types as described in:
```diff
51,54c63,67
<                         "n2-standard-8 (8vCPU, 32GB RAM)",
<                         "n2-standard-16 (16vCPU, 64GB RAM)",
<                         "n2-standard-32 (32vCPU, 128GB RAM)",
<                         "n2-standard-48 (48vCPU, 192GB RAM)"
---
>                         "n2-standard-4",
>                         "n2-standard-8",
>                         "n2-standard-16",
>                         "n2-standard-32",
>                         "n2-standard-48"
```
This PR uses `_enumDisplayName` SAP enhancement to OSB API as described in:
https://wiki.one.int.sap/wiki/pages/viewpage.action?spaceKey=CPC15N&title=%5BCookbook%5D+How+to+Render+a+Form+for+Input+Paramete …
> Display machine type details in KEB catalog

- components/kyma-environment-broker/internal/metrics/metrics.go
- components/kyma-environment-broker/internal/metrics/operation_result.go
https://github.com/kyma-project/control-plane/pull/1875 has introduced new operations processing manager with callbacks for most of the metrics but looks like `compass_keb_provisioning_result` got forgotten for steps processing. This adds the callback following the patterns set by #1875.
Queried on custom deployment shortly after provisioning call
```
$ curl localhost:8080/metrics | grep compass_keb_provisioning_result
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  339# HELP compass_keb_provisioning_result Result of the provisioning 4200
k # TYPE compass_keb_provisioning_result gauge
compass_keb_provisioning_result{error_category="",error_reason="",global_account_id="e449f875-b5b2-4485-b7c0-987 …
```
> Register compass_keb_provisioning_result metrics to generic operations manager

- components/provisioner/Dockerfile
- components/provisioner/go.mod
- components/provisioner/go.sum
CVE-2022-21698 vulnerability in Provisioner
- change client_golang to 1.11.1 due to CVE in 1.11.0
**Additional info**
[Link to reported CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21698)
> Provisioner - change client_golang to 1.11.1 due to CVE in 1.11.0

- tools/cli/.gitignore
- tools/cli/Makefile
@kyma-project/gopher would like to build and release the ERS cli tool the same way KCP cli is done in [test-infra](https://github.com/kyma-project/test-infra/blob/084f90d558559078fab4d6c80302e190ea9a5e23/prow/scripts/build-kcp-cli.sh#L51). This is a preliminary step to have both executables build in a standard, unified way.
> Build ERS cli by tools Makefile

- tools/cli/Makefile
Followup to https://github.com/kyma-project/control-plane/pull/2053, this reduces repetitiveness of build target definitions.
The change is rather cosmetic, main goal is actually to trigger automated builds from https://github.com/kyma-project/test-infra/pull/6031 to check if they work ok.
> Non-repetitive definition of build targets for CLI tools

- components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go
- components/kyma-environment-broker/internal/process/operation_manager.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
The `OperationManager` was swallowing errors from steps executions and only returning errors when storage update itself failed which resulted in metrics for failed operations no longer contained `LastError` categorization. This bugifx should address the problem.
> Aggregate error from operation manager when marking operation as failed

- components/kyma-environment-broker/internal/process/operation_manager.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
https://github.com/kyma-project/control-plane/pull/2069 used [post go 1.13 error wrapping](https://go.dev/blog/go1.13-errors) which is not yet supported by metrics error unwrapping. Reverting to use https://github.com/pkg/errors and KEB should deprecate the package as a whole, it's not possible to do it gradually.
> Revert KEB operation manager to legacy error wrapping

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Improvements in handling of bring own cluster plan
- Masking kubeconfig before logging it
- Decoding kubeconfig - it should be base64 encoded in the request
- Decrypting kubeconfig conditionally - to support backward compatibility
> Bring you own cluster - kubeconfig in base64 in request body

- components/kyma-environment-broker/common/gardener/client.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
The error when initiating `RESTConfig` for gardener client was being swallowed, this propagates the error for easier debugging.
> Fix swallowing gardener client error in KEB

- components/kyma-environment-broker/internal/runtime/converter.go
- components/kyma-environment-broker/internal/runtime/converter_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
The `/runtimes` response' runtime state show "suspended" for suspension failed runtimes
```
{
"data": [
{
"instanceID": "00EB1D6A-F5C1-47B1-837A-65A8CD512D82",
"runtimeID": "63cc19d5-0005-4b72-8cc0-5709265cd2c7",
"globalAccountID": "f3ef6db1-7a41-4a7a-96ab-a97ba4672de9",
"subscriptionGlobalAccountID": "",
"subAccountID": "9cdb4347-07ff-4b05-bbf3-ac0a8fef1672",
"region": "ap-southeast-1",
"subAccountRegion": "cf-ap21",
"shootName": "c-1c8c5e3",
"serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
"serviceClassName": "kymaruntime",
"servicePlanID": "7d55d31d-35ae-4438-bf13-6ffdfa107d9f",
"servicePlanName": "trial",
"provider": "AWS",
"status": {
"createdAt": "2022-09-19T04:22:00.094931Z",
"modifiedAt": "2022-10-04T01:25:23.294792Z",
"expiredAt": …
```
> Fix setting failed state for suspend failed runtimes in /runtimes response

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/broker/instance_update_test.go
- components/kyma-environment-broker/internal/suspension/handler.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
- an expired instance could be "resuspended" if the last suspension has failed.
- the scenario is covered by the test: https://github.com/kyma-project/control-plane/blob/f00e19395114a801d65947d6aa9721e4d72cf69e/components/kyma-environment-broker/cmd/broker/update_test.go#L144
> Allow to retrigger suspension of expired instance

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
As a part of Bring Your Own Gardener Cluster we implemented passing kubeconfig as a part of request object.
This kubeconfig shall be base64 encoded.
- kubeconfig validation i.e. successful creation of config object and validation of the object
> Kubeconfig validation for own cluster plan

- resources/kcp/charts/provisioner/templates/gardener-creds-secret.yaml
- resources/kcp/charts/provisioner/values.yaml
- add annotation "argocd.argoproj.io/hook" to  gardener-credentials secret , so we can control resourceHook via override
> add annotation for gardener-credentials secret allowing argoCD to skip

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/events/handler.go
- components/kyma-environment-broker/internal/storage/dbmodel/events.go
- components/kyma-environment-broker/internal/storage/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/events/events.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/postsql/factory.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- components/kyma-environment-broker/internal/storage/storage.go
- resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
This is a followup to KEB tracing events proposal in https://github.com/kyma-project/control-plane/pull/2094. Exposing events as a API with some basic filtering options in form of URL param `?instance_id=`, `?runtime_id=`, `?operation_id=`
<details>
<summary>example</summary>
state from the db:
```
broker=> select * from events where instance_id='test-jw231';
id                  | level | instance_id |             operation_id             |                          message                          |          created_at
--------------------------------------+-------+-------------+--------------------------------------+-----------------------------------------------------------+-------------------------------
3b36a6f8-4cf9-44e7-998c-38cc1e60e352 | info  | test-jw231  | …
```
> API for KEB tracing events

- components/kyma-metrics-collector/Dockerfile
- resources/kcp/values.yaml
to prevent bugs and security issues.
> bump build image in Dockerfile to golang1.19.2-alpine3.16 in KMC

- README.md
- docs/README.md
Remove the link to KCP CLI. The documentation on KCP CLI was removed as outdated.
> Remove the link to KCP CLI

- components/kyma-environment-broker/internal/process/staged_manager.go
- components/kyma-environment-broker/internal/storage/driver/postsql/events/events.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Currently, steps in operation processing are not forwarding errors to the staged manager which makes visibility with tracing events limited. This PR will at least help to observe a step when the process is put to sleep and also clearly state when the operation changed to one of the terminal states.
> Enhance staged manager tracing events in KEB

- CODEOWNERS
Dropping tobiscr from CODEOWNER file. Ownership no longer needed caused by team/role restructuring.
> Dropping tobiscr from` values.yaml` ownership

- components/kyma-environment-broker/internal/storage/storage.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
During the review of https://github.com/kyma-project/control-plane/pull/2094#discussion_r987810866, it was decided that in case DB sink is not configured, the default for tracing events for tests should be `/dev/null`. The https://github.com/kyma-project/control-plane/pull/2203 enabled to implement different sink backends for tracing events.
This PR implements in memory / stdout sink for tracing events, configured for unit tests.
> Implementation of in memory tracing events sink for tests

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/staged_manager.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
During review of https://github.com/kyma-project/control-plane/pull/2094, @piotrmiskiewicz expressed desire to have event throwing helper on operations struct directly. Before https://github.com/kyma-project/control-plane/pull/2203 this was difficult because of import cycle but now it should be simple to implement such helper there.
> Tracing events helper on operation struct in KEB

- resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
In https://github.com/kyma-project/control-plane/pull/2216, I forgot to update RBAC for KEB to manage secrets for lifecycle manager.
```
{"instanceID":"799efc2c-a78f-4388-8046-e21f06d856a0","level":"error","msg":"failed to create kubeconfig secret kyma-system/kubeconfig-28704cd3-09c3-40c1-993d-ca7199c6c02a for lifecycle manager: secrets is forbidden: User \"system:serviceaccount:kcp-system:kcp-kyma-environment-broker\" cannot create resource \"secrets\" in API group \"\" in the namespace \"kyma-system\"","operation":"7e21985b-745f-4464-9bf8-8ed6597f5eac","planID":"7d55d31d-35ae-4438-bf13-6ffdfa107d9f","provisioning":"manager","stage":"create_runtime","step":"Sync_Kubeconfig","time":"2022-11-11T10:22:15Z"}
```
> KEB RBAC to manage secrets for lifecycle manager

- components/kyma-environment-broker/internal/metrics/metrics.go
- components/kyma-environment-broker/internal/metrics/operation_duration.go
- components/kyma-environment-broker/internal/process/events.go
- components/kyma-environment-broker/internal/process/staged_manager.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Reported by @JackCheng01:
> We are collecting metrics like `compass_keb_deprovisioning_duration_minutes_sum` in grafana [dashboard](https://github.com/kyma-project/control-plane/blob/a7e4debe949f4185914cc8cd1f0c3c808a7bed8b/resources/kcp/charts/kyma-environment-broker/files/dashboard.json) for KEB.
We observed metrics for [deprovisioning_duration_minutes](https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/internal/metrics/operation_duration.go#L31-L37) are missing.
> <img width="1734" alt="image" src="https://media.github.tools.sap/user/906/files/74fe196a-2874-4ce0-a5ae-48a003c3cf2d">
> Issue persists on current version deployed on dev:
`eu.gcr.io/kyma-project/control-plane/kyma-environment-broker:PR-2203`
The …
> Hook legacy deprovisioning duration metric to staged manager

- components/kyma-environment-broker/internal/model.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Some time ago, we introduced a regression that suspension operations don't get provisioning parameters inherited from previous operations. This appears in DB as missing plan ID for example:
```
broker=> select id, instance_id, state, type, provisioning_parameters->'plan_id' as planid, created_at, updated_at from operations where instance_id = 'test-jw252';
id                  | instance_id |   state   |    type     |                 planid                 |          created_at           |          updated_at
--------------------------------------+-------------+-----------+-------------+----------------------------------------+-------------------------------+-------------------------------
5f4c19fe-8a7f-49d3-84e8-16889e26d1fd | test-jw252  | succeeded | provision   | …
```
> KEB should pass provisioning parameters for suspension operations

- resources/kcp/charts/component-reconcilers/values.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
bumping manually to alleviate parsing problems due to https://github.com/kyma-project/test-infra/pull/6403
- bumps to first properly tagged reconciler on main, after this bumping will work normally again in the control image bump job: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/reconciler-control-plane-image-bump
> Update Reconciler images as necessary (Manual)

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Logic to cover the case when during `trial` deprovisioning (suspension) we are not able to remove service bindings and service instances. During BTPOperator_Cleanup step we should remove all service bindings and all service instances.
- While testing trial plan after SKR creation we add one service instance and one service binding
- After deprovisioning we check if the resources no longer exist
> Assert the removal of service binding and instances during trial deprovisioning

- components/kyma-environment-broker/common/runtime/client.go
- components/kyma-environment-broker/common/runtime/model.go
- components/kyma-environment-broker/internal/events/interface.go
- components/kyma-environment-broker/internal/runtime/handler.go
- components/kyma-environment-broker/internal/storage/dbmodel/instance.go
- components/kyma-environment-broker/internal/storage/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
- tools/cli/pkg/command/runtime.go
Whenever an instance is deprovisioned, the root reference in `Instances` table is deleted which results in failure to get any data through KCP. However, there is a possibility to reconstruct some data from residual `Operations` and events.
This PR enables getting some subset of information for troubleshooting purposes with following usage:
```
$ kcp runtime -i [instance_id] --include-deleted
```
<details>
<summary>sample usage</summary>
Old way for calling kcp on deleted instance
```
$ kcp runtime -itest-jw252
GLOBALACCOUNT ID   SUBACCOUNT ID   SHOOT   REGION   PLAN   CREATED AT   STATE
```
Proposed `--include-deleted` parameter that will try best effort to reconstruct instance details from residual operations
```
$ kcp runtime -itest-jw25 --include-deleted
GLOBALACCOUNT …
```
> Option for KCP to display at least partial information for deprovisioned instances

- components/kubeconfig-service/Dockerfile
- resources/oidc-kubeconfig-service/values.yaml
Update Dockerfile for kubeconfig-service to use scratch image.
> Update Dockerfile for kubeconfig-service to use scratch image

- components/kyma-environment-broker/common/runtime/client.go
- components/kyma-environment-broker/common/runtime/model.go
- components/kyma-environment-broker/internal/runtime/handler.go
- components/kyma-environment-broker/internal/storage/dbmodel/instance.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
- tools/cli/pkg/command/runtime.go
In https://github.com/kyma-project/control-plane/pull/2283, new flag for `kcp runtimes` called `--include-deleted` was introduced. After followup discussion in https://github.com/kyma-project/control-plane/issues/2256, it was expressed as desirable to rename the flag to `--only-deleted` with all semantic changes relevant for the rename.
closes: https://github.com/kyma-project/control-plane/issues/2256
> Change KCP runtime flag `--include-deleted` to `--only-deleted`

- resources/kcp/templates/migrator-job.yaml
Moving kcp-migration-broker and kcp-migration-provisioner jobs to pre-install/pre-upgrade hook, as we observed issues that argocd did not execute this job during post-sync having conflict with long-running post-sync e2e test. 
[KCP Dev Provision failed: \"eu_access\" of relation \"gardener_config\" does not exist #3295](https://github.tools.sap/kyma/backlog/issues/3295)
> kcp-migration-broker and provisioner - change on helm hook annotations

- components/kyma-environment-broker/cmd/environmentscleanup/main.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
It was noticed that environment cleanup job started failing:
The error message is
```
time="2022-12-16T00:00:57Z" level=fatal msg="while loading cleanup config: %!w(<nil>)" component="environmentscleanup/main.go:89:main.fatalOnError"
```
The error wrapping implemented in https://github.com/kyma-project/control-plane/pull/2234 had a side effect here that even `nil` error is still wrapped which results in marking job as failed. It surfaced during the last image bump https://github.com/kyma-project/control-plane/pull/2337.
This PR proposes remediation in form of explicit error checking.
> Explicit err check before err wrapping

- components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Currently hash is logged as binary converted to string.
- `kubeconfig` hash is not logged any more
> Do not Log kubeconfig hash

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/aws_provider_test.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
For access from PlatformRegions `cf-eu11` and `cf-ch20` we restrict set of available regions accordingly. When region is not provided default is assumed - this is not aligned with EU Access restrictions. 
- Default regions for AWS and Azure plans are EU Access compliant in case EU Access restrictions apply
> EU Access in KEB - handling default regions

- tools/cli/pkg/command/orchestration.go
- tools/cli/pkg/command/upgrade.go
KCP CLI doesn't currently propagate the `--maintenancewindow` option to KEB properly. This PR fixes it. 
> KCP CLI: fix setting maintenance window

- resources/kcp/templates/migrator-job.yaml
This reverts commit 2cce31ffd9e794f646514d92d941752c6770840a.
The change causes problems during update after pruning resources deployed after the pre-upgrade hook.
> Revert "kcp-migration-broker and provisioner - change on helm hook annotations (#2330)"

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/apply_kyma_step.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
KEB should be configurable to dynamically enable and disable its integration with Lifecycle Manager as well as Reconciler.
related to: https://github.com/kyma-project/kyma/issues/15445
<details>
<summary>kcp events</summary>
the lifecycle manager steps are highlighted
```diff
$ kcp rt --events -i test-jw256
GLOBALACCOUNT ID                       SUBACCOUNT ID                          SHOOT       REGION         PLAN   CREATED AT            STATE            KYMA VERSION
e449f875-b5b2-4485-b7c0-98725c0571bf   19ea2000-865d-42fd-8d6f-3e3e2dcce3c8   c-98ca31a   eu-central-1   aws    2023/01/04 09:59:12   deprovisioning   2.9.3
˫provision operation 4b7134a3-2dac-4e81-8ba2-596def96149a: succeeded
˫info   89m                         processing step: Starting
˫info   89m …
```
> Configurable integration of KEB with LM and Reconciler

- components/kubeconfig-service/pkg/runtime/runtime.go
- resources/oidc-kubeconfig-service/values.yaml
In K8S 1.24, the default behavior of generating tokens for service accounts has changed:
> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets). (https://github.com/kubernetes/kubernetes/pull/108309, …
> kubeconfig-service: use SA TokenRequest API instead of secret bound token

- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
KEB occasionally crashes with concurrent ma writes
```
fatal error: concurrent map writes
/go/src/github.com/kyma-project/control-plane/components/kyma-environment-broker/cmd/broker/main.go:426 +0x65
/go/src/github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go:196 +0x194
```
The stacktrace points to `k8sClientProvider` function used in operations to get kube client. It is called during the processing of each operation, however, it uses global `Scheme` from the client-go package and tries to register `apiextensions` group each time. Processing two operations at the same time then risks concurrent map write because `Scheme` is implemented as a map of `GroupVersionKind` to `runtime.Object`.
This change registers …
> Fix scheme concurrent map write panic

- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
We need to test how BTP presents the result of instance creation failure.
- Every instance creation request with predefined subaccont ID fails with a distinctive message.
> For testing purposes always fail instance creation (EU Access story)

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
- components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go
- components/kyma-environment-broker/internal/process/deprovisioning/ias_deregistration.go
- components/kyma-environment-broker/internal/process/operation_manager.go
- components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
If a step cannot finish his job and goes to the next one, the step needs to be marked. The idea is to store those steps
- Store the step that was retried via `RetryOperationWithoutFail` without success in the DB
> Store failed steps during deprovisioning

- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/dto.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
- components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
- Allow MachineType update in KEB OSB API
- Sanitize BTP Operator overrides for KEB update operation
**Tested with following scenario:**
1) Provision instance in AWS larger than the default machine type - `m5.2xlarge` with put payload
```
$ kubectl get shoot f6f9e78 -o json | jq '.spec.provider.workers[].machine.type'
"m5.2xlarge"
```
2) Update machine type `m5.2xlarge` -> `m5.xlarge` with patch 1 payload
```
$ kubectl get shoot f6f9e78 -o json | jq '.spec.provider.workers[].machine.type'
"m5.xlarge"
```
3) Update machine type `m5.xlarge` -> `m5.large` with patch 2 payload
```
$ kubectl get shoot f6f9e78 -o json | jq '.spec.provider.workers[].machine.type'
"m5.large"
```
4) Update machine type `m5.large` -> `m5.2xlarge` with patch 3 payload
```
$ kubectl get shoot f6f9e78 …
```
> KEB update machine type

- components/kyma-environment-broker/internal/process/staged_manager.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
When operation processing is finished, KEB `staged_manager` sets the operation state but keeps the description. Example for status after successful deprovisioning operation:
```
$ curl -XGET "${KEB}/oauth/v2/service_instances/${INSTANCE}/last_operation" -H "X-Broker-API-Version: 2.14"
{"state":"succeeded","description":"Operation created"}
```
This change sets the description for successfully processed operations.
```
$ curl -XGET "${KEB}/oauth/v2/service_instances/${INSTANCE}/last_operation" -H "X-Broker-API-Version: 2.14"
{"state":"succeeded","description":"Processing finished"}
```
> KEB to set operation description on success

- components/kyma-environment-broker/Dockerfile.job
Currently, there are 5 copy-paste Dockerfiles for various KEB `Jobs`. These all have similar content, only difference is the binary name and source path to respective `main.go` and container images are built by [test-infra kaniko build jobs](https://github.com/kyma-project/test-infra/blob/586a1f5/templates/data/control-plane-build.yaml).
* [`Dockerfile.cleanup`](https://github.com/kyma-project/control-plane/blob/6d611bf/components/kyma-environment-broker/Dockerfile.cleanup) - [test-infra](https://github.com/kyma-project/test-infra/blob/586a1f5a94de7e4bb96463aaf8d5abb75cc9b471/templates/data/control-plane-build.yaml#L164)
* [`Dockerfile.drj`](https://github.com/kyma-project/control-plane/blob/fd6fb1c/components/kyma-environment-broker/Dockerfile.drj) - …
> Generic Dockerfile for KEB jobs

- components/kyma-environment-broker/common/runtime/model.go
- components/kyma-environment-broker/internal/runtime/converter.go
- components/kyma-environment-broker/internal/storage/postsql/write.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Followup to https://github.com/kyma-project/control-plane/pull/2429, the `deleted_at` never got to the database because it was not set.
see also: https://github.com/kyma-project/control-plane/issues/2406#issuecomment-1437230078
> KEB set and read instance deleted_at field

- tools/cli/pkg/command/upgrade.go
Reverts kyma-project/control-plane#2504
With this change, there is no possibility to set "no maintenance window".
> Revert "Modify KCP CLI to deploy with maintenancemode flag set to true by default."

- resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
https://github.com/kyma-project/control-plane/pull/2477 accidentally duplicated `command` for trial cleanup job.
```
...
147 2023-02-28T09:40:05.1854481Z /github/home/generated.yaml - CronJob trial-cleanup-job failed validation: error unmarshalling resource: error converting YAML to JSON: yaml: un     marshal errors:
148 2023-02-28T09:40:05.1854620Z   line 92: key "command" already set in map
...
```
> Remove duplicate 'command' for trial cleanup job

- tools/cli/pkg/command/reconciliations_state.go
reported internally by @zralt 
> Using `kcp rc state` command seems to be heavily flawed, when I use it with `-c shoot_id`  it returns a random entry (not every time, but it's pretty frequent).
It also seems to be working fine with the "-r runtime" flag.
> Now I wonder that this is related to using the shoot flag, and in that case maybe some clusters got their reconciliation disabled while I was trying to disable the cluster `f34cd39`. Seemingly it never picked this cluster.
> To reproduce:
For ex. on the prod environment, issue this a few times:
```
kcp rc state -c f34cd39 -ojson
```
This fixes the `runtimeID` variable shadowed in code resulting in it always being an empty string `""`.
Before fix:
```
$ kcp rt -c c-247e667 -o json | jq '.data[].runtimeID' …
```
> Fix 'kcp rt status -c shoot' returning random runtime status

- components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
- components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
`OwnCluster` is not handled properly in the `release_subscription` step and a wrong assertion is used in `TestReleaseSubscriptionStep_TrialPlan`. This PR fixes it.
- Handle `OwnCluster` plan
- Add test case for `OwnCluster` plan
- Fix assertions for `TrialPlan`
Resolves #2545
> Handle own cluster subscription release

- components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
`TestKymaDeprovision` logged an error in the `EDP_Deregistration` step during deprovisioning, and it shouldn't have. This was due to different SubAccountID in the instance and the provisioning operation. In addition, the mocked EDPClient was also missing the `MaasConsumerServicePlan`.
- Fix the SubAccountID mismatch
- Add `MaasConsumerServicePlan` to the mocked EDPClient
> Fix Kyma deprovisioning test

- components/kyma-environment-broker/common/runtime/client.go
- components/kyma-environment-broker/common/runtime/model.go
- components/kyma-environment-broker/internal/runtime/handler.go
- components/kyma-environment-broker/internal/storage/dbmodel/instance.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
The `/runtime` endpoint is used to enable better visibility for KCP where OSB API is not sufficient. This PR introduces two changes
1) https://github.com/kyma-project/control-plane/pull/2563/commits/783c01b17c9ac2c7770f308b1c9af5d89d59ae7c - a filter for listing instances that require re-execution for deprovisioning due to some steps not completing.
2) https://github.com/kyma-project/control-plane/pull/2563/commits/a7457b66d1269d1eed24d8d5e78dd319612550b0 - refactor of `only-deleted` introduced in https://github.com/kyma-project/control-plane/pull/2286. After exploring the flags and parameters on both KCP and KEB, I think it will provide better consistency to use `state=deprovisioned` filter instead of the completely independent and own `only-deleted` parameter.
**Related …
> KEB /runtime endpoint deprovision incomplete filter

- resources/kcp/charts/component-reconcilers/charts/rma/templates/rbac.yaml
There was a failure in provisioning due to rma reconciler rbac:     
```
"message": "Runner: failing reconciliation of 'rma' in version '2.11.2' with profile 'Production': helm install xxx-xxxx failed: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource VMProbe \"xxx-xxxxxx\" in namespace \"monitoring-system\": vmprobes.operator.victoriametrics.com \"xxx-xxxxxxx\" is forbidden: User \"system:serviceaccount:xxxxxxxxx\" cannot get resource \"vmprobes\" in API group \"operator.victoriametrics.com\" in the namespace 
```
> Added vmprobes to rma reconciler clusterrole

- components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
- components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
EDP register and deregister requieres that the subaccountID doesn't contain uppercase letters.
- Convert subaccountID to lowercase in the EDP steps during provisioning and deprovisioning
Resolves #2532
> Convert subaccountID to lowercase in EDP steps

- resources/kcp/values.yaml
Missing CloudSql Proxy for Provisioner and Migrator
- Missing CloudSql proxy for provisioner and migrator.
> Missing CloudSql Proxy Param for Provisioner and Migrator

- components/kyma-environment-broker/common/orchestration/dto.go
- components/kyma-environment-broker/internal/orchestration/manager/manager.go
- components/kyma-environment-broker/internal/storage/dbmodel/orchestration_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
If orchestration field `immediate` is persisted as a string value `"true"` in database the request send to "orchestration" endpoint fails on unmarshaling this value to bool of https://github.dev/kyma-project/control-plane/blob/c825f45f79d9d4b1b1fe9f5f9ac54c779e494a1a/components/kyma-environment-broker/internal/storage/dbmodel/orchestration.go#L50. Error example: 
```
while getting orchestrations: json: cannot unmarshal string into Go struct field RetryOperationParameters.retryoperation.immediate of type bool"}
``` 
- Tests that mitigate the orginal problem (see case with `"immediate": "true"`)
- New `stringBoolean` with custom unmarshal that handles bool represented as strings.
> Introduced Bool Type for Incorrect DB Values

- components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
- components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations_test.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
Avs evaluations deprovision has redundant logic to check if evaluations have already been removed. This caused confusion during troubleshooting. The check is already present in the `deleteAvsEvaluation` method. This PR removes redundant logic and adds more unit tests.
- Remove redundant check if avs evaluations already deleted
- Add unit test for removing avs evaluations if they have been removed previously
- Add unit tests for skipping the external avs evaluations removal for Trial and Freemium
Resolves #2534
> Avs evaluations deprovision cleanup

- resources/kcp/charts/component-reconcilers/values.yaml
recent changes to `resources/kcp/charts/component-reconcilers/values.yaml`
deleting
```yaml
serviceMonitor:
enabled: false
scrapeTimeout: 30s
interval: 60s
```
were unintentional and must be reverted.
- ...
- ...
- ...
> Undo the changes done to service monitor.

- components/provisioner/Dockerfile
- components/provisioner/go.mod
- resources/kcp/charts/provisioner/values.yaml
- bumps provisioner golang-runtime to 1.20.3
- switches go version from 1.19 to 1.20 
- updates alpine to 3.17.3
> bumps provisioner golang to 1.20.3 and alpine to 3.17.3

- components/kyma-environment-broker/internal/process/queue.go
- components/kyma-environment-broker/internal/process/staged_manager.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
To help investigating the flow of operations with restarts. When step needs to be retried we restart the whole operation which is not so obvious.
- Additional message when we restart operation in staged_manager
- removed excessive logging for orchestrations (noise)
> Logging for staged manager

- components/kyma-environment-broker/Dockerfile.job
- resources/kcp/values.yaml
Aims to fix:
- CVE-2022-41723
- CVE-2022-41722
- CVE-2022-41724
- CVE-2022-41725
- CVE-2023-24537
- CVE-2023-24532
in kyma-environment-subscription-cleanup-job
- bump golang-runtime from 1.20.2 to 1.20.3
> bump golang-runtime from 1.20.2 to 1.20.3 in keb

- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/charts/kyma-metrics-collector/values.yaml
- resources/kcp/charts/provisioner/values.yaml
- resources/kcp/values.yaml
Since we are moving to the artifact registry, we need to switch from using PR images to images built after merging to the main branch. Since we don't yet have a solution to automate image bumping, we have to create a second PR from now on after merging a PR with changes to bump the image version to the image built after merging the previous PR. To summarise the workflow will look like this:
- A PR with some changes is created and merged to main
- The image is built using post build jobs
- A second PR with bumps is created using the image tag from post build jobs
- Move KEB images to artifact registry
- Move Provisioner images to artifact registry
- Move KMC images to artifact registry
- Move test images to artifact registry
**Related …
> Migrate KEB, provisioner and KMC images to artifact registry

- components/provisioner/go.mod
- components/provisioner/go.sum
- resources/kcp/charts/provisioner/templates/deployment.yaml
- resources/kcp/charts/provisioner/values.yaml
- resources/kcp/values.yaml
Aims to fix vulnerabilities reported by Whitesource in Provisioner
- bumps containerd to 1.6.18
- bumps goland.org/x/net to 0.8.0
> bumps containerd to 1.6.18 and goland.org/x/net to 0.8.0 in provisioner

- components/kyma-environment-broker/Dockerfile.job
- components/kyma-environment-broker/Dockerfile.keb
- tests/e2e/provisioning/Dockerfile
- bump golang builder images to 1.20.4 ver. in dockerfiles.
> Bump golang images to 1.20.4 ver. in KEB and E2E Provisioning test

- resources/kcp/charts/provisioner/values.yaml
- The KCP contains reference `europe-docker.pkg.dev/kyma-project/prod/control-plane/prod/control-plane%2Fprovisioner:v20230508-19cfa22a` where `prod/control-plane` is duplicated. This PR should help in debugging the isue.  
- Switches image to `PR-` version and `dev` directory
- ...
- ...
- https://github.com/kyma-project/control-plane/pull/2733
> reverts to DEV PR in order to see if it will help with url duplication

- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- resources/kcp/charts/provisioner/templates/deployment.yaml
- resources/kcp/charts/provisioner/values.yaml
Change requested by Gardener team:
Updating all related code in open-source Kyma to not use Shoot with basic auth any more, as it's a deprecated field which is getting removed very very soon.
> Stoping using of deprecated field EnableBasicAuthentication from shoot

- tools/reconciler/e2e-test/template-kyma-main.json
Tracing component is deprecated and will be removed in the next Kyma releases.
However, the current `latest` Kyma version, `2.13.1` still contain tests for tracing in the sources.
Prow jobs for the reconciler component that execute tests on the `latest` Kyma fail without `tracing`.
[A PR](https://github.com/kyma-project/control-plane/pull/2708) has been merged that deletes the `tracing` component from reconciler's test configuration.
This PR restores that component to fix the pipelines.
- restore tracing for reconciler tests
https://github.com/kyma-project/kyma/issues/17379
https://github.com/kyma-project/control-plane/pull/2708
> restore tracing for reconciler tests

- components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
- components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
- components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
- components/kyma-environment-broker/internal/process/operation_manager.go
Some steps don't have the error state event in the kcp cli view when errors occur.
- Add error state event for deregister cluster step
- Add error state event for edp deregistration step
- Add error state event for release subscription step
Resolves #2569
> Add missing error state event for deprovisioning steps

- resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
- resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
Couple of manifests in the kcp helm charts were using v1beta1 CronJobs which are no longer available on newer kubernetes installations. Bumped those to use v1.
> Use batch/v1 for CronJobs

- resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
There was a leftover `batch/v1beta1` `CronJob` in the KEB subchar, this PR is fixing that with an update to `batch/v1`
> Fix leftover batch/v1beta1 CronJob

- components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
- Adding the following three labels to each Kyma resource on SKR:
- subaccount-id
- shoot-name: name of the shoot cluster. The shoot name could also be extracted from the skr-domain (some lines below). However, this would require some string splitting and also accessing the resource annotations. I think adding a dedicated field to the labels is cleaner and doesn't introduce any overhead.
- region
CC @ebensom, @a-thaler  
> add more labels to Kyma resource

- components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
Due to an [issue present in Gardener machine-controller-manager](https://github.com/gardener/machine-controller-manager/issues/798) (MCM), Kyma runtimes with a worker group using 3 AZs and maxSurge =1 are configured with the below machinedeployments
<html>
<body>
MachineDeployment | Zone | maxSurge | maxUnavailable
-- | -- | -- | --
worker-z1 | europe-west1-a | 1 | 0
worker-z2 | europe-west1-b | 0 | 0
worker-z3 | europe-west1-b | 0 | 0
</body>
</html>
During a rolling update of the worker groups this leads to nodes in z2 and z3 be drained before ANY new surge nodes being created, which is definitely not what we intended and could cause severe disruptions during maintenance.
This workaround applies one of the (easier) recommendations from the issue to increase the maxSurge …
> Configure maxSurge equal to the number of znoes for enterprise plan runtimes

- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/btp_operator_overrides.go
- components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
- do not prepare overrides for BTP operator if it is not in the additional component list - a case , when BTP operator is installed by LM. It fixes a bug in the update process for LM integration.
> Update without btp operator

- components/kyma-metrics-collector/pkg/edp/consumption_metrics.go
- components/kyma-metrics-collector/pkg/process/process.go
- components/kyma-metrics-collector/pkg/process/process_test.go
- Add instanceID to data sent to edp using kmc
Example Payload published to EDP:
```
{\"runtime_id\":\"52e31334-4819-4f36-9651-8ccd2a29b880\",\"sub_account_id\":\"9ee756cb-6584-4dd7-8c09-84342667f3f3\",\"shoot_name\":\"c-7ea3c78\",\"timestamp\":\"2023-05-22T13:34:16Z\",\"compute\":{\"vm_types\":[{\"name\":\"standard_d2_v3\",\"count\":4}],\"provisioned_cpus\":8,\"provisioned_ram_gb\":32,\"provisioned_volumes\":{\"size_gb_total\":81,\"count\":7,\"size_gb_rounded\":224}},\"networking\":{\"provisioned_vnets\":1,\"provisioned_ips\":3}}
```
- https://github.com/kyma-project/control-plane/issues/2711
> Include shoot info in data sent to edp from KMC

- components/kubeconfig-service/Dockerfile
- resources/oidc-kubeconfig-service/values.yaml
This version bump should fix the following Security vulnerabilities in /components/kubeconfig-service: 
BDSA-2023-0791
BDSA-2023-1067
BDSA-2023-1074
BDSA-2023-1078
BDSA-2023-1165
BDSA-2023-1414
BDSA-2023-1417
BDSA-2023-1422
BDSA-2023-1424
CVE-2022-41722
CVE-2022-41723
CVE-2022-41724
CVE-2022-41725
CVE-2023-24532
CVE-2023-24534
CVE-2023-24536
CVE-2023-24537
CVE-2023-24538
[Protecode MPS security scans dashboard shows few unassigned items. #3964](https://github.tools.sap/kyma/backlog/issues/3964)
> bump go version to 1.20.5 in /components/kubeconfig-service

- components/provisioner/internal/gardener/provisioner.go
- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/infrastructure/azure/infrastructure.go
- resources/kcp/charts/provisioner/values.yaml
Adapt to Provisioner to prevent it from removing NAT `IPAdresses` fields from the Gardener Shoot object by changing the way of handling `EnableNatGateway` struct.
- prevent Provisioner from removing NAT `IPAdresses`fields from the Gardener Shoot object
#2901
> Update the structure of Azure Gardener extensions

- resources/kcp/Chart.yaml
With the latest piper-lib and helm the build fails with:
```
Error: dependency "postgresql" has an invalid version/constraint format: improper constraint: 
```
This PR fixis this by adding the subcharts' version to the main chart's deps.
> Add versions to kcp chart deps

- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
Allows the mothership to skip some components if needed
Relates to https://github.com/kyma-incubator/reconciler/pull/1377
> Make env-vars configurable

- components/provisioner/Dockerfile
Golang builder image from Docker Repo `golang:1.20.6-alpine3.18`
> Update golang builder image for Provisioner to version 1.20.6-alpine3.18

- resources/oidc-kubeconfig-service/values.yaml
Bumps image to `PR-2916`, because previous is not available anymore.
related: https://github.tools.sap/kyma/backlog/issues/4278
> Bump image tag to PR-2916

- components/kyma-environment-broker/internal/avs/client.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/avs/mock_server.go
- update AvS API server response struct,
- fix a bug when reading the response body too many times prior to logging produces EOF message,
- fix mock server response for unit test.
Resolves #2665
> Fix Deprovision_AVS_Evaluations step

- components/provisioner/.gitignore
- adds git ignore for migration files generated by provisioner e2e tests
-
- ...
https://github.com/kyma-project/test-infra/issues/7662
> adds git ignore for migration files generated by provisioner e2e tests

- components/provisioner/e2e_test/test.sh
- checks if `timeout` is installed and gives a MacOs hint if not
- ...
- ...
> adds a check for timeout tool for provisioner e2e test

- components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
- components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
- Retry every 5 secs for 1 minut in case Get_Kubeconfig fails due to inability to create k8sclient (provision + update)
> Retry when unable to create k8sclient for operation

- resources/oidc-kubeconfig-service/values.yaml
The dev images are being phased out, and this continuously breaks kubeconfig-service. Right now the image specified in the chart doesn't exist anymore.
This PR switches the chart to use prod images instead of PR builds, which are retained.
> Use production images for kubeconfig-service

- resources/kcp/charts/component-reconcilers/templates/service-monitor.yaml
- resources/kcp/charts/component-reconcilers/values.yaml
- resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/charts/kyma-metrics-collector/templates/service-monitor.yaml
- resources/kcp/charts/kyma-metrics-collector/templates/service.yaml
- resources/kcp/charts/kyma-metrics-collector/values.yaml
- resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
- resources/kcp/charts/provisioner/templates/service-monitor.yaml
- resources/kcp/charts/provisioner/values.yaml
This PR adds optional generation of `VMServiceScrape` manifests for direct monitoring with victoriametrics. Everything is conditional on two points:
1. `VMServiceScrape` manifests are only generated if the APIVersion is available through helm's `.Capabilities.APIVersions`
2. is explicitly enabled using `vmscrapes.enabled` in the values
> Adds option VMServiceScrape generation

- CODEOWNERS
Add access to talszabi for the following components: 
- kubeconfig-service
- kcp-cli
-
> Adding talszabi to kubeconfig-service and kcp-cli code owners

- resources/oidc-kubeconfig-service/values.yaml
Bumping the kubeconfig-service image version to the latest which merges the recent go deps update opened by dependabot
following PRs will be applied: 
- gomod(deps): bump github.com/smartystreets/goconvey from 1.8.0 to 1.8.1 in /components/kubeconfig-service #2890
- gomod(deps): bump golang.org/x/oauth2 from 0.8.0 to 0.12.0 in /components/kubeconfig-service #3050
- docker(deps): bump golang from 1.20.5-alpine3.18 to 1.21.1-alpine3.18 in /components/kubeconfig-service #3056
> Bumping the image in kubeconfig-service chart to v20230927-3979470d

- components/provisioner/internal/provisioning/graphql_converter_test.go
- components/provisioner/internal/provisioning/input_converter.go
- components/provisioner/internal/provisioning/input_converter_test.go
The value `domains.include` in DNS config should contain only one value with the full shoot domain name.
This is just overriding the value passed by KEB. The final fix must be done on the KEB side since on KEB side the initial DNS providers configuration is created and Provisioner just stores this value. The proposed solution just ignores this value from KEB and use shootDomain as single `domains.include` entry.
After the fix - this PR can be reverted
> Fix for provisioned shoot DNS

- resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
- resources/kcp/charts/mothership-reconciler/templates/virtualservice.yaml
- resources/kcp/charts/provisioner/templates/virtual-service.yaml
- resources/oidc-kubeconfig-service/templates/virutalservice.yaml
We need to have multiple gateways defined in the VirtualServices, this patch adds this functionality:
```
$ helm template --kube-version 1.27.0 --api-versions $(cat $apiver) -f ~/tmp/global-istio-gw.yaml oidc-kubeconfig-service/ | yq 'select(.kind == "VirtualService").spec.gateways'
- kyma-system/kyma-gateway
- mostrum/ridcully
$ helm template --kube-version 1.27.0 --api-versions $(cat $apiver) -f ~/tmp/global-istio-gw.yaml -f ~/tmp/kcp-defvalues.yaml -f ~/tmp/kcp-values.yaml kcp/ | yq 'select(.kind == "VirtualService").spec.gateways'
- kyma-system/kyma-gateway
- mostrum/ridcully
---
- kyma-system/kyma-gateway
- mostrum/ridcully
---
- kyma-system/kyma-gateway
- mostrum/ridcully
```
Also, VirtualGateway apiVersions are updated to v1beta1, as that's the current one with isito.
> Add option for additional gateways

- resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/charts/kyma-metrics-collector/templates/service-monitor.yaml
- resources/kcp/charts/kyma-metrics-collector/values.yaml
- resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
- resources/kcp/charts/provisioner/templates/service-monitor.yaml
- resources/kcp/charts/provisioner/values.yaml
Ensure all ServiceMonitor CRs can be conditionally rendered based on Helm variable. 
This is needed to be able to disable all kcp ServiceMonitoris once the migration from prometheus-operator (Kyma monitoring component) is completed.
> Make all kcp servicemonitors conditional

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- Bump KEB image to include the https://github.com/kyma-project/kyma-environment-broker/pull/111 PR
- Removed unused `internalTesterTags` and `internalTesterTags` fields from `avs-creds` Secret
- W.r.t the aboe PR, remove `gardenerShootNameTagClassId` helm configuration
> KEB: don't provide GardenerShootName AvS tag

- components/provisioner/internal/runtime/configurator.go
- provisioner will now create `istio-system` namespace to allow the planned istio removal
- Please see the internal issue with number `4750`
/area control-plane
> provisioner will now create istio-system namespace

- tools/cli/go.mod
From version `v0.0.0-20230222072933-f72a783494d6` to version` v0.0.0-20220427105742-42ddda791e49`
After merging https://github.com/kyma-project/control-plane/pull/3186 and https://github.com/kyma-project/control-plane/pull/3187
> Kcp-cli tool Update provisioner dependency after new release of provisioner

- resources/kcp/charts/kyma-metrics-collector/templates/_helpers.tpl
- resources/kcp/values.yaml
Subscription Cleanup Job (SCJ) has been moved outside of `control-plane` directory. This PR updates paths to allow usage of no dir value for SCJ but leaving other places unchanged.
- set dir to `control-plane` for all components,
- removed `control-plane` from `containerRegistry` property,
- left dir empty for SCJ.
> Corrected Image Path for Subscription Cleanup Job

- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- [WiP] sets EnableStaticTokenKubeconfig to false during 1.27.0+ upgradeShoots operations
- ...
- ...
- https://github.com/kyma-project/control-plane/issues/3240
> sets EnableStaticTokenKubeconfig to false during 1.27.0+ upgrades

- resources/kcp/charts/mothership-reconciler/values.yaml
Ignore the reconciliation of CP component when CP-CRD exists on SKR.
> Ignore Connectivity Proxy when CRD exists

- components/provisioner/internal/api/resolver_integration_test.go
- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/provisioning/input_converter_test.go
- components/provisioner/pkg/gqlschema/models_gen.go
- components/provisioner/pkg/gqlschema/schema.graphql
- components/provisioner/pkg/gqlschema/schema_gen.go
From now Provisioner is responsible for adding (if KEB does not provide) these parameters during provision of the OpenStack cluster:
- `FloatingPoolName`
- `ExposureClassName`
- GraphQL `provisionRuntime` mutation now does not require `floatingPoolName` to be provided
> The Provisioner adds OpenStack parameters

- components/kyma-metrics-collector/options/options.go
- resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml
- resources/kcp/charts/kyma-metrics-collector/values.yaml
Clean-up Gardener secret references as it is not needed anymore. None of the metrics are retrieved from the gardener anymore.
#3312
> Clean-up gardener secret configs references

- resources/kcp/values.yaml
Bump KMC latest image for removing gardener dependency
Prow [build job](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-metrics-collector-build/1758121976037117952)
#3353
> Bump KMC image

- components/provisioner/Dockerfile
- components/provisioner/go.mod
- tests/e2e/provisioning/Dockerfile
- tests/provisioner-tests/Dockerfile
- bumps golang to 1.22.0 and alpine to 3.19.1 in provisioner - hoping it will resolve some busybox vulnerabilities. 
- image bump will follow
- ...
> bumps golang to 1.22.0 and alpine to 3.19.1 in provisioner

- components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
- components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
One of installed Kyma componenets "compass-runtime-agent" requires `istio-system` namespace to be correctly initialised. This namespace was created by the Provisioner as part of Runtime configuration step where Provisioner created secrets on the cluster that allowed to establish connection between compass-runtime-agent and Compass.
New version of the provisioner delivered by [this PR ](https://github.com/kyma-project/control-plane/pull/3399)makes Compass Registration process optional, controlled by env variables.
There was a bug in the code where after disabling Compass Registration - The Provisioner has stopped creating `istio-system` namespace as well. 
This PR is suppose to mitigate this problem by moving namespace creation code into "create operator bindings" step
> Provisioner creates "istio-system" namespace as part of "create operator bindings" step

- tests/e2e/provisioning/pkg/client/runtime/runtime_client.go
Using the director to fetch the runtimeID and then using it to fetch the kubeconfig is no longer possible.
- Use instanceID for fetching kubeconfig
> Use instanceID for fetching kubeconfig in e2e tests

- .github/workflows/provisioner-e2e-test.yaml
- components/provisioner/Makefile
- components/provisioner/README.md
- components/provisioner/e2e_test/main_test.go
- components/provisioner/e2e_test/requests/provision.graphql
- components/provisioner/internal/api/resolver_integration_with_gardener_test.go
- components/provisioner/internal/persistence/database/schema_initializer_test.go
- components/provisioner/internal/persistence/testutils/database.go
- Remove multiple layers of docker from tests
- Modify workflow to use `actions/setup-go@v5`
- Bump buildpack
- Remove special test-env handling from database code
#3287
> Refactor provisioner tests env

- components/provisioner/cmd/init.go
- components/provisioner/cmd/main.go
- components/provisioner/internal/api/resolver_integration_with_gardener_test.go
- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- components/provisioner/internal/model/infrastructure.go
- components/provisioner/internal/model/infrastructure/aws/worker.go
- components/provisioner/internal/provisioning/input_converter.go
- components/provisioner/internal/provisioning/input_converter_test.go
- components/provisioner/internal/provisioning/service_test.go
- components/provisioner/pkg/gqlschema/models_gen.go
- components/provisioner/pkg/gqlschema/schema.graphql
- components/provisioner/pkg/gqlschema/schema_gen.go
- Add new Gardener configuration `DefaultEnableIMDSv2` as a feature flag to enabled IMDSv2 support during provisioning and shoot upgrade
- Add new fields in AWSProviderConfig and AWSProviderConfigInput GQL schema
- In input converter, support using the default AWS IMDVSv2 configuration if it was provided as input
- Enhance `AWSGardenerConfig.ExtendShootConfig()` to add the needed providerConfig to the single worker if `enableIMDSv2` is true
- Enhance `AWSGardenerConfig.EditShootConfig()` to check if the needed providerConfig is present in the shoot, and ensure it is configured with in the desired state, in case the `enableIMDSv2` is true
https://github.tools.sap/kyma/backlog/issues/5218
> provisioner: add support for configuring AWS IMDSv2 access method

- resources/kcp/charts/provisioner/templates/deployment.yaml
- resources/kcp/charts/provisioner/values.yaml
- Bump provisioner in kcp chart to v20240429-ea75326a to include https://github.com/kyma-project/control-plane/pull/3429
- Define `defaultEnableIMDSv2` Helm value
https://github.tools.sap/kyma/backlog/issues/5218
> Bump provisioner in kcp chart to v20240429-ea75326a

- components/provisioner/cmd/main.go
- components/provisioner/internal/api/resolver_integration_test.go
- components/provisioner/internal/api/resolver_integration_with_gardener_test.go
- components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
- components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
The L2 and L3 operator bindings were for a legacy (OIDC based) approach to authorize SAP operator access to SKRs, but are not needed any more. 
After this PR is merged, I plan to raise another PR to remove related code from kcp chart.
https://github.tools.sap/kyma/backlog/issues/5553
> Remove obsolete L2/L3 operator bindings from provisioner

- components/provisioner/pkg/gqlschema/models_gen.go
- components/provisioner/pkg/gqlschema/schema.graphql
- components/provisioner/pkg/gqlschema/schema_gen.go
- Put `shootAndSeedSameRegion` field to GardenerConfigInput instead of GardenerConfig.
https://github.com/kyma-project/kyma/issues/18182
> Correction for #344 - shootAndSeedSameRegion in GardenerConfigInput

- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- components/provisioner/internal/util/testkit/shoot.go
**What this PR does** :  Setting the parameter `shoot.Spec.Provider.WorkersSettings.SSHAccess` to false for all provisioned and updated Gardener Shoots resources to block SSH traffic.
**Related Issue**: someGHRepo/kyma/backlog/issues/5775
**Why this PR is created**: Requested by SRE to address SSH security vulnerability. Check the linked issue for more details.
Includes all required unit tests adjustments.
> fix Blocking SSH access for all provisioned and upgraded Kyma runtimes

- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
Enabling OIDC extension for Provisioned shoots by adding following item to list of shoot extensions
```
extensions:
- type: shoot-oidc-service  #this line enables OIDC extension
disabled: false
```
This change will affect only new clusters as specified in https://github.com/kyma-project/control-plane/issues/3466
Extension section from test shoot provisioned on AWS
```
extensions:
- type: shoot-dns-service
providerConfig:
apiVersion: some-version
dnsProviderReplication:
enabled: true
kind: DNSConfig
providers:
- domains:
include:
- some-domain
secretName: some-name
type: some-type
syncProvidersFromShootSpecDNS: true
- type: shoot-cert-service
providerConfig:
apiVersion: some-api-version
shootIssuers:
enabled: true
kind: CertConfig
- type: shoot-networking-filter
disabled: true
- type: …
```
> Provisioner - enable oidc extension by default for newly provisioned clusters
