- installation/resources/tiller.yaml
- installation/scripts/install-tiller.sh
- Restore Tiller script
Even though Installer is migrated to Helm 3, because of its initContainers Tiller is still needed. That's why for now we're bringing back the script.
> Restore Tiller script

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/rbac.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- Add ability to disable Provisioning E2E tests
> Add ability to disable Provisioning E2E tests

- installation/resources/COMPASS_VERSION
> Bump Compass version

- installation/resources/COMPASS_VERSION
> Bump Compass

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
- resources/kcp/values.yaml
- Remove instance from the storage when deprovisioning initialisation step succeeded
> KEB: remove instances when deprovisioning is finished

- components/kyma-environment-broker/README.md
- components/kyma-environment-broker/internal/director/config.go
- components/kyma-environment-broker/internal/director/oauth/client_test.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
- components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
- docs/kyma-environment-broker/03-06-runtime-overrides.md
- resources/kcp/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
- resources/kcp/values.yaml
- tests/e2e/provisioning/README.md
- tests/e2e/provisioning/internal/director/config.go
- tests/e2e/provisioning/internal/director/oauth/client_test.go
- tests/e2e/provisioning/test/test_suite.go
- Change hardcoded occurrences of compass-system namespace
Follow-up issue regarding parameterization of these values: https://github.com/kyma-project/control-plane/issues/35
> Change hardcoded occurrences of compass-system namespace in KEB

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
> Fix KEB starting

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/httputil/client.go
- components/kyma-environment-broker/internal/ias/bundle.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- Enable TLS renegotiation for IAS HTTP client
> Enable TLS renegotiation for IAS HTTP client

- CODEOWNERS
- resources/oidc-kubeconfig-service/values.yaml
New fsnotify library image bump: #43 
- oidc-kubeconfig-service image bump
See also: #43
> oidc-kubeconfig-service image bump

- docs/kyma-environment-broker/02-02-broker-endpoints.md
> Fix link for OSB API

- resources/oidc-kubeconfig-service/templates/virutalservice.yaml
- Add `corsPolicy` to virtual service of kubeconfig service
[Console/Compass](https://github.com/kyma-project/console/pull/1894)
> Add corsPolicy for kc service

- installation/scripts/generate-installer-artifacts.sh
- Use the artifacts bucket instead of the github release page.
https://github.com/kyma-project/kyma/issues/8360
> Change the URL from github to gcs bucket

- docs/internal/investigations/dapr-poc-scenario.md
- docs/internal/investigations/remote-kyma-runtime-configuration.md
- Add Dapr sidecar configuration investigations
#11
> Add Dapr sidecar configuration investigations

- OWNERS_ALIASES
> remove sjanota from codeowners

- components/provisioner/internal/runtime/configuration_test.go
- components/provisioner/internal/runtime/configurator.go
- resources/kcp/values.yaml
- Config Map creation removed
kyma-incubator/compass#1279
> Remove Config Map creation after runtime is provisioned

- installation/resources/COMPASS_VERSION
- installation/resources/KYMA_VERSION
> Bump kyma (kyma-installer fixes, updates to ory, kiali, jaeger)

- installation/resources/KYMA_VERSION
Bump kyma to include https://github.com/kyma-project/kyma/pull/9075
> Bump kyma to include kyma-installer memory limit change

- components/provisioner/Dockerfile
- resources/kcp/values.yaml
- Cleanup Provisioner Dockerfile
> Cleanup Provisioner Dockerfile

- README.md
- Describe Control Plane dependencies
- Update prerequisites
> Describe Control Plane dependencies

- components/provisioner/go.mod
- resources/kcp/values.yaml
Bump images of:
* provisioner 
* schema_migrator
* provisioner-tests
> Bump images of control-plane after merging #28 Add UpgradeShoot() mutation

- components/kyma-environment-broker/internal/broker/instance_deprovision.go
- components/kyma-environment-broker/internal/broker/instance_deprovision_test.go
- Fixed deprovisioning retries
> Fix deprovisioning retries

- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/storage/dbsession/factory.go
- components/kyma-environment-broker/internal/storage/dbsession/read.go
- components/kyma-environment-broker/internal/storage/driver/memory/instance.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- add a method to the storage which counts instances per global account
- add a check before provisioning
Related: https://github.tools.sap/kyma/backlog/issues/488
> Keb one trial per globalaccount

- resources/kcp/values.yaml
> Bump KEB image

- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/automock/provision_input_creator.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
- components/kyma-environment-broker/internal/process/provisioning/input/builder.go
- components/kyma-environment-broker/internal/process/provisioning/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/lms_cert_step_test.go
- add EnableComponent method to the inputCreator to allow any step to enable optional component
> Keb step enables optionalcomponent

- components/kyma-environment-broker/internal/process/provisioning/lms_cert_step_test.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
- use default Kyma settings for Trial
> Default Kyma settings for Trial

- installation/resources/COMPASS_VERSION
- Bump compass version
https://github.com/kyma-project/control-plane/pull/93
https://github.com/kyma-incubator/compass/pull/1508
https://sap-ti.slack.com/archives/CQF0V9075/p1595923351129100
> bump compass version, increase memory limit for compass-installer

- components/kyma-environment-broker/internal/broker/broker.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/plans_validator.go
- components/kyma-environment-broker/internal/broker/plans_validator_test.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/input/builder.go
- components/kyma-environment-broker/internal/process/provisioning/input/builder_test.go
- components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
- components/kyma-environment-broker/internal/process/provisioning/resolve_creds_test.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
- components/kyma-environment-broker/internal/process/provisioning/skip_for_trial_step_test.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- resources/kcp/values.yaml
> Add AzureTrial plan

- components/kyma-environment-broker/cmd/environmentscleanup/main.go
- components/kyma-environment-broker/internal/environmentscleanup/service.go
- components/kyma-environment-broker/internal/environmentscleanup/service_test.go
- resources/kcp/values.yaml
- Fix panic when no `runtime-id` label on shoot
> Fix panic on Environments Cleanup job

- docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
- Change step AVS owner in KEB documentation
> Change step AVS owner in KEB documentation

- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
- components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
- KEB: use "lite" settings for SKR Trial
> KEB: Use Lite settings for Trial plan

- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/charts/metris/values.yaml
- resources/kcp/charts/provisioner/values.yaml
Configure image pull policy to "always"
> Set image pull policy to always

- resources/kcp/values.yaml
- tests/provisioner-tests/Gopkg.lock
- tests/provisioner-tests/Gopkg.toml
- Remove the fork from test dependencies
> Remove the fork from test dependencies

- docs/kyma-environment-broker/03-01-service-description.md
- resources/kcp/values.yaml
> Bump KEB version

- docs/internal/README.md
> Quick docu fix

- docs/internal/investigations/runtime-governor-poc/README.md
- Fix broken links in internal docs
> Fix broken links

- docs/internal/investigations/runtime-governor-poc/README.md
- docs/internal/investigations/runtime-governor-poc/governor/chart/templates/configmap.yaml
- docs/internal/investigations/runtime-governor-poc/governor/chart/values.yaml
- Fix commands in runtime governor POC
> Fix commands in runtime governor POC

- components/kyma-environment-broker/internal/process/provisioning/natss_step.go
- components/kyma-environment-broker/internal/process/provisioning/natss_step_test.go
- components/kyma-environment-broker/internal/runtime/components/components.go
- components/kyma-environment-broker/internal/runtime/disabled_components.go
- resources/kcp/values.yaml
- Fix Nats streaming name in KEB
> Fix Nats name in KEB

- components/kyma-environment-broker/internal/runtime/provider.go
- components/kyma-environment-broker/internal/runtime/provider_test.go
- resources/kcp/values.yaml
- tests/e2e/provisioning/internal/provisioner/components_provider.go
- Change Installer URL from GitHub to KEB
> Fix components download URLs in KEB

- CODEOWNERS
- Added new members to Gophers team's components
- Added all developers as CODEOWNERS of `scripts` directory
- ...
> Modify CODEOWNERS

- docs/kyma-environment-broker/03-09-subaccount-cleanup-cronjob.md
- Add documentation to delete orphan instances functionality
**Related PR**
[PR](https://github.com/kyma-project/control-plane/pull/131)
> Add documentation to delete orphan instances functionality

- components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler.go
- components/kyma-environment-broker/internal/storage/dbsession/factory.go
- components/kyma-environment-broker/internal/storage/dbsession/read.go
- components/kyma-environment-broker/internal/storage/driver/memory/orchestration.go
- components/kyma-environment-broker/internal/storage/driver/postsql/orchestration.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- Implemented orchestration list endpoint
> Implement orchestration list endpoint

- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- resources/kcp/values.yaml
> Update trial defaults

- resources/kcp/charts/kyma-environment-broker/templates/api-rule.yaml
- resources/kcp/charts/kyma-environment-broker/templates/oauth-client.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- Implement oauth rules for upgrade using ORY
> Implement oauth rules for upgrade

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/orchestration/dto.go
- components/kyma-environment-broker/internal/orchestration/handlers/converter.go
- components/kyma-environment-broker/internal/orchestration/handlers/converter_test.go
- components/kyma-environment-broker/internal/orchestration/handlers/handler.go
- components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager_test.go
- resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
- Implement dry run mode for upgrade
- Fixed some issues in orchestration implemetation
You need to specify the `dry` parameter in the request body to `true` in the orchestration call to run upgrade in dry run mode 
> Implement dry run mode for upgrade

- components/kyma-environment-broker/internal/process/provisioning/lms_cert_step.go
- increase LMS cert timeout to 30 min
Related: https://github.tools.sap/kyma/backlog/issues/722
> KEB: increase LMS cert timeout

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
Roll KEB deployment when additionalRuntimeComponents config changes
> Roll KEB deployment when additionalRuntimeComponents config changes

- resources/kcp/values.yaml
- Bump migrator to support Orchestrations
> Bump migrator to support Orchestrations

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/README.md
- components/kyma-environment-broker/internal/process/provisioning/input/builder.go
- components/kyma-environment-broker/internal/process/provisioning/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
- components/kyma-environment-broker/internal/provisioner/client_test.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- make MachineImage and MachineImageVersion gardener params configurable
RElated: https://github.tools.sap/kyma/backlog/issues/716
> Keb gardener machine params

- components/kyma-environment-broker/internal/process/provisioning/input/input.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- docs/kyma-environment-broker/03-01-service-description.md
- resources/kcp/values.yaml
- KEB must not configure multiple zones as a default setting
Related: https://github.tools.sap/kyma/backlog/issues/725
> KEB does not configure zones for SKRs

- components/provisioner/internal/installation/release/provider.go
- components/provisioner/internal/installation/release/provider_test.go
- components/provisioner/internal/installation/release/repository.go
- resources/kcp/values.yaml
- tests/provisioner-tests/test/testkit/inputs.go
- Fix possible race condition when downloading artifacts
> Fix race when downloading artifacts

- components/kyma-environment-broker/README.md
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/automock/provision_input_creator.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
- components/kyma-environment-broker/internal/process/provisioning/input/builder.go
- components/kyma-environment-broker/internal/process/provisioning/input/builder_test.go
- components/kyma-environment-broker/internal/process/provisioning/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/input/test/regions.yaml
- components/kyma-environment-broker/internal/process/provisioning/lms_cert_step_test.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider_test.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider_test.go
- components/kyma-environment-broker/internal/provider/region_mapping.go
- components/kyma-environment-broker/internal/provider/region_mapping_test.go
- components/kyma-environment-broker/internal/provider/test/regions.yaml
- docs/kyma-environment-broker/03-01-service-description.md
- resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- adds a possibility to configure a mapping between platform region and default provider region
for trial plan
> Keb region mapping for trial

- components/provisioner/Dockerfile
- resources/kcp/values.yaml
- Dockerfiles refer to images in GCR
> Use images from GCR in Dockerfiles

- resources/kcp/charts/metris/templates/service.yaml
- fixing metris service port in chart template
> fixing metric port

- resources/kcp/values.yaml
- dev versions for Provisioner and Provisioner Tests
https://github.com/kyma-project/control-plane/pull/168
> Bump Provisioner and Provisioner Tests image

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/provisioner/client.go
- components/kyma-environment-broker/internal/provisioner/client_test.go
- components/kyma-environment-broker/internal/third_party/machinebox/graphql/LICENSE
- components/kyma-environment-broker/internal/third_party/machinebox/graphql/README.md
- components/kyma-environment-broker/internal/third_party/machinebox/graphql/graphql.go
- components/kyma-environment-broker/internal/third_party/machinebox/graphql/graphql_json_test.go
- components/kyma-environment-broker/internal/third_party/machinebox/graphql/graphql_multipart_test.go
- resources/kcp/values.yaml
- KEB parses the error code returned from the Provisioner and do not performs retries if the error is permanent.
> Keb fails fast

- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- docs/kyma-environment-broker/03-01-service-description.md
- resources/kcp/values.yaml
- Enable zones
- Use one zone by default
> Enable zones and use one zone by default

- components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler.go
- Enable bulk orchestration requests
- Resolved TODOs
> Enable bulk orchestration requests

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- components/kyma-environment-broker/internal/storage/dbsession/factory.go
- components/kyma-environment-broker/internal/storage/dbsession/read.go
- components/kyma-environment-broker/internal/storage/driver/memory/orchestration.go
- components/kyma-environment-broker/internal/storage/driver/postsql/orchestration.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/values.yaml
- Reprocess orchestrations on start
- Add waiter to orchestration manager
> Reprocess orchestration on start

- components/kyma-environment-broker/internal/runtime/components/components.go
- components/kyma-environment-broker/internal/runtime/disabled_components.go
- resources/kcp/values.yaml
- Disable AvS bridge for trial plan
> Disable AvS bridge for trial plan

- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- resources/kcp/values.yaml
- fix overriding kyma version per global account
> KEB: fix kyma version per global account

- resources/kcp/values.yaml
- tests/e2e/provisioning/Gopkg.lock
- tests/e2e/provisioning/Gopkg.toml
- Align dependecies list with latest master version for `control-plane` repository after merging #204 
[#1303](https://github.com/kyma-incubator/compass/issues/1303)
> Align e2e tests dep's dependencies

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
- components/kyma-environment-broker/internal/storage/dbsession/dbmodel/runtime_state.go
- components/kyma-environment-broker/internal/storage/dbsession/factory.go
- components/kyma-environment-broker/internal/storage/dbsession/read.go
- components/kyma-environment-broker/internal/storage/dbsession/write.go
- components/kyma-environment-broker/internal/storage/driver/memory/runtime_state.go
- components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/postsql/init.go
- components/kyma-environment-broker/internal/storage/storage.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- components/kyma-environment-broker/internal/storage/tests_utils.go
- components/schema-migrator/migrations/kyma-environment-broker/202009171000_add_runtime_states.down.sql
- components/schema-migrator/migrations/kyma-environment-broker/202009171000_add_runtime_states.up.sql
- resources/kcp/values.yaml
- Implemented storage for RuntimeStates
> Implement RuntimeState storage

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
- SingleStats grafana panel migrated to Stat
> Migrate KEB SingleStat grafana panels to Stat

- components/kyma-environment-broker/README.md
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/lms/client.go
- components/kyma-environment-broker/internal/process/provisioning/lms_activation_step.go
- components/kyma-environment-broker/internal/process/provisioning/lms_activation_step_test.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- Enable LMS for specified global accounts
> Enable LMS for specified global accounts

- resources/kcp/templates/registration-job.yaml
- resources/kcp/values.yaml
No compass no more. Bye compass 👋
> Make compass registration job optional

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/common/pagination/pagination.go
- components/kyma-environment-broker/internal/runtime/handler.go
- components/kyma-environment-broker/internal/runtime/handler_test.go
- components/kyma-environment-broker/internal/runtime/model.go
- components/kyma-environment-broker/internal/storage/dbsession/factory.go
- components/kyma-environment-broker/internal/storage/dbsession/read.go
- components/kyma-environment-broker/internal/storage/driver/memory/instance.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
- resources/kcp/values.yaml
- Change Runtime pagination to page and limit
#180
> Change Runtime pagination to page and limit

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
> Fix KEB dashboard

- resources/kcp/values.yaml
> Bump schema migrator

- components/provisioner/go.mod
- components/provisioner/go.sum
- upgrade `etcd` version in KCP Provisioner
> Upgrade 'etcd' in Provisioner

- components/kyma-environment-broker/internal/cis/client_ver_1.go
- components/kyma-environment-broker/internal/cis/client_ver_1_test.go
- components/kyma-environment-broker/internal/cis/model.go
- resources/kcp/values.yaml
CIS in version 1 has changed response json body, this PR adapt CIS client in ver 1 to the new response format.
> Adapt CIS client ver1 to the new response format

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/orchestration/resolver.go
- components/kyma-environment-broker/internal/orchestration/resolver_test.go
- Extended runtime resolver with a planName selector
> Extend runtime resolver with planName

- resources/oidc-kubeconfig-service/templates/deployment.yaml
- resources/oidc-kubeconfig-service/values.yaml
> Make OIDC issuer configurable

- components/kyma-environment-broker/internal/process/deprovisioning/manager.go
- components/kyma-environment-broker/internal/process/deprovisioning/manager_test.go
- components/kyma-environment-broker/internal/process/provisioning/manager.go
- Added `planID` to deprovision operation log
> Add PlanID to deprovision operation logs

- components/kyma-environment-broker/README.md
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
- resources/kcp/values.yaml
- tests/e2e/provisioning/Gopkg.lock
- tests/e2e/provisioning/Gopkg.toml
- tests/e2e/provisioning/README.md
- tests/e2e/provisioning/test/test_suite.go
- Bumped `control-plane` dependency to latest version
- Updated director client usage in e2e provisioning tests
#217 
[#1228](https://github.com/kyma-incubator/compass/issues/1228)
> Update director client in e2e tests

- components/kyma-environment-broker/internal/avs/client.go
- resources/kcp/values.yaml
- Remove token refreshing functionality from AvS client due to not support refresh token functionality by UAA
> Remove token refreshing functionality from AvS client

- installation/resources/COMPASS_VERSION
- Contains the fix for the connector certificate revocation flow
> Fixes connector certificate revocation

- components/kyma-environment-broker/internal/broker/instance_deprovision.go
- components/kyma-environment-broker/internal/broker/instance_deprovision_test.go
- components/kyma-environment-broker/internal/process/provisioning/manager.go
- components/kyma-environment-broker/internal/process/provisioning/manager_test.go
- resources/kcp/values.yaml
- Added `planID` field to Provisioning manager logs and to Deprovision endpoint logs
> Add planID field to KEB logs

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/cmd/cli/skr/kubeconfig.go
- components/kyma-environment-broker/cmd/cli/skr/options.go
Implement `skr kubeconfig` command.
Resolves #238
> SKR CLI: kubeconfig command

- components/kyma-environment-broker/internal/model.go
- docs/kyma-environment-broker/03-10-orchestration.md
- docs/kyma-environment-broker/08-05-orchestrate-kyma-upgrade.md
- docs/kyma-environment-broker/08-06-orchestration-status.md
- Adjusted documentation after orchestration changes
> Adjust documentation after orchestration changes

- components/provisioner/internal/gardener/shoot_reconciler.go
- resources/kcp/values.yaml
- Audit log tenant key is no longer strictly related to seed name
> New mechanism for extracting audit log tenant

- .github/stale.yml
We have noticed a low number of stale issues in our organizations, and it seems that we do not have the `stale.yml` added to some of our repos. We have to adjust repos to follow our [guidelines](https://kyma-project.io/community/governance#issues-workflow-issues-workflow-stale-issues) and add the `.github/stale.yml` to the repos. For reference, see [this](https://sap-ti.slack.com/archives/C0176RK3ECT/p1603352325430200) discussion.
- Add stalebot to the `control-plane` repo
> Add stalebot to the control-plane repo

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- resources/kcp/values.yaml
- bump Azure sdk and azure go-autorest
> Keb bump azure sdk

- components/kyma-environment-broker/internal/orchestration/strategy_parallel.go
- resources/kcp/values.yaml
> Fix upgrade queue in KEB

- components/kyma-environment-broker/internal/metrics/operation_result.go
- components/kyma-environment-broker/internal/metrics/step_result.go
- Extend metrics labels in KEB
> Extend metrics labels in KEB

- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- components/provisioner/internal/provisioning/input_converter.go
- components/provisioner/internal/util/testkit/worker.go
- components/provisioner/pkg/gqlschema/models_gen.go
- components/provisioner/pkg/gqlschema/schema.graphql
- components/provisioner/pkg/gqlschema/schema_gen.go
- docs/provisioner/08-06-upgrading-shoots.md
- resources/kcp/values.yaml
- Added machineImage and machineImageVersion fields to upgrade mutation
- Update example upgrade call in docs
https://github.com/kyma-project/control-plane/issues/247
> Allow to change machine image and version in upgrade mutation

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/event/pubsub.go
- components/kyma-environment-broker/internal/event/pubsub_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/manager_test.go
- components/kyma-environment-broker/internal/process/provisioning/manager_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/manager_test.go
- resources/kcp/values.yaml
- Initialize log property in PubSub struct
> Initialize log property in PubSub struct

- resources/kcp/charts/kyma-environment-broker/templates/policy.yaml
- Add missing authorization for /oauth, /info/runtimes
- Add authorization needed by /orchestrations and /upgrade
> Add Istio authorization for all KEB endpoints

- resources/kcp/values.yaml
To implement `Monitoring and Alerting for Metris component in MPS` (see[ issue 620](https://github.tools.sap/kyma/backlog/issues/620) )
> bump metris version to PR-63

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
implement for [task 740 ](https://github.tools.sap/kyma/backlog/issues/740) -`Report in KCP Grafana about provisioning/deprovisioning quality`
> add graph/gauges for provisioning/deprovisioning quality task

- components/provisioner/internal/gardener/shoot_reconciler.go
- resources/kcp/values.yaml
- Shoot controller will now search for seed specific audit log tenant before checking generic one
> Add possibility to pass seed specific audit log tenant

- components/kyma-environment-broker/cmd/cli/command/kubeconfig.go
- components/kyma-environment-broker/cmd/cli/command/login.go
- components/kyma-environment-broker/cmd/cli/command/options.go
- components/kyma-environment-broker/cmd/cli/command/orchestration.go
- components/kyma-environment-broker/cmd/cli/command/runtime.go
- components/kyma-environment-broker/cmd/cli/command/upgrade.go
- components/kyma-environment-broker/cmd/cli/command/upgrade_kyma.go
- components/kyma-environment-broker/common/orchestration/client.go
- components/kyma-environment-broker/common/orchestration/client_test.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- docs/cli/02-01-usage.md
- docs/cli/commands/kcp_orchestrations.md
- docs/cli/commands/kcp_taskrun.md
- docs/cli/commands/kcp_upgrade_kyma.md
- docs/kyma-environment-broker/03-05-authorization.md
- docs/kyma-environment-broker/03-10-orchestration.md
- docs/kyma-environment-broker/08-05-orchestrate-kyma-upgrade.md
- docs/kyma-environment-broker/08-06-orchestration-status.md
- resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
- resources/kcp/charts/kyma-environment-broker/templates/policy.yaml
- resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
CLI: orchestration commands
- Changed auth model of KEB `/orchestrations` and `/upgrade` endpoints to be based on OIDC JWT verification
- Implemented `kcp orchestrations` and `kcp upgrade kyma` commands
- Fixed immediate and maintenance windows schedules of upgrade operations
Resolves #239 
Resolves #240
> CLI: orchestration commands

- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- resources/kcp/values.yaml
- when provider was not set in the provisioning parameters - the AzureTrial is not initialized and the default region was set which makes a problem
> Fix Trial region mapping

- components/provisioner/internal/gardener/provisioner.go
`confirmation.garden.sapcloud.io` is deprecated with https://github.com/gardener/gardener/pull/1833 and will be removed in a future release of gardener/gardener.
> Do not use the deprecated confirmation annotation

- components/kyma-environment-broker/Gopkg.lock
- resources/kcp/values.yaml
> Upgrade apimachinery in KEB

- tests/e2e/provisioning/Gopkg.lock
- Upgrade apimachinery in e2e test
> Upgrade apimachinery in e2e test

- docs/kyma-environment-broker/03-06-runtime-overrides.md
- Update doc for runtime overrides in KEB
See also #231
> Update doc for runtime overrides in KEB

- docs/README.md
- docs/kyma-environment-broker/03-03-runtime-operations.md
Some of the KCP docs are updated. First, as Mateusz Szostok left the company, he is no longer the owner of the provisioning step in KEB. The ownership belongs to the whole Team Gopher now. Second, there is no mention of KCP CLI docs in the main docs README.
- Remove mszostok from the step owner
- Update the main docs README with KCP CLI
> Update the KCP docs

- components/kyma-environment-broker/internal/provisioner/client.go
- resources/kcp/values.yaml
- Increase timeout for HTTP client used in Provisioner client
> Increase timeout for http client used in Provisioner client

- components/kyma-environment-broker/internal/process/input/builder.go
- resources/kcp/values.yaml
- Fix SKR components list for GA
> Fix SKR components list for GA

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- resources/kcp/values.yaml
- the initialisation step was saving the operation every time which bumps the update timestamp even if there was no any changes.
> KEB saves kyma ersion in operation only once

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- resources/kcp/values.yaml
Kyma upgrade operations are not executed by orchestration strategy after KEB restart.
> Resume upgrade kyma operations after restart

- components/metris/internal/gardener/handlers.go
- components/metris/internal/gardener/types.go
- components/metris/internal/provider/azure/azure.go
- components/metris/internal/provider/azure/instance.go
- fix issue with trial clusters not reporting metrics because they have no event hub resource groups.
> fixing issue with trial cluster

- resources/kcp/values.yaml
Bump metris version to include fix (#328 ) for trial runtimes.
> Bump metris version to include fix for trial runtimes

- resources/kcp/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
- all overrides must be in config repo, not in KEB chart
> KEB chart without overrides for SKRs

- components/kyma-environment-broker/internal/avs/client.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/avs/external_eval_assistant.go
- resources/kcp/values.yaml
- Add log to AvS post step in a temporary fail situation
- Increase timeout for AvS post step
> Fix AvS post action behavior

- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- resources/kcp/values.yaml
- Add random suffix to trial runtimes
> Add random suffix to trial runtimes

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider_test.go
- components/kyma-environment-broker/internal/provider/common.go
- resources/kcp/values.yaml
- Generate a random azure zone
> Generate a random azure zone

- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
- Update postgresql-client binary
> Updates dependencies in schema-migrator

- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- resources/kcp/values.yaml
- Add random name suffix to all plans
> Add random name suffix to all plans

- components/kyma-environment-broker/internal/process/input/input.go
- resources/kcp/values.yaml
- Shorten the random suffix in runtime names
> Shorten the random suffix in runtime names

- tools/cli/pkg/credential/manager.go
Fix credential manager crash after package upgrade
> Fix credential manager crash after package upgrade

- installation/cmd/run.sh
- `latest-published` source flag will no longer exist for the CLI. So, its usage is replaced with the new `master` source flag
kyma-project/cli#501
> Replace latest-published source flag with master source flag

- components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
- components/kyma-environment-broker/internal/process/provisioning/audit_log_step_test.go
-Add filters to fluentbit so that non audit data is skipped
> Add further filters to the fluentbit to filter out non audit data

- resources/kcp/values.yaml
> Bump provisioner

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
- components/kyma-environment-broker/internal/process/provisioning/sm_overrides.go
- components/kyma-environment-broker/internal/process/provisioning/sm_overrides_test.go
- components/kyma-environment-broker/internal/process/provisioning/uaa_step.go
- components/kyma-environment-broker/internal/servicemanager/client.go
- components/kyma-environment-broker/internal/servicemanager/client_int_test.go
- components/kyma-environment-broker/internal/servicemanager/client_test.go
- components/kyma-environment-broker/internal/servicemanager/config.go
- components/kyma-environment-broker/internal/servicemanager/factory.go
- components/kyma-environment-broker/internal/servicemanager/types.go
- resources/kcp/values.yaml
- implement Service Manager client for necessary methods
- provide an easy way to get SM client from provisioning step
- implement dummy "doing readonly" uaa step (this implementation must be changed in the next PRs) to proove it works fine
- change sm_overrides step to use new implementation of SM credentails logic
Related: https://github.tools.sap/kyma/backlog/issues/908
> Service Manager client

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-skr.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
Adding dedicated test definition for SKR end-to-end test scenario. Dedicated test definition is required to be decoupled from existing provisioning scenarios.
https://github.tools.sap/kyma/backlog/issues/953
> Add TestDefinition for SKR provisioning+cleanup

- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/values.yaml
> Fix resuming upgrade operations after KEB restart

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/input/builder_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
- resources/kcp/values.yaml
- Add profiles to kyma plans
#287
> Add profiles to kyma plans

- resources/kcp/values.yaml
Update both images to the latest version
> Correcting images for provisioner and provisioner tests

- docs/kyma-environment-broker/03-01-service-description.md
- Fixed dead link pointing to KEB provisioning steps list
> Fix dead link in KEB service description

- resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
- resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
- disable istio sidecar for cronjobs with the external database
> Disable istio sidecar for cronjobs with external database

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- Fix parameter value for KEB deployment
> Fix parameter value for KEB deployment

- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/input/builder_test.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
- KEB: upgrade input builder has the same logic with a component list like for provisioning
> Fix KEB upgrade component list

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/broker/services.go
- components/kyma-environment-broker/internal/dto.go
- resources/kcp/values.yaml
- service contains a flag "allow_context_updates" which enables context updates by KEB client
- added more logging to the update endpoint logic to see what we get
> Keb context updates

- components/kyma-environment-broker/common/runtime/client.go
- components/kyma-environment-broker/common/runtime/client_test.go
- components/kyma-environment-broker/common/runtime/model.go
- components/kyma-environment-broker/internal/runtime/handler.go
- tools/cli/pkg/command/runtime.go
- add Plans to runtime ListParameters
> Add plans to runtime listParams

- resources/kcp/charts/provisioner/values.yaml
- resources/kcp/templates/migrator-job.yaml
- Parametrize Migrator quit command
It's a clean up for [this fix](https://github.com/kyma-project/control-plane/pull/369)
> Parametrize Migrator quit command

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- components/kyma-environment-broker/internal/broker/broker.go
- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/broker/services.go
- components/kyma-environment-broker/internal/broker/services_test.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
Enrich details in the broker responses.
- Upgrade existing parameters and add new on GET `/v2/catalog` endpoint
- Add new parameters to metadata section on PUT `/v2/service_instances` endpoint
> KEB - ERS improvements

- CODEOWNERS
- Add Gopher team to all files as CODEOWNERS
- Remove @dbadura from CODEOWNERS
> Add Gopher team to all files as CODEOWNERS

- components/schema-migrator/migrations/kyma-environment-broker/202012150900_add_provisioning_parameters_to_operation.down.sql
- components/schema-migrator/migrations/kyma-environment-broker/202012150900_add_provisioning_parameters_to_operation.up.sql
- resources/kcp/values.yaml
- Append operations table with provisioning parameters stored in JSON type
> Append operations table with provisioning parameters

- components/kyma-environment-broker/internal/migrations/parameters.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- components/kyma-environment-broker/internal/storage/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- components/kyma-environment-broker/internal/storage/postsql/write.go
- resources/kcp/values.yaml
- Fixed provisioning parameters type to sql.NullString
> Fix provisioning parameters type

- docs/cli/commands/kcp_taskrun.md
- tools/cli/cmd/gendocs/gendocs.go
- tools/cli/pkg/command/taskrun.go
- Add `--` to kcp taskrun documentation
> Add -- to kcp taskrun documentation

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/storage/driver/memory/instance.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/postsql/write.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- components/kyma-environment-broker/internal/storage/tests_utils.go
- components/schema-migrator/migrations/kyma-environment-broker/202012151612_add_version_to_instance.down.sql
- components/schema-migrator/migrations/kyma-environment-broker/202012151612_add_version_to_instance.up.sql
- resources/kcp/values.yaml
- add optimistick locking for instsance updates (KEB)
> KEB instance model with versioning

- docs/cli/commands/kcp_runtimes.md
- tools/cli/go.mod
- tools/cli/go.sum
- tools/cli/pkg/command/runtime.go
…runtime cmd flag
- add coloumn PLAN to KCP CLI runtime cmd output 
- add plan as KCP CLI runtime cmd flag
> add plan column to runtime. output also make it a filtering flag

- components/kyma-environment-broker/internal/storage/driver/memory/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/values.yaml
- Added extra condition when getting last operation for given `instanceID` to ensure the operation is not in `pending` state
#399
> Return only non-pending operations when getting last operation

- components/provisioner/Dockerfile
- components/provisioner/Makefile
- components/provisioner/go.mod
- resources/kcp/values.yaml
- Bump Alpine and Golang in Provisioner
> Bump Alpine and Golang in Provisioner

- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- resources/kcp/values.yaml
- Fixed operations unmarshalling
> Fix operations unmarshalling

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
- resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
- resources/kcp/charts/provisioner/templates/deployment.yaml
- resources/kcp/templates/migrator-job.yaml
- resources/kcp/values.yaml
- Set custom cloudsql-proxy image
> Set custom cloudsql-proxy image

- docs/cli/commands/kcp.md
- docs/cli/commands/kcp_kubeconfig.md
- docs/cli/commands/kcp_login.md
- docs/cli/commands/kcp_orchestrations.md
- docs/cli/commands/kcp_runtimes.md
- docs/cli/commands/kcp_taskrun.md
- docs/cli/commands/kcp_upgrade.md
- docs/cli/commands/kcp_upgrade_kyma.md
- tools/cli/cmd/gendocs/gendocs.go
- tools/cli/pkg/command/taskrun.go
Expose SKR instance id in `INSTANCE_ID` environment variable during `kcp taskrun` executions.
> Add INSTANCE_ID env var to taskrun execution

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/values.yaml
> Fix parameters decryption

- components/metris/README.md
- add edp data schema and example data to the README
> update metris documentation

- components/kyma-environment-broker/internal/metrics/operation_duration.go
- components/kyma-environment-broker/internal/metrics/operations_collector.go
- components/kyma-environment-broker/internal/metrics/step_result.go
- components/kyma-environment-broker/internal/storage/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/driver/memory/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
- Added planID to the KEB operations metrics
> Add planID to the KEB operations metrics

- components/metris/README.md
> Fix a typo in Metris docs

- resources/kcp/values.yaml
- tests/e2e/provisioning/Dockerfile
- Bumped curl in e2e provisioning test
> Bump curl in e2e provisioning test

- resources/kcp/values.yaml
- tests/e2e/provisioning/Dockerfile
- Bump alpine in e2e provisioning test to 3.13
> Bump alpine in e2e provisioning test

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/migrations/instancedetails.go
- components/kyma-environment-broker/internal/migrations/instancedetails_test.go
- components/kyma-environment-broker/internal/storage/driver/memory/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/ext.go
- components/kyma-environment-broker/internal/storage/postsql/factory.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- Added migration for `InstanceDetails` field from latest `ProvisioningOperation` to `UpgradeKymaOperation`
> Add InstanceDetails migration to upgradeKyma operation

- components/kyma-environment-broker/internal/avs/client_test.go
- components/kyma-environment-broker/internal/avs/delegator.go
- components/kyma-environment-broker/internal/avs/delegator_test.go
- components/kyma-environment-broker/internal/avs/mock_server.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/evaluation_manager.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- resources/kcp/values.yaml
Adds tests and fixes Kyma upgrade issues for pre- and post- logic on monitor upgrades.
Failures of the additional steps should fail the operation as well. 
> Additional logic on Kyma upgrade

- resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
KEB handles PATCH requests - changes in ory rules.
> Allowes to KEB handles PATCH requests (instance update)

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- Enable InstanceDetails migration for upgradeKyma operations to propagate the instance data properly
- ...
- ...
> Enable InstanceDetails migration

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/auditlog/config.go
- components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
- components/kyma-environment-broker/internal/process/provisioning/audit_log_step_test.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/values.yaml
- Use the sequential http plugin only when enabled else by default use the http plugin for fluent bit
> Provide a feature flag to enable sequentialhttp fluentbit

- resources/kcp/values.yaml
- Bump image based on https://github.com/kyma-project/control-plane/pull/461
> Bump image using PR 461

- tools/cli/go.mod
- tools/cli/go.sum
- tools/cli/pkg/command/runtime.go
- Adapt to https://github.com/kyma-project/control-plane/pull/450
> Handle runtimes suspension/unsuspension operation states

- components/kyma-environment-broker/internal/migrations/instancedetails.go
- resources/kcp/values.yaml
> Fix checking InstanceDetails contect in migration

- resources/kcp/charts/kyma-environment-broker/values.yaml
- Change trial SKRs node count to 1
> Change trial SKRs node count to 1

- components/kyma-environment-broker/internal/suspension/handler.go
- resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
- resources/kcp/values.yaml
After merging https://github.com/kyma-project/control-plane/pull/450 the proper Swagger schema should be updated.
- Added `suspension` and `unsuspension` field to example json response in KEB swagger
https://github.com/kyma-project/control-plane/pull/450
> Update runtimes endpoint schema in KEB swagger

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/broker/instance_update_test.go
- the context update (http PATCH) is a partial update. First version was taking all values so we have cleaned values.
- this is the reason we need to take provisioning parameters from last provisioning operation
> KEB reverts erscontext cleanup

- components/kyma-environment-broker/internal/broker/instance_last_operation.go
- components/kyma-environment-broker/internal/broker/instance_last_operation_test.go
Return last operation for given `instanceID` when user does not provide `operationID` in request body when calling `GET /v2/service_instances/{id}/last_operation`
- Modified last operation endpoint
> KEB returns last operation state when operation ID not provided in request

- components/kyma-environment-broker/common/runtime/model.go
- components/kyma-environment-broker/internal/dto.go
- components/kyma-environment-broker/internal/runtime/converter.go
> KEB stores userid

- components/kyma-environment-broker/internal/storage/dbmodel/instance.go
- components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
- components/kyma-environment-broker/internal/storage/postsql/factory.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- components/kyma-environment-broker/internal/storage/storage_test.go
- resources/kcp/values.yaml
fix FindAllInstancesWithOperations and ListInstances to unmarshall provisioning parameters
> fix keb listing instances

- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/broker/instance_update_test.go
- components/kyma-environment-broker/internal/ptr/ptr.go
- resources/kcp/values.yaml
- finds latest provisioning and deprovisioning (operations) if exists and decide if the instance is active or not
- 
> Look at operations to see if the instance is active or not

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager.go
- components/kyma-environment-broker/internal/orchestration/kyma/manager_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/ems_deprovision.go
- components/kyma-environment-broker/internal/process/deprovisioning/ems_dprov_int_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/ems_unbind.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/deprovisioning/xsuaa_int_test.go
- components/kyma-environment-broker/internal/process/provision_operation.go
- components/kyma-environment-broker/internal/process/provisioning/ems_bind.go
- components/kyma-environment-broker/internal/process/provisioning/ems_prov_int_test.go
- components/kyma-environment-broker/internal/process/provisioning/ems_provision.go
- components/kyma-environment-broker/internal/process/provisioning/xsuaa_int_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/ems_bind.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/ems_bind_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/ems_prov_int_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/ems_provision.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/ems_provision_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/event_hub_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/event_hub_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/service_manager_offering_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/service_manager_offering_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma_operation.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
Upgrade Kyma-Eventing
- Extend the "upgrade_kyma" process for using the Service Manager
- Add new installing steps for Eventing-EMS
- Deprovision Eventing Event-Hub
See also https://github.com/kyma-project/kyma/issues/10317
> Upgrade eventing

- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/input/builder_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
- resources/kcp/values.yaml
- Add KymaProfile to upgrade request
> Add KymaProfile to upgrade request

- tools/cli/go.mod
- tools/cli/go.sum
- tools/cli/pkg/command/runtime.go
Integrate #511 with KCP CLI to use enhanced resolver which is aware of suspension/unsuspension
> Make kcp taskrun fully aware to suspension/unsuspension

- components/subscription-cleanup-job/go.mod
- components/subscription-cleanup-job/go.sum
- upgraded `golang.org/x/text` in Runtime Provisioner by `replace`
> Upgrade `golang.org/x/text` in `subscription-cleanup-job`

- components/kyma-environment-broker/internal/provider/azure_provider.go
- resources/kcp/values.yaml
- change autoscaler params to reduce nodes
> Set autoscale params for node reducement

- components/provisioner/internal/provisioning/service.go
The idea behind that is to align timeouts in KEB with timeouts in Provisioner. 
- Decreased number of retries in calls to Director
> Decrease retries count in calls to Director

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/migrations/operation_user_id.go
- components/kyma-environment-broker/internal/migrations/operation_user_id_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
- components/kyma-environment-broker/internal/storage/driver/memory/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/ext.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- Removed userID after deprovisioning
> Remove userID after deprovisioning

- components/kubeconfig-service/Dockerfile
- Update goland-toolbox in kubeconfig-service
> Update goland-toolbox in kubeconfig-service

- components/kyma-environment-broker/internal/migrations/instance_parameters.go
- resources/kcp/values.yaml
- Fix instances parameters migration
> Fix instances parameters migration

- resources/kcp/charts/provisioner/templates/tests/role-binding.yaml
- resources/kcp/charts/provisioner/templates/tests/service-account.yaml
- resources/kcp/charts/provisioner/templates/tests/test-hibernation.yaml
- Fix for Hibernation Test : service account was not created when hibernation test was enabled
> Fixed issue with non-existent Service Account in Hibernation test

- resources/kcp/OWNERS
I was missing in OWNERS file for approvers in resources/kcp directory.
> Adding Przemyslaw Golicz as approver of changes in kcp resources

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
> Bump keb deps

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
Implement the task of  [Grafana dashboard enhancement](https://github.tools.sap/kyma/backlog/issues/1266)
> add gauge of skr de-/provisioning success rate in grafana

- components/kubeconfig-service/Dockerfile
- resources/oidc-kubeconfig-service/values.yaml
- alpine: `3.12.0` -> `3.13.2`
- ...
- ...
> Update alpine base image in kubeconfig-service

- resources/oidc-kubeconfig-service/values.yaml
> Bump kubeconfig-service image from PR to valid

- docs/provisioner/08-02-provisioning-gardener.md
- Instructions to setup OpenStack provider
- Example provisioning mutation
> Add docs for openstack provisioning

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-skr.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-suspension.yaml
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- tests/e2e/provisioning/Gopkg.lock
- tests/e2e/provisioning/Gopkg.toml
- tests/e2e/provisioning/README.md
- tests/e2e/provisioning/pkg/client/broker/broker_client.go
- tests/e2e/provisioning/test/e2e_suspension_test.go
e2e suspension test makes calls to KEB which provisions Trial version of Kyma Runtime, then suspend and unsuspend it and check operations states after each step.
- Added e2e suspension trial test
> Add e2e trial suspension test

- resources/kcp/values.yaml
- Bumped e2e provisioning test image, implementation merged here: https://github.com/kyma-project/control-plane/pull/526
> Bump e2e provisioning test image

- components/metris/go.mod
- components/metris/go.sum
- update dependencies to fix security issues
> update k8s dependencies to 1.18.16

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
to implement the task [Grafana Dashboard for Gardener Usage Exporter](https://github.tools.sap/kyma/backlog/issues/1281)
> add gardener quota and azure secret usage tables in grafana dashboard

- resources/kcp/values.yaml
- tests/provisioner-tests/test/provisioner/hibernation_test.go
> Fix for hibernation test

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/plans_validator.go
- components/kyma-environment-broker/internal/broker/services_test.go
- components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
- components/kyma-environment-broker/internal/dto.go
- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/aws_provider_test.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- components/kyma-environment-broker/internal/runtime/disabled_components.go
- resources/kcp/charts/kyma-environment-broker/files/catalog.yaml
- resources/kcp/values.yaml
> Enable AWS in KEB

- components/kyma-environment-broker/internal/avs/client.go
- resources/kcp/values.yaml
Don't fail upgrade if AVS evaluation is not found
> Don't fail upgrade if AVS evaluation is not found

- components/provisioner/internal/api/resolver_integration_test.go
> Remove unnecessary test cases from Resolver tests

- components/kyma-environment-broker/internal/process/provisioning/ems_provision.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/ems_provision.go
If a new instance ID was generated, save it before starting the provisioning
- Persist operation in case of a new generated instance ID before starting provisioning
> Save the new instance ID before provisioning

- components/provisioner/internal/installation/resource_cleanup.go
- components/provisioner/internal/installation/resource_cleanup_test.go
- resources/kcp/values.yaml
- Remove clusterbrokers finalizers before uninstallation to speed up the process
> Remove clusterbrokers finalizers before uninstallation

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- resources/kcp/values.yaml
`testcontainers-go` in version `0.9.0` contains security vulnerabilities
- Bumped `testcontainers-go` dependency to latest version ` v0.10.0`
> Bump testcontainers-go in KEB

- components/kyma-environment-broker/internal/cls/client.go
- components/kyma-environment-broker/internal/cls/config.go
- components/kyma-environment-broker/internal/cls/config_test.go
- components/kyma-environment-broker/internal/cls/deprovisioner.go
- components/kyma-environment-broker/internal/cls/kyma_version_check.go
- components/kyma-environment-broker/internal/cls/overrides.go
- components/kyma-environment-broker/internal/cls/provisioner.go
- components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step.go
- components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step_test.go
- components/kyma-environment-broker/internal/process/provisioning/cls_binding_step.go
- components/kyma-environment-broker/internal/process/provisioning/cls_offering_step.go
- components/kyma-environment-broker/internal/process/provisioning/cls_provision_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_audit_log.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_audit_log_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_binding.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_offering.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_provision.go
> Improve CLS log messages

- components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
- resources/kcp/values.yaml
- runs intance cleanup when operation succeeded
> KEB removes instance after deprovisioning runtime

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/Gopkg.toml
- resources/kcp/values.yaml
`microsoft/hcsshim` in version `v0.8.7` contains security vulnerabilities
- Bumped `microsoft/hcsshim` to latest version `v0.8.15`
> Bump hcsshim dependency in KEB

- docs/cli/commands/kcp_upgrade_kyma.md
- tools/cli/go.mod
- tools/cli/go.sum
- tools/cli/pkg/command/upgrade.go
- tools/cli/pkg/command/upgrade_kyma.go
Allows KCP to specify a custom version on Kyma upgrade.
> Add version parameters to KCP CLI on Kyma upgrade

- components/kyma-environment-broker/internal/process/deprovisioning/event_hub_activation.go
- components/kyma-environment-broker/internal/process/deprovisioning/event_hub_activation_test.go
- components/kyma-environment-broker/internal/process/provisioning/event_hub_activation.go
- components/kyma-environment-broker/internal/process/provisioning/event_hub_activation_test.go
- components/kyma-environment-broker/internal/process/provisioning/nats_activation_step.go
- components/kyma-environment-broker/internal/process/provisioning/nats_activation_step_test.go
- resources/kcp/values.yaml
- Fix KymaVersion in azure event hub activation step
> Fix KymaVersion in azure event hub activation step

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-suspension.yaml
- resources/kcp/values.yaml
- tests/e2e/provisioning/test/e2e_suspension_test.go
> Fetch e2e test cluster kubeconfig after unsuspending runtime

- resources/kcp/values.yaml
- Forgot to bump it in #605 
See also #605
> Bump KEB image version

- components/kyma-environment-broker/internal/suspension/handler.go
- components/kyma-environment-broker/internal/suspension/handler_test.go
- components/provisioner/assets/database/provisioner.sql
- resources/kcp/values.yaml
- old clusters were provisioned without saving shoot name and domain and it must be recovered from dashboard_url in the unsuspension process
> KEB extracts shoot name and domain from dashboard url

- resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
- add missing configuration with encrytpion key to env cleanup job
> Add missing encryption key reference to the environment cleanup job

- resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
> Fix indentation in environments cleanup Job

- components/kyma-environment-broker/internal/process/deprovisioning/cls_unbinding_step.go
- components/kyma-environment-broker/internal/process/provisioning/cls_binding_step.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/cls_binding.go
- resources/kcp/values.yaml
- Add retry logic to binding (only for temporary errors)
- Add retry logic to unbinding (only for temporary errors)
> KEB: Improve error handling in CLS binding/unbinding steps

- resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
- Add update secretbindings rbac for KEB
> Add update secretbindings rbac for KEB

- .kyma-project-io/build-preview.sh
> Update docs preview

- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/values.yaml
Extract provisioning/deprovisioning steps & queue creation to separate exported functions. This will allow using the functions in test scenarios and should avoid possible conflicts in future code changes. 
- put provisioning steps definition and queue creation in `NewProvisioningProcessingQueue()` function,
- put deprovisioning steps definition and queue creation in `NewDeprovisioningProcessingQueue()` function.
Related issue(s)
#619
> Extract KEB's queues creation to separate functions

- resources/kcp/values.yaml
> Fix cloudsql image dir

- .github/pull-request-template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- components/kyma-environment-broker/CODE_OF_CONDUCT.md
- components/kyma-environment-broker/CONTRIBUTING.md
- components/kyma-environment-broker/README.md
- components/provisioner/README.md
- docs/README.md
- docs/kyma-environment-broker/02-02-broker-endpoints.md
- docs/kyma-environment-broker/03-02-runtime-components.md
- docs/kyma-environment-broker/03-03-runtime-operations.md
- docs/kyma-environment-broker/03-08-kyma-versions.md
- docs/kyma-environment-broker/03-11-swagger.md
- docs/provisioner/01-01-provisioner-overview.md
- scripts/README.md
- tests/e2e/provisioning/README.md
SAP is replacing insensitive terms (such as `master` / `slave`, `whitelist` / `blacklist`) with an inclusive language that helps to create a more inclusive workplace and ecosystem. To comply with this vision, we must adjust our documentation and correct the usage of these terms.
- Rename `master` references to `main`
https://github.com/kyma-project/community/issues/515
> Remove insensitive terms

- components/kyma-environment-broker/common/orchestration/client.go
KCP CLI required changes for cluster upgrade operation.
- Extend KEB common client with cluster upgrade function
- ...
- ...
https://github.tools.sap/kyma/backlog/issues/1165
> Cluster upgrade orchestration - common cli client, part 4

- resources/kcp/values.yaml
- tests/e2e/provisioning/Gopkg.lock
- tests/e2e/provisioning/Gopkg.toml
- Delete KEBs fork from the e2e test
> Delete KEBs fork from the e2e test

- resources/kcp/values.yaml
- third-party-images repo was moved and docker paths adjusted, so updating to the latest version for the cloudsql image
- ...
- ...
kyma-project/third-party-images#75
> updated to newest docker image for cloudsql to adapt docker image name changes

- components/provisioner/internal/gardener/auditlogging.go
- resources/kcp/values.yaml
> Make audit log regexp more broad

- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/manager_test.go
- components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
- components/kyma-environment-broker/internal/process/provisioning/staged_manager_test.go
- components/kyma-environment-broker/internal/storage/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- components/kyma-environment-broker/internal/storage/postsql/write.go
- components/kyma-environment-broker/internal/storage/tests_utils.go
- components/schema-migrator/migrations/kyma-environment-broker/202104010820_add_finished_stages.down.sql
- components/schema-migrator/migrations/kyma-environment-broker/202104010820_add_finished_stages.up.sql
Implementation of a replacement for provisioning.Manager - StagedManager. This new implementation will replace existing one at the final PR
What was done in the PR:
- Manager with stages
- Operation with persisted finished stages to not unnecessary stage execution 
- Manager does not rerun finished stages 
- Manager does not rerun finished steps (it reruns only if the Pod is restarted)
https://github.com/kyma-project/control-plane/issues/622
> Keb with staged steps

- resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml
- resources/kcp/charts/kyma-metrics-collector/values.yaml
- Make gardener ns configurable
> Make gardener ns configurable

- components/kyma-environment-broker/internal/storage/dbmodel/operation.go
- components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
- resources/kcp/values.yaml
> Fix operation storage in keb

- components/provisioner/Dockerfile
- resources/kcp/values.yaml
- Upgrade Alpine version in Runtime Provisioner
> Upgrade Alpine version in Runtime Provisioner

- docs/kyma-environment-broker/03-05-authorization.md
SAP is replacing insensitive terms (such as `master` / `slave`, `whitelist` / `blacklist`) with an inclusive language that helps to create a more inclusive workplace and ecosystem. To comply with this vision, we must adjust our documentation and correct the usage of these terms.
- Rename `master` references to `main`
https://github.com/kyma-project/community/issues/515
> Rename master to main

- components/kyma-environment-broker/Gopkg.lock
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/ias/builder.go
- components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step.go
- components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step_test.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/sm_overrides.go
- components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
- components/kyma-environment-broker/internal/process/provisioning/staged_manager_test.go
- components/kyma-environment-broker/internal/process/queue.go
- components/kyma-environment-broker/internal/provisioner/fake_client.go
- components/kyma-environment-broker/internal/servicemanager/fake.go
- resources/kcp/values.yaml
- Added e2e test covering `ProvisioningOperation` processing in the provisioning queue
#619
> Add e2e provisioning queue test

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/common/director/fake.go
- add assertions to KEB provisioning process e2e test
> Add assertions to keb provisioning queue test

- resources/kcp/values.yaml
> Bump KEB image to PR-658

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/broker/instance_last_operation.go
- components/kyma-environment-broker/internal/broker/instance_last_operation_test.go
- resources/kcp/values.yaml
- the LastOperation endpoint must work if the instance does not exists. It happens when the deprovisioning is finished.
> Fix keb last operation

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- Make skipDeprovisionAzureEventingAtUpgrade flag configurable from outside
see also #658
> Add skipDeprovisionAzureEventingAtUpgrade flag to charts

- components/kyma-environment-broker/internal/broker/instance_create_test.go
- components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler_test.go
- components/kyma-environment-broker/internal/runtime/provider.go
- components/kyma-environment-broker/internal/runtime/provider_test.go
- components/provisioner/internal/installation/release/gcs_downloader.go
- components/provisioner/internal/installation/release/gcs_downloader_test.go
- docs/cli/commands/kcp_upgrade_kyma.md
- docs/kyma-environment-broker/03-08-kyma-versions.md
- installation/cmd/run.sh
- installation/resources/README.md
- installation/scripts/generate-installer-artifacts.sh
- resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
- tools/cli/pkg/command/upgrade_kyma.go
SAP is replacing insensitive terms (such as `master` / `slave`, `whitelist` / `blacklist`) with an inclusive language that helps to create a more inclusive workplace and ecosystem. To comply with this vision, we must adjust our code and documentation and correct the usage of these terms.
- Rename `master` references to `main`, if possible
https://github.com/kyma-project/community/issues/515
> Change master to main

- resources/kcp/values.yaml
> Bump image for KMC

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- add test cases for other plans in provisioning process flow
- add necessary asserts
> KEB trail e2e provisioning test

- components/kubeconfig-service/Dockerfile
- Bump alpine image in kubeconfig-service
> Bump alpine image

- tools/cli/pkg/command/upgrade_kyma.go
Allow empty (default) value for KCP CLI  kyma upgrade version option
> Allow empty (default) value for KCP CLI  kyma upgrade version option

- resources/oidc-kubeconfig-service/values.yaml
- Bump kubeconfig-service image after changes in dockerfile
https://github.com/kyma-project/control-plane/pull/683
> Kubeconfig-service image bump

- components/kyma-environment-broker/common/orchestration/client.go
- add missing interface for common cluster upgrade function, should be part of https://github.com/kyma-project/control-plane/pull/635
> missing interface for common cluster upgrade function

- CODEOWNERS
- Added tunas to codeowners for KMC
> Add tunas to codeowners for KMC

- resources/kcp/values.yaml
- Upgraded the Provisioner deployment image.
> Upgrade Provisioner image

- CODEOWNERS
> Added tunas to codeowners

- components/kyma-metrics-collector/Dockerfile
- resources/kcp/values.yaml
- Changed base image to distroless to solve security issues CVE-2021-3450, CVE-2021-3449 and CVE-2021-28831
> Changed base image to distroless

- components/provisioner/Dockerfile
- components/provisioner/Makefile
- components/provisioner/go.mod
- resources/kcp/values.yaml
- Bump Golang version in Provisioner
> Bump Golang version in Provisioner

- components/kyma-metrics-collector/README.md
> Tuned readme for KMC

- resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
- fix subaccount cleaner job chart
> Fix subaccount cleaner job

- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- resources/kcp/values.yaml
- handle Provisioner errors in RuntimeOperationStatus operation
> Keb more logs

- components/provisioner/go.mod
- Upgraded version of hydroform
> Hydroform Version Bump

- components/kyma-environment-broker/internal/process/provisioning/manager.go
- resources/kcp/values.yaml
- provisioning manager must not finish operation if the state is "pending"
> KEB do not finish pending provisioning operations

- resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml
- resources/kcp/charts/kyma-metrics-collector/templates/service.yaml
- resources/kcp/charts/kyma-metrics-collector/values.yaml
- Add svc for kmc as this will enable monitoring systems to access `/healthz` endpoint
> Add svc for kmc

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
- resources/kcp/values.yaml
Some fields in azure_lite plan schema require update.
- adjust azure_lite plan schema.
> Adjust azure_lite plan schema

- resources/kcp/values.yaml
- tests/e2e/provisioning/Dockerfile
> Fix image tags in jobs

- components/kyma-environment-broker/internal/broker/instance_create_test.go
- resources/kcp/values.yaml
Fix failing broker test: `TestProvision_Provision`
> Fix broker provision test

- tools/cli/pkg/command/upgrade_cluster.go
(minor changes)
- add missing runtime cli flag for cluster upgrade
- extra spaces for cli help example output
https://github.tools.sap/kyma/backlog/issues/1165 -> backlog
> Cluster cli backlog

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
- resources/kcp/values.yaml
> Fix unsuspension process

- components/kyma-environment-broker/internal/process/provisioning/initialisation.go
- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-free-aws.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- tests/e2e/provisioning/pkg/client/broker/broker_client.go
- add free-aws e2e test
- add possibility to specify provider region to KEB client in those tests
> E2e free AWS testing pipeline

- resources/kcp/values.yaml
- tests/e2e/provisioning/pkg/client/broker/broker_client.go
- add url to the error in e2e tests
> Add logs to e2e tests

- resources/kcp/values.yaml
- tests/e2e/provisioning/pkg/client/broker/broker_client.go
- fix KEB client in e2e pipeline test
> Fix e2e pipeline KEB client

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
- resources/kcp/values.yaml
- Changed autoscalerMax.Minimum to `4` and .Maximum to `40` for azure_ha plan
> Fix azure HA schema

- components/kyma-environment-broker/internal/runtime/handler.go
- resources/kcp/values.yaml
- fix bug which displays deprovisioning operation with zeroed values.
> Bugfix for /runtimes endpoint displaying zeroed deprovisioning operation

- components/provisioner/internal/provisioning/persistence/dbsession/write.go
- resources/kcp/values.yaml
> KEB Resolve user (email) of the runtime creator

- components/kyma-environment-broker/go.mod
- components/kyma-environment-broker/go.sum
- resources/kcp/values.yaml
> KEB Resolve user (email) of the runtime creator (#766) - go.mod

- components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
- components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
- components/provisioner/internal/util/testkit/shoot.go
- resources/kcp/values.yaml
- Shoot upgrade operation returns recoverable error when encounters rate limit exceeded error
- Test added
> Retry operation when shoot upgrade encounters rate limit exceeded error

- components/provisioner/Dockerfile
- components/provisioner/go.sum
- resources/kcp/values.yaml
> Bump Provisioners alpine

- components/kyma-environment-broker/common/orchestration/dto.go
- components/kyma-environment-broker/common/orchestration/resolver.go
- components/kyma-environment-broker/common/orchestration/resolver_test.go
- ... Clients should be able to target instance IDs
> Added instanceID to data target and resolver

- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
> Bump schema migrator base alpine image

- components/kyma-environment-broker/common/hyperscaler/account_provider.go
- components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
- resources/kcp/values.yaml
- use provider stored in the instance as a source of truth for deprovisioning
> Use stored provider in KEB deprovisioning

- tools/cli/pkg/command/options.go
- tools/cli/pkg/command/root.go
- tools/cli/pkg/credential/manager.go
- No feature has been added, because of login issues, I had to remove the client secret. 
> Removed oidc client secret

- tools/cli/pkg/command/options.go
- tools/cli/pkg/command/root.go
remove oidcClientSecret from required global options list
> remove oidcClientSecret from required global options list

- components/kyma-environment-broker/internal/broker/services.go
- resources/kcp/values.yaml
Kyma instance has no purpose to be bound to applications.
- set bindable field to false.
See also #737
> Set Kyma service bindable field to false

- resources/kcp/values.yaml
- Update cloudsql-docker/gce-proxy to 1.23.0-alpine
> Update cloudsql-docker/gce-proxy to 1.23.0-alpine

- resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
Add missing VirtualService rule for /kubeconfig/* endpoint
[#556](https://github.com/kyma-project/control-plane/pull/556)
> Add kubeconfig path to VirtualService

- components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
- components/kyma-environment-broker/internal/process/provisioning/audit_log_step_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/audit_log.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/audit_log_test.go
- Fix such that secrets are populated properly
> Use secrets for auditlog

- components/kyma-environment-broker/internal/process/provisioning/ems_bind.go
- resources/kcp/values.yaml
- Remove the obsolete for now IsBEBEnabled flag
> Remove IsBEBEnabled flag

- docs/kyma-environment-broker/03-01-service-description.md
- Updated available plans with parameters in KEB's service description
> Update KEB service description docs

- components/kyma-environment-broker/internal/broker/plans_schema.go
- components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
- components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
- components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
- components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
- components/kyma-environment-broker/internal/broker/testdata/azure-schema.json
- components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema.json
- components/kyma-environment-broker/internal/broker/testdata/free-aws-schema.json
- components/kyma-environment-broker/internal/broker/testdata/free-azure-schema.json
- components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json
- components/kyma-environment-broker/internal/broker/testdata/openstack-schema.json
- ...
- ...
- ...
https://github.tools.sap/kyma/backlog/issues/1554
> Add auto generate property to KEB plans schemas

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
- components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime_test.go
- components/kyma-environment-broker/internal/process/input/input.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- allow to configure deprovisioning KEB timeout
> Define deprovisioning timeout in KEB

- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- add proper env to the chart for default trial provider
> Make default trial provider in KEB configurable

- components/kyma-environment-broker/internal/broker/instance_create.go
> Fix OIDC mandatory fields validation

- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider.go
- resources/kcp/values.yaml
- configure proper zone in case of custom region
https://github.com/kyma-project/control-plane/issues/840
> Fix KEB freemium zones

- components/provisioner/internal/operations/executor.go
- components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion.go
- components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
- resources/kcp/values.yaml
- Recoverable operation errors are now logged as warnings 
#764
> Change log levels for recoverable errors

- .kyma-project-io/build-preview.sh
- CODEOWNERS
- OWNERS
- OWNERS_ALIASES
- resources/kcp/OWNERS
- Cleanup @kazydek @aerfio @kfurgol @magicmatatjahu from CODEOWNERS
> Cleanup code owners

- components/provisioner/internal/operations/queue/queues_constructor.go
- components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect.go
- components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect_test.go
- components/provisioner/internal/runtime/configuration_test.go
- components/provisioner/internal/runtime/configurator.go
- resources/kcp/values.yaml
Fix: https://github.tools.sap/kyma/backlog/issues/1585
> Reconfigure runtime (upsert secret) on Compass ConnectionFailed

- resources/kcp/values.yaml
- Bump Provisioner to the main version
> Bump Provisioner to the main version

- tools/cli/pkg/command/options.go
Add support for Azure HA, AWS HA and Free plans
> Add support for missing plans in KCP CLI

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.sac
- resources/kcp/values.yaml
- tests/e2e/provisioning/Dockerfile
- Bumping alpine and rebuilding the image updates curl to `7.77.0` to address a CVEs present in `7.76.1`.
* https://github.tools.sap/kyma/security-scans/issues/8630
* https://github.tools.sap/kyma/security-scans/issues/8627
* https://github.tools.sap/kyma/security-scans/issues/8628
> Bump alpine to v3.14.0

- CODEOWNERS
- https://github.com/kyma-project/control-plane/pull/865 missed a few places to add @voigt and @wozniakjan 
> Add voigt and wozniakjan to all KEB related directories

- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
- resources/kcp/values.yaml
- fix OIDC field in GraphQL template
> KEB fix UpgradeShoot GraphQL template

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
- resources/kcp/values.yaml
- the upgrade process does not use default OIDC values which makes an invalid request to Provisioner
> Set default OIDC values in update request

- resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
- In the private repository, the config map name is different, thus it couldn't run.
> Modified config map name

- resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
- The test definition needs to provision and test that, not the upgrade scenario.
> Set upgrade test to false in test definition

- docs/kyma-environment-broker/03-13-custom-administrators.md
- add the documentation about administrators parameter.
> Administrators parameter doc

- resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
**Changes**
The cleanup definition has had a wrong name and I have changed it according to the first definition in the file.
> Modified wrongly given cleanup testdefinition name

- components/provisioner/go.mod
- components/provisioner/go.sum
- resources/kcp/values.yaml
- Replace apimachinery in Provisioner
> Replace apimachinery in Provisioner

- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
- Use planID as template variable in KEB dashboard
- Replace charts using hardcoded planID & planName with templated ones
https://github.com/kyma-project/control-plane/pull/851
> Use planID as template variable in KEB dashboard

- components/kyma-metrics-collector/README.md
- Update the description of KMC and describe the functionality
https://github.com/orgs/kyma-project/projects/3#card-67415944
> Update description of KMC

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
- components/kyma-environment-broker/internal/runtimeversion/runtimeversion_test.go
- docs/kyma-environment-broker/03-08-kyma-versions.md
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- introduce a new Preview Plan
- handle new Preview env var
- [#1686](https://github.tools.sap/kyma/backlog/issues/1686)
> add new previewPlanID

- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
- components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
- InputCreator has methods for creating inputs for provisioner and reconciler for kyma 2.0 (Preview plan)
> KEB input creator for preview plan

- components/kyma-metrics-collector/pkg/edp/client.go
- components/kyma-metrics-collector/pkg/keb/client.go
- resources/kcp/values.yaml
- Ovserve duration for each request instead
https://github.com/orgs/kyma-project/projects/3#card-64966588
> Fine tune metrics

- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- resources/kcp/values.yaml
- extending shoot spec with DNS & Cert extensions
https://github.com/kyma-project/control-plane/issues/875
> extending shoot spec with DNS & Cert extensions

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
- components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
- components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
- components/kyma-environment-broker/internal/runtimeversion/runtimeversion_test.go
- resources/kcp/values.yaml
- add logic for determining Kyma's major version
> Determine Kyma's major version

- CODEOWNERS
> Add ralikio to CODEOWNERS

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/process/input/builder.go
- components/kyma-environment-broker/internal/provider/aws_provider.go
- components/kyma-environment-broker/internal/provider/aws_provider_test.go
- set proper zone for region for AWS Trial plan
Fixes: https://github.com/kyma-project/control-plane/issues/924
> Fix aws trial

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/runtime/provider.go
- components/kyma-environment-broker/internal/runtime/provider_test.go
- components/kyma-environment-broker/internal/runtime/testdata/additional-runtime-components.yaml
- resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- edit chart so it includes new additional components for runtime,
- add logic to differentiate additional components for runtime versions.
> KEB new additional components

- resources/kcp/values.yaml
> Bump cloudsql-proxy image

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.sac
- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
- tests/e2e/provisioning/Dockerfile
> Bump alpine version in KEB

- docs/kyma-environment-broker/08-05-orchestrate-kyma-upgrade.md
- s/strategies/strategy/ - [see code](https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/common/orchestration/dto.go#L12)
- include is a list of runtime targets, not a single object - [see code](https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/common/orchestration/dto.go#L103)
> fix payload in keb upgrade docs

- components/kyma-metrics-collector/Dockerfile
- resources/kcp/values.yaml
> update base image to update go

- resources/kcp/values.yaml
> Bump KEB (enable preview plan)

- components/provisioner/internal/gardener/shoot_reconciler.go
- resources/kcp/values.yaml
- Audit logging setup logs warns instead of errors
> Change log level of Audit logging setup to warn

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.sac
- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
- set apk repository for curl to v3.14 instead of edge.
> Fix apk repository for curl

- components/provisioner/Dockerfile
- resources/kcp/values.yaml
> Bump Alpine in Provisioner

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/plans_schema.go
- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/services.go
- resources/kcp/values.yaml
Currently, KEB doesn't expose update parameters for any plans. This PR is a follow-up to #920 and exposing the instance update parameters through plan update.
<details><summary>Diff between main branch on `/v2/catalog` endpoint:</summary>
<p>
```diff
*** /dev/fd/63	2021-09-30 08:57:14.222591053 +0200
--- /dev/fd/62	2021-09-30 08:57:14.225924373 +0200
***************
*** 90,96 ****
}
},
"update": {
-                 "parameters": null
}
},
"service_binding": {
--- 90,115 ----
}
},
"update": {
+                 "parameters": {
+                   "$schema": "http://json-schema.org/draft-04/schema#",
+                   "_controlsOrder": [],
+                   "_show_form_view": true,
+                   "properties": {
+                     "autoScalerMax": {
+ …
```
> Update plan schema in KEB

- resources/kcp/charts/component-reconcilers/Chart.yaml
- resources/kcp/charts/component-reconcilers/templates/deployment.yaml
- resources/kcp/charts/component-reconcilers/templates/rbac.yaml
- resources/kcp/charts/component-reconcilers/templates/service.yaml
- resources/kcp/charts/component-reconcilers/values.yaml
- resources/kcp/charts/mothership-reconciler/.helmignore
- resources/kcp/charts/mothership-reconciler/Chart.yaml
- resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
- resources/kcp/charts/mothership-reconciler/templates/_helpers.tpl
- resources/kcp/charts/mothership-reconciler/templates/cr-configmap.yaml
- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/templates/mr-encryption-key-secret.yaml
- resources/kcp/charts/mothership-reconciler/templates/mr-secret.yaml
- resources/kcp/charts/mothership-reconciler/templates/service.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
- resources/kcp/requirements.yaml
- resources/kcp/values.yaml
- tools/kcp-installer/kcp.Dockerfile
- Add reconciler resources to control-plane
- Bump kyma-operator
> Add reconciler to control-plane

- docs/kyma-environment-broker/03-01-service-description.md
Documentation for `PATCH` on `/v2/service_instances/${instance}` endpoint implemented in https://github.com/kyma-project/control-plane/pull/920.
https://github.com/kyma-project/control-plane/pull/920
> Document KEB update parameters

- resources/kcp/charts/component-reconcilers/templates/deployment.yaml
- resources/kcp/values.yaml
> fix reco images

- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/values.yaml
> fix reco args

- resources/kcp/charts/mothership-reconciler/templates/mr-encryption-key-secret.yaml
> fix secret key

- components/kyma-environment-broker/internal/provider/openstack_provider.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer.go
- components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
- adds missing exporeClassName to graphqlizer
- change defaultOpenStackRegion to `eu-de-2`
https://github.tools.sap/kyma/backlog/issues/1775
> Add exposure class name to graphqlizer

- components/kyma-environment-broker/internal/broker/plans_test.go
- components/kyma-environment-broker/internal/broker/testdata/update-aws-ha-schema.json
- components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json
- components/kyma-environment-broker/internal/broker/testdata/update-azure-ha-schema.json
- components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema.json
- components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json
- components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json
- components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema.json
This is a followup for https://github.com/kyma-project/control-plane/pull/943. The update schema code was implemented there and this provides set of unit tests for the update schema.
https://github.com/kyma-project/control-plane/pull/943
> Unit tests for update plans schema in KEB

- resources/kcp/values.yaml
> set keb value

- resources/kcp/charts/mothership-reconciler/values.yaml
- resources/kcp/values.yaml
https://github.com/kyma-incubator/reconciler/pull/227
> Rename istio prereq to istio-configuration

- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- components/kyma-environment-broker/internal/reconciler/contract.go
- resources/kcp/values.yaml
- provide a source URL of a component to reconciler
> Keb component source for reconciler

- docs/kyma-environment-broker/03-01-service-description.md
- add plan name - plan id mappings for all existing plans
- correct `preview` plan name formatting
See: https://github.com/kyma-project/kyma/issues/12344
> Describe mapping between plan name and plan id for service plans

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
- resources/kcp/values.yaml
> KEB does not retry cluster config creation

- resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-ha-aws.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
Adding e2e-provisioning-ha-aws.yaml and updateing values.yaml with ha_aws plan id
- ...
- ...
- ...
> Adding e2e-provisioning-ha-aws.yaml and updateing values.yaml with ha_aws plan id

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration_step_test.go
- components/kyma-environment-broker/internal/storage/dbmodel/runtime_state.go
- components/kyma-environment-broker/internal/storage/driver/memory/runtime_state.go
- components/kyma-environment-broker/internal/storage/driver/memory/runtime_state_test.go
- components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
- components/kyma-environment-broker/internal/storage/ext.go
- resources/kcp/values.yaml
- add reconciler payload to storage.
> Reconciler payload persistence (memory)

- resources/kcp/values.yaml
- Update reconciler charts (including latest changes from this commit: https://github.com/kyma-incubator/reconciler/commit/40bbe781d32e6a6d7a52884fa4733d3340557c2d)
> Update reconciler chart 

- components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
- components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
- resources/kcp/values.yaml
- define EDP pklan for azure lite
https://github.com/kyma-project/control-plane/issues/1001
> DEfine lite plan for EDP

- resources/kcp/values.yaml
- Update reconciler charts (including latest changes from this commit: https://github.com/kyma-incubator/reconciler/commit/6cf748c72587a84be76382419e808f1e712563cb)
> Update reconciler chart

- tools/cli/pkg/command/reconciliation_info.go
- Just  a simple typo fix
https://github.com/kyma-incubator/reconciler/issues/115
> Fix schceduling -> scheduling typo

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/process/input/input.go
- resources/kcp/values.yaml
- KEB propagates all globals to all components
> Keb provides global configuration for all components

- resources/kcp/charts/component-reconcilers/templates/authorization.yaml
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/templates/monitoring.yaml
- resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
- resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/templates/serviceaccount.yaml
- resources/kcp/values.yaml
- allow `mothership-reconciler` to reach `component-reconcilers`
- allow `component-reconcilers` and the KEB to reach the `mothership-reconciler`
- allow KEB to reach the `mothership-reconciler`
https://github.com/kyma-incubator/reconciler/issues/53
> Secure internal communication with mothership and component-reconcilers

- components/provisioner/internal/operations/queue/queues_constructor.go
- resources/kcp/charts/provisioner/templates/deployment.yaml
- resources/kcp/values.yaml
- Add NO_INSTALL env variables to the Provisioner
See the issue [here](https://github.com/kyma-project/kyma/issues/12354)
> Add NO_INSTALL env variables to the Provisioner

- resources/kcp/values.yaml
Add delete functionality in reconciler.
- add reconciler delete functionality
- fix state tracking for deleted clusters
https://github.com/kyma-incubator/reconciler/pull/298
https://github.com/kyma-incubator/reconciler/pull/317
> Add reconciler delete functionality

- components/provisioner/internal/api/resolver_test.go
- components/provisioner/internal/gardener/provisioner.go
- components/provisioner/internal/model/gardener_config.go
- components/provisioner/internal/model/gardener_config_test.go
- components/provisioner/internal/provisioning/input_converter.go
- components/provisioner/internal/provisioning/input_converter_test.go
- components/provisioner/internal/provisioning/service_test.go
- components/provisioner/pkg/gqlschema/models_gen.go
- components/provisioner/pkg/gqlschema/schema.graphql
- components/provisioner/pkg/gqlschema/schema_gen.go
- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
This PR is to separate the provisioner part of codes from the PR970 (DNS config added for custom domain support).
It keeps synced from PR970 provisioner codes changes.
- ...
- ...
- ...
> provisioner - synced with PR970 for DNS config

- resources/kcp/charts/component-reconcilers/templates/authorization.yaml
- resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
- resources/kcp/charts/mothership-reconciler/templates/virtualservice.yaml
- resources/kcp/values.yaml
> Allow disabling istio resources regarding reconcilers components

- resources/kcp/values.yaml
- Fix nil state update when starting reconciliation 
https://github.tools.sap/kyma/backlog/issues/1978
> Update reconciler to include nil state update fix

- resources/kcp/values.yaml
Update reconciler version to include changes below.
- Change reconciler logic to replace kubernetes resources instead of patching them
- Add preDeleteAction to ory reconciler
https://github.com/kyma-incubator/reconciler/issues/330
https://github.com/kyma-incubator/reconciler/issues/342
> Include reconciler resource replace change

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/input/input_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
- resources/kcp/values.yaml
> Fix boolean global overrides

- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json
- components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json
- components/kyma-environment-broker/internal/provider/gcp_provider.go
- resources/kcp/values.yaml
- Change Asia region for GCP form `asia-northeast1` to `asia-south1`
requested by @PK85
> Change Asia region for GCP plan in KEB

- components/kubeconfig-service/pkg/transformer/kubeconfig.go
- components/kubeconfig-service/pkg/transformer/transformer_test.go
- components/kyma-environment-broker/internal/kubeconfig/builder_test.go
- components/kyma-environment-broker/internal/kubeconfig/kubeconfig.go
- resources/kcp/values.yaml
- resources/oidc-kubeconfig-service/values.yaml
- Request extra scopes `email` and `openid` to support custom oidc configurations where email is targeted as username
Fixes https://github.com/kyma-project/control-plane/issues/1062
> Request Email and OpenID scopes in oidc-login

- tools/reconciler/e2e-test/get-reconcile-status.sh
- tools/reconciler/e2e-test/reconcile-kyma.sh
- tools/reconciler/e2e-test/request-reconcile.sh
- tools/reconciler/e2e-test/template.json
- Move test scripts for reconciler
> Move test scripts for reconciler

- components/kyma-environment-broker/internal/orchestration/manager/manager.go
- resources/kcp/values.yaml
- changed the rescheduleDelay to 0.
- ...
- ...
> change the rescheduleDelay to 0

- components/kyma-environment-broker/internal/kubeconfig/handler.go
- sanitize origin value in the kubeconfig handler
> Sanitize origin in the kubeconfig handler

- resources/kcp/values.yaml
- bump cloudsql-proxy image version
> Bump cloudsql-proxy img to v1.27.0

- resources/kcp/values.yaml
Image bump for https://github.com/kyma-incubator/reconciler/pull/382.
> Image Bump

- resources/kcp/values.yaml
Bumping reconciler to latest version.
> Bump reconciler to a3fbfa81

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.keb
- components/kyma-environment-broker/Dockerfile.sac
- components/kyma-environment-broker/go.mod
- components/kyma-environment-broker/go.sum
- resources/kcp/values.yaml
- bump golang.org/x/net version,
- bump golang img version (builder)
> Fix golang-runtime security issues

- tools/cli/pkg/command/operation_stop.go
- tools/cli/pkg/command/operation_stop_test.go
- add 404 http status handling
See https://github.com/kyma-incubator/reconciler/issues/309
> Fix Operation Stop when reconciler returnrs 404

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster_test.go
- components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration_step_test.go
- components/kyma-environment-broker/internal/reconciler/contract.go
- components/kyma-environment-broker/internal/reconciler/fake.go
- resources/kcp/values.yaml
- keb waits for reconciler deprovisioning to be finished
> KEB waits for reconciler deletion

- components/subscription-cleanup-job/Dockerfile
- components/subscription-cleanup-job/go.mod
- components/subscription-cleanup-job/go.sum
- resources/kcp/values.yaml
- bump subaccount cleanup job deps
> Bump subaccount cleanup job deps

- components/kyma-metrics-collector/Dockerfile
- components/kyma-metrics-collector/Makefile
- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
- Bump GO version to 1.1.7 for KMC
> Bump GO version for KMC

- resources/kcp/values.yaml
- Bump reconciler tags to include https://github.com/kyma-incubator/reconciler/pull/417
https://github.com/kyma-incubator/reconciler/pull/417
> Fix namespace resolution for interceptors

- resources/kcp/values.yaml
See https://github.com/kyma-incubator/reconciler/pull/421
> Remove migrate binary from reconciler image

- components/kyma-environment-broker/internal/error/not_found_error.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration_test.go
- components/kyma-environment-broker/internal/reconciler/client.go
> Fix check cluster deregistration

- resources/kcp/values.yaml
> Bump reconciler and mothership images

- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/values.yaml
- KEB resumes update operations after a restart
> KEB resumes update operations

- resources/kcp/values.yaml
> Upgrade reconciler image tag

- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/values.yaml
Reverts kyma-project/control-plane#1105
> Revert "KEB resumes update operations"

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/values.yaml
- (hotfix) resume 10 update operations (in the next PR it will be done as it should be)
> KEB resumes 16 update operations

- components/kyma-environment-broker/internal/process/upgrade_kyma/create_cluster_configuration.go
- resources/kcp/values.yaml
- Add error handling while getting latest runtimeState in upgrade queue
> Fix shadowed error when getting latest runtimeState in upgrade queue

- resources/kcp/values.yaml
Bump reconciler images:
- fix race condition while creating workspaces
See also: https://github.com/kyma-incubator/reconciler/issues/395
> Bump reconciler image - fix race condition while creating workspaces

- components/kyma-environment-broker/internal/process/input/input_test.go
- Adding additional test cases for overwriting overrides implemented here https://github.com/kyma-project/control-plane/pull/1112
https://github.com/kyma-project/control-plane/issues/1095
> Improve test coverage for appending overrides

- resources/kcp/values.yaml
> Fix image for subaccount cleaner job

- resources/kcp/charts/mothership-reconciler/templates/auditlog-config.yaml
- resources/kcp/charts/mothership-reconciler/templates/auditlog-pvc.yaml
- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/templates/mr-fluentbit-cm.yaml
- resources/kcp/values.yaml
- tools/reconciler/Makefile
- ...
- ...
- ...
https://github.com/kyma-incubator/reconciler/issues/291
> Enable auditlog for mothership-reconciler

- components/provisioner/Dockerfile
- components/subscription-cleanup-job/Dockerfile
- resources/kcp/values.yaml
- Bump Go version in Subscription Cleanup Job and Provisioner
> Bump Go version in Subscription Cleanup Job and Provisioner

- components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
- resources/kcp/values.yaml
- when the reconciler confirms the success, we need to finish the upgrade process
> Make operation succeeded if reconciler succeeced for upgrade

- resources/kcp/values.yaml
Update reconciler images.
- https://github.com/kyma-incubator/reconciler/pull/431.
> Update reconciler images

- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
- resources/kcp/values.yaml
> Process cluster deregistration error status

- resources/kcp/values.yaml
- Change audit log storage class to `default`
> Fix audit log storage class

- resources/kcp/values.yaml
- Set audit log storage class to standard
> Empty audit log storage class 

- resources/kcp/charts/mothership-reconciler/values.yaml
- resources/kcp/values.yaml
Upgrade to latest reconciler images and adjust configuration to install all pre-requisites in parallel / delete them in paralle.
> bump reconciler and configure parallel install

- resources/kcp/charts/mothership-reconciler/templates/auditlog-pvc.yaml
- Conditional storage class name
> Conditional storage class name

- components/kyma-environment-broker/internal/storage/postsql/read.go
- resources/kcp/values.yaml
> Load all not finished at startup

- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler.go
- components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go
- resources/kcp/values.yaml
- add code to get KymaConfig from reconciler.Cluster
#1096
> Fill KymaConfig after upgrade

- resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/templates/service.yaml
- resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/values.yaml
- resources/kcp/charts/component-reconcilers/templates/service.yaml
- resources/kcp/charts/component-reconcilers/values.yaml
- resources/kcp/charts/mothership-reconciler/templates/service.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
- Exposed port 15020 on reconciler service resources.
> Expose port 15020 on reconciler service resources

- resources/kcp/values.yaml
Version Bump for kyma-incubator/reconciler#477
> Version Bump

- resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
- resources/kcp/charts/mothership-reconciler/templates/policy.yaml
- resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
- resources/kcp/values.yaml
- Add ServiceMonitor for mothership-reconciler.
- Add PeerAuthentication
- Allow metrics in authorization policy
> Add serviceMonitor for mothership-reconciler

- components/kyma-environment-broker/internal/broker/instance_deprovision.go
- components/kyma-environment-broker/internal/broker/instance_deprovision_test.go
- resources/kcp/values.yaml
- the deprovisioning retry must not restart existing failed deprovisioning operation but create a new one
> Create new deprovisioning operation instead of retrying failed one

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.keb
- components/kyma-environment-broker/Dockerfile.sac
- resources/kcp/values.yaml
- bump golang image version in dockerfiles to 1.17.3-alpine3.14
> Bump golang image version to 1.17.3

- resources/kcp/values.yaml
Upgrade to latest reconciler library.
> Bump reconciler to latest image

- resources/kcp/values.yaml
Upgrade to latest reconciler lib (rev feb4fbd7)
> Upgrade to reconciler image feb4fbd7

- components/kyma-environment-broker/internal/reconciler/fake.go
- Added a persistence of `clusterConfig` containing for example components list for future assertions, when `ApplyClusterConfig` method is called on fake reconciler more than once
> Add persisting cluster config in fake reconciler

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/provisioner/fake_client.go
- resources/kcp/values.yaml
- return http 422 if the instance is deproviosioned or failed
> Do not allow to update an instance if the instance is failed or is being deprovisioned

- resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/templates/deployment.yaml
- resources/kcp/charts/component-reconcilers/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/values.yaml
- Changed reconciler image format in values.yaml
> changed reconciler image format in values.yaml

- components/kyma-environment-broker/common/orchestration/strategies/parallel.go
- resources/kcp/values.yaml
> Remove hardcoded 24 hours orchestration reschedule delay

- resources/kcp/values.yaml
https://github.com/kyma-incubator/reconciler/pull/519
> Update images for reconciliation components

- CODEOWNERS
> Add kwiatekus to the CODEOWNERS

- components/kyma-environment-broker/internal/metrics/operations_collector.go
- resources/kcp/charts/kyma-environment-broker/files/dashboard.json
-  Add GCPPlanID to metrics supportedPlansIDs
- update KEB grafana dashboard
> Add GCPPlanID to metrics supportedPlansIDs

- resources/kcp/values.yaml
Updating reconciler images to version 0b69711d
> Bump reconciler images to 0b69711d

- docs/README.md
- fix broken links
- remove redundant section "Docs structure"
- ...
> fix links in KCP docs README

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.keb
- components/kyma-environment-broker/Dockerfile.sac
- components/kyma-environment-broker/go.mod
- components/kyma-environment-broker/go.sum
- resources/kcp/values.yaml
- update dependencies to address security issues,
- bump golang image to 1.17.4
> Update runc dependency and golang image

- tools/reconciler/Makefile
remove postgresql.persistence.enabled=false
> remove postgresql.persistence.enabled=false

- tools/reconciler/Makefile
> revert change

- resources/kcp/values.yaml
Bump reconciler images to tag `8f7ef39c`
> Bump reconciler images to tag `8f7ef39c`

- resources/kcp/values.yaml
- Bump reconciler component after [this PR](https://github.com/kyma-incubator/reconciler/pull/509)
> Bump reconciler component

- resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
Reducing cleanup rate as it's too frequent
- Change subscription cleanup schedule to daily
> Change subscription cleanup schedule to daily

- resources/kcp/values.yaml
- Bump reconciler to include https://github.com/kyma-incubator/reconciler/pull/585
> Strip namespace from templates of selected kinds

- CODEOWNERS
Krystian left Kyma in October and he's no longer an active contributor so, according to the [guidelines](https://kyma-project.io/community/governance/01-governance/#when-does-a-maintainer-lose-the-maintainer-status), he can be removed from the codeowners.
- Remove Krystian (`crabtree`) from codeowners
> Remove crabtree from codeowners

- resources/kcp/values.yaml
Bump to reconciler image with tag 943e0e86
> Bump to reconciler image 943e0e86

- components/kyma-environment-broker/internal/provider/azure_provider.go
- components/kyma-environment-broker/internal/provider/azure_provider_test.go
- Changed default Azure region from `westeurope` to `eastus`
tools/documentation/182
> Change default Azure region to eastus

- resources/kcp/values.yaml
Bump reconciler images to bb1616d4
> Bump reconciler images to bb1616d4

- resources/kcp/values.yaml
Bump reconciler image to 1ff7cd81
> Bump to reconciler image 1ff7cd81

- CODEOWNERS
add jellyfish team to code owners
> add jellyfish team to code owners

- components/kyma-environment-broker/cmd/broker/provisioning_test.go
- components/kyma-environment-broker/internal/broker/plans.go
- components/kyma-environment-broker/internal/provider/aws_provider.go
- docs/kyma-environment-broker/03-01-service-description.md
- resources/kcp/values.yaml
- remove AWS m6 machines from the offering (but allow in validation schema)
> Switch to AWS m5 machines

- OWNERS_ALIASES
> Remove console approvers from OWNERS_ALIASES

- resources/kcp/values.yaml
> use old version

- resources/kcp/values.yaml
> fix format

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration.go
- components/kyma-environment-broker/internal/reconciler/client.go
- resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
- resources/kcp/charts/kyma-environment-broker/values.yaml
- resources/kcp/values.yaml
- define separate timeout for reconciliation in the provisioning process
- delete cluster if the provisioning reconciliation takes too much time
> Delete cluster config on reconciliation timeout

- CODEOWNERS
- OWNERS
- Cleans up OWNERS and CODEOWNERS
> Cleans up OWNERS and CODEOWNERS

- CODEOWNERS
- OWNERS
- resources/kcp/OWNERS
Cleans up OWNERS from resources/kcp
> Cleans up OWNERS from resources/kcp

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/cmd/broker/update_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration_test.go
- components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
- components/kyma-environment-broker/internal/reconciler/fake.go
- resources/kcp/values.yaml
- clean CLusterConfigurationVersion must be cleaned after the deletion is completed
> Clean CLustertConfigurationVersion after the deletion is completed

- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
Bumping the migrator tool to latest release v4.15.1
> Bump schema-migrator to v4.15.1

- components/kyma-environment-broker/internal/process/update/initialisation_step.go
- resources/kcp/values.yaml
- pending update operation must fail, if the instance is already deprovisioned
> Fail update operation, if the instance is already deprovisioned

- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
- components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
- resources/kcp/values.yaml
- because we do not have srtages in the upgrade kyma process, the check step must be the first one - to prevend unecessary running other steps after the reconciler is called
> Move check cluster configuration to the begining

- tools/reconciler/e2e-test/template.json
The pipeline `periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade` currently upgrades kyma1 to main, but we want it to upgrade it to a released kyma2 version, which is currently 2.0.2
- curl request want to upgrade to kyma 2.0.2
- ...
- ...
> Change kyma upgrade from main to 2.0.2 in `periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade`

- components/kyma-environment-broker/internal/fixture/fixture.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
- components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
- resources/kcp/values.yaml
- fill KymaVersion field in RuntimeStateDTO when preparing dto for saving in DB
#1264
> Fix Kyma version placement in RuntimeStateDTO

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.keb
- components/kyma-environment-broker/Dockerfile.sac
- components/schema-migrator/Dockerfile
- resources/kcp/values.yaml
- bump golang img (builder) to 1.17.6
- bump alpine to 3.14.3
> Bump golang builder image to 1.17.6

- resources/kcp/values.yaml
> Upgrade reconciler after merging pr 701

- tests/e2e/provisioning/pkg/client/runtime/dashboard_checker.go
- tests/e2e/provisioning/test/e2e_provisioning_test.go
- tests/e2e/provisioning/test/e2e_suspension_test.go
- tests/e2e/provisioning/test/test_suite.go
- Corrected dashboard redirection
> Corrected Redirection to Busola

- resources/kcp/charts/component-reconcilers/templates/deployment.yaml
- resources/kcp/charts/component-reconcilers/values.yaml
- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
try to add `nodeSelector` which requirements from the [K8S resource configurations for reconciler workloads](https://github.tools.sap/kyma/backlog/issues/2239)
> add nodeSelector in the deployment.yaml of mothership/component-reconciler 

- components/provisioner/Dockerfile
- components/provisioner/go.mod
- components/provisioner/go.sum
- components/subscription-cleanup-job/Dockerfile
- components/subscription-cleanup-job/go.mod
- components/subscription-cleanup-job/go.sum
- resources/kcp/values.yaml
- Bump Golang Runtime in Provisioner and SCJ
> Bump Golang Runtime in Provisioner and SCJ

- resources/kcp/values.yaml
Upgrade Reconciler after merging https://github.com/kyma-incubator/reconciler/pull/703
- ...
- ...
- ...
> Upgrade reconciler

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
- components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
- resources/kcp/values.yaml
- fix cluster deregistration timeout
> Fix KEB timouet on deprovisioning

- components/kyma-environment-broker/internal/avs/model.go
- resources/kcp/values.yaml
- avs interval updated from 180s to 60s
> interval updated

- resources/kcp/charts/component-reconcilers/templates/pdb.yaml
- resources/kcp/charts/component-reconcilers/values.yaml
- resources/kcp/charts/mothership-reconciler/templates/pdb.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
try to add pdb for the task [K8S resource configurations for reconciler workloads](https://github.tools.sap/kyma/backlog/issues/2239)
> add pdb for component-reconcilers and mothership-reconciler

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/main.go
- components/kyma-environment-broker/go.mod
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/update/btp_operator_check.go
- components/kyma-environment-broker/internal/process/update/btp_operator_check_test.go
- components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
- resources/kcp/values.yaml
- SC migration must be blocked if the BTP Operator is already installed
fixes https://github.com/kyma-project/control-plane/issues/1271
> Prevent SC migration if BTP operator exists

- tools/reconciler/e2e-test/template.json
- Add the missing `istio-resources` component
https://github.com/kyma-project/control-plane/issues/1296
> Fix the `pre-main-control-plane-reconciler-e2e` pipeline

- resources/kcp/values.yaml
Update reconciler versions
Includes fix: https://github.com/kyma-incubator/reconciler/pull/718
> Bump reconciler version

- tools/reconciler/e2e-test/request-reconcile.sh
> Some more debug info

- docs/kyma-environment-broker/03-03-runtime-operations.md
- Description of Reconciler timeout when invoked from KEB.
> Reconciler Timeout Note

- resources/kcp/templates/registration-job.yaml
- Added new scope necessary to retrieve auth info from Compass.
> Add new scope to registration job

- components/kyma-environment-broker/cmd/broker/broker_suite_test.go
- components/kyma-environment-broker/cmd/broker/suite_test.go
- components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
- components/kyma-environment-broker/internal/provisioner/fake_client.go
- resources/kcp/values.yaml
- Upgrade shoot operation must not use provisioning parameters from the provisioning operation but the newest one
Resolves: https://github.com/kyma-project/control-plane/issues/1299
> Upgrade process uses correct gardener params

- tools/reconciler/e2e-test/template-kyma-2-0-x.json
- tools/reconciler/e2e-test/template-kyma-main.json
Chicken-Egg Problem with: https://github.com/kyma-project/test-infra/pull/4868
- ...
- ...
- ...
> Prepare two templates for different kyma version

- tools/cli/go.mod
- tools/cli/go.sum
> KCP CLI: fix go mod tidy failing in CI

- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/broker/logging.go
- components/kyma-environment-broker/internal/broker/logging_test.go
- resources/kcp/values.yaml
- KEB logs incoming request contexts
Example of logged context:
```
time="2022-02-02T14:20:18+01:00" level=info msg="Provision called with context: {\"globalaccount_id\":\"g-account-id\",\"sm_platform_credentials\":{\"credentials\":{},\"url\":\"*****\"},\"subaccount_id\":\"sub-id\",\"user_id\":\"*****\"}" instanceID=139f1bc6-0a5a-43dc-81e7-f01a51c5f666 operationID=76ab18d8-9d73-4cf8-9f91-97eb42e312c9 planID=7d55d31d-35ae-4438-bf13-6ffdfa107d9f service=ProvisionEndpoint
time="2022-02-02T14:20:18+01:00" level=info msg="Received context: {\"globalaccount_id\":\"g-account-id\",\"user_id\":\"*****\"}" instanceID=139f1bc6-0a5a-43dc-81e7-f01a51c5f666 service=UpdateEndpoint
```
If you want to see such logging, you can run any test from the …
> Log incoming requests in KEB

- components/kyma-environment-broker/cmd/broker/main.go
- resources/kcp/values.yaml
- finalization update process for sc-migration must be in separate stage to not rerun migration
> Introduce separate stage for update sc-migration finalization process

- resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
> fixed mothership reconciler pgHost value

- resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
- resources/kcp/charts/mothership-reconciler/values.yaml
- configurable liveness/readiness probes
- Increase default timeout to 2 seconds
> mothersip-reconciler: configurable liveness/readiness probes

- components/kyma-environment-broker/internal/broker/instance_deprovision_test.go
- components/kyma-environment-broker/internal/model.go
- components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
- resources/kcp/values.yaml
- tools/cli/pkg/ers/client.go
- Deprovisioning operation must be created as pending
> Deprovisioning operations should be created as Pending

- components/kubeconfig-service/Dockerfile
- resources/oidc-kubeconfig-service/values.yaml
- Fix dockerfiles linting issues according to hadolint
> Fix dockerfile linting - 1

- resources/kcp/values.yaml
- Fix for reconciler race condition when a new reconciliation switching from reconcile to delete or vice versa mid reconciliation.
https://github.com/kyma-incubator/reconciler/issues/782
> Bump reconciler: reconcile/delete race condition

- resources/kcp/values.yaml
https://github.com/kyma-project/third-party-images/pull/185
> Bump third party images containing latest OpenSSL release

- components/kyma-environment-broker/Dockerfile.cleanup
- components/kyma-environment-broker/Dockerfile.keb
- components/kyma-environment-broker/Dockerfile.sac
- components/kyma-environment-broker/go.mod
- components/kyma-environment-broker/go.sum
- resources/kcp/values.yaml
Bump prometheus client to v1.12.0, go version to 1.17.7 and alpine image 3.15.0.
> Bump prometheus 1.12.0, go 1.17.7 and alpine versions 3.15.0

- resources/kcp/values.yaml
Reconciler Image needs to upgrades due to a DB fix.
> Bump Reconciler Image

- resources/kcp/values.yaml
upgrade to reconciler image `3cc61b26`
> upgrade to latest reconciler version

- components/kyma-metrics-collector/go.mod
- components/kyma-metrics-collector/go.sum
- resources/kcp/values.yaml
- Bump prometheus client_golang
> Bump prometheus client_golang

- CODEOWNERS
- Removed `sayan` as codeowner
- Added Faizan, Friedrich and Vlad as codeowners for KMC.
> Updated codeowners for KMC

- resources/kcp/charts/kyma-metrics-collector/templates/policy.yaml
- resources/kcp/charts/kyma-metrics-collector/templates/service.yaml
- resources/kcp/charts/kyma-metrics-collector/values.yaml
- Enabled sidecar injection for KMC pod.
- Added Istio PeerAuthentication `PERMISSIVE` policy for KMC.
https://github.com/kyma-project/kyma/issues/13472
> Enable service-mesh for KMC

- components/kyma-environment-broker/internal/process/input/input.go
- components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration.go
- resources/kcp/values.yaml
- if the cluster was provisioned without user_id (old ones) - do not send administrator list
> Send empty administrator list if user_id was not set

- components/kyma-environment-broker/internal/broker/instance_create.go
- components/kyma-environment-broker/internal/broker/instance_update.go
- components/kyma-environment-broker/internal/broker/instance_update_test.go
- components/kyma-environment-broker/internal/dto.go
- resources/kcp/values.yaml
- add OIDC input validation on Provisioning, Update endpoints
> Add OIDC input validation

- CODEOWNERS
- github raised a few errors for the CODEOWNERS. This PR fixes them. They are all in the form of 
```
Unknown owner on line XX: make sure XXXX exists and has write access to the repository
```
> remove users from CODEOWNERS to fix errors

- resources/kcp/values.yaml
- bump cloudsql-gce-proxy version to [1.29.0](https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases/tag/v1.29.0)
> Bump cloudsql-proxy to v1.29.0
